### ISSUE TITLE
multi sample somatic calling

### ISSUE THREAD

**Issue by ruping** [PapenfussLab/gridss#103]
Hi Daniel,

  I have a confusion with the multi sample somatic calling. Say there is one normal sample, two tumor samples, by specifying three INPUTs each as the corresponding bam file, how does GRIDSS treat them? 

  Are the calls in the output vcf based on a joint quality assessment for all three INPUTs? For one tumor and one normal, it seems to me that it requires a post-processing (a R script) to obtain somatic calls. For more than one tumor sample, I am not sure how to proceed and any suggestions are much appreciated. Thank you!

Best,
Ruping,

**Comment by ruping** [comment]
My main concern is that when multiple libraries are supplied as inputs, does GRIDSS pool all the abnormal reads from different libraries and perform a all-in-one assembly, or does GRIDSS perform library specific assembly and then merge the assembled breakpoint sequences together to seek the supporting evidence from each library for each breakpoint? 

Thanks!

**Comment by d-cameron** [comment]
>does GRIDSS pool all the abnormal reads from different libraries and perform an all-in-one assembly

It does. This improves the assembly quality for variants shared between samples.

> For one tumor and one normal, it seems to me that it requires a post-processing (a R script) to obtain somatic calls.

It does. There is an example script of simple post-processing somatic calling aat https://github.com/PapenfussLab/gridss/blob/master/example/somatic.R

>Say there is one normal sample, two tumor samples, by specifying three INPUTs each as the corresponding bam file, how does GRIDSS treat them?

By default, GRIDSS treats each input file as a sample so will report overall variant information, and provide a per-sample breakdown. This has been quite useful for some of the work we have done with tumour evolution as you can see changes allele frequency (calculated from the supporting read breakdowns and the REF/REFPAIR fields) across multiple related tumours.
