### ISSUE TITLE
how to explain ALT flag in the vcf ?

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#117]
hi,
   I saw  these result at the ALT flag , like C]chr1:838464] , ]chr1:1105073]C, ]chr6:117642092]A,
   what is the meaning  of the  character  '[' or ']' ??  
    the flag  "]chr6:117642092]A "  means that  the breakpoint position is  chr6-117642093 ?

Expecting your answer !

**Comment by d-cameron** [comment]
This is standard VCF notation and is covered in section 5.4 of the [VCF file format specifications document](https://samtools.github.io/hts-specs/VCFv4.3.pdf).
