### ISSUE TITLE
how to calculate the  VAF about gene fusion from SV ?

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#119]
HI,
   I  wanna use gridss to call gene fusion  ,it'is possible ? ??
   if is ,how to calculate the VAF via the gridss result ?

thank you !

**Comment by d-cameron** [comment]
GRIDSS reports the supporting read and read pair counts for both the reference and the variant. The VAF can be calculated from this. Here is the function I'm currently using for a large pan-cancer project.

```
gridss_af = function(gr, vcf, i=1) {
	g = geno(vcf[names(gr)])
	ref = g$REF[,i]
	refpair = g$REFPAIR[,i]
	# assembly counts must be halved for reciprocal assemblies since
	# we independently eassemble the same reads on both sides
	assembled_read_weight = ifelse(str_detect(gr$FILTER, "SINGLE_ASSEMBLY"), 1, 0.5)
	assrrp_af = ((g$ASSR[,i] + g$ASRP[,i]) * assembled_read_weight)/((g$ASSR[,i] + g$ASRP[,i]) * assembled_read_weight + ref + refpair)
	srrp_af = (g$SR[,i] + g$RP[,i]) / (g$SR[,i] + g$RP[,i] + ref + refpair)
	assr_af = (g$ASSR[,i] * assembled_read_weight) / (g$ASSR[,i] * assembled_read_weight + ref)
	# it is questionably whether we should incoproate BSC.
	# It's definitely incorrect in the case of promiscuous breakpoints
	sr_af = (g$SR[,i]+g$BSC[,i])/(g$SR[,i]+g$BSC[,i]+ref)

	# a complete assembly will give the most accurate AF, but
	# a fragmented assembly will underestimate
	ifelse(is_short_deldup(gr), pmax(assr_af, sr_af), pmax(assrrp_af, srrp_af))
}
gridss_somatic_af = function(gr, vcf) {
	return(gridss_af(gr, vcf, 2))
}
```

**Comment by WinterLi1993** [comment]
@d-cameron 
I rememver you said  for high coverage sample, should not use  AS* ?
I check you VAF function :  
assrrp_af = ((g$ASSR[,i] + g$ASRP[,i]) * assembled_read_weight)/((g$ASSR[,i] + g$ASRP[,i]) * assembled_read_weight + ref + refpair)
assr_af = (g$ASSR[,i] * assembled_read_weight) / (g$ASSR[,i] * assembled_read_weight + ref)

how to change your code to be suitable for my data ?

**Comment by d-cameron** [comment]
That code should be fine as `pmax(assr_af, sr_af), pmax(assrrp_af, srrp_af)` will use the direct read counts when you're missing an assembly due to your extremely high coverage.

**Comment by WinterLi1993** [comment]
@d-cameron 
  I use R version  3.4 ... can not install  'VariantAnnotation' package . 
  so could you please give  python scripts to calculate VAF   ?

thank you in advance !

**Comment by WinterLi1993** [comment]
HI, @d-cameron 
I use the following format to calculate VAF . 
srrp_af = (g$SR[,i] + g$RP[,i]) / (g$SR[,i] + g$RP[,i] + ref + refpair)
sr_af = (g$SR[,i]+g$BSC[,i])/(g$SR[,i]+g$BSC[,i]+ref)

I got this value 9.99999963208652e-08 and  9.999996322031264e-05 ;
It's very small !!!!
but I know my VAF should be at 15% ; 
So what happened ??

**Comment by WinterLi1993** [comment]
@d-cameron 
when I use  (RP + SR)  / (REF+REFPAIR+RP + SR) , ,the result is 25% ... 
So   wheter  (RP + SR)  / (REF+REFPAIR+RP + SR)  is correct to calculate VAF   ??
