### ISSUE TITLE
how to convert gridss result into gene fusion format  ?

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#121]
@d-cameron 
what the difference between these two records ? they are for the same SV ?
and the more important question for me : 
  how to convert gridss result into gene fusion format  ?
like 
ChrA ,POSA,GeneA ,ChrB,POSB,GeneB 

thank you! 

chr9	133729678	gridss167_928o	T	]chr22:23634671]T	26661.14	.	AS=1;ASQ=9798.25;ASRP=568;ASSR=255;BA=0;BAQ=0.00;BEID=asm167-3386,asm285-1564;BQ=1968.58;BSC=81;BSCQ=1968.58;BUM=0;BUMQ=0.00;CAS=0;CASQ=0.00;CQ=26400.87;EVENT=gridss167_928;IC=0;IHOMPOS=0,0;IQ=0.00;PARID=gridss167_928h;RAS=1;RASQ=8851.51;REF=2576;REFPAIR=470;RP=287;RPQ=6093.37;SC=1X356M;SR=70;SRQ=1918.00;SVTYPE=BND	GT:ASQ:ASRP:ASSR:BAQ:BQ:BSC:BSCQ:BUM:BUMQ:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ	.:9798.25:568:255:0.00:1968.58:81:1968.58:0:0.00:0.00:0:0.00:26661.14:8851.51:1160:185:287:6093.37:70:1918.00	.:0.00:0:0:0.00:0.00:0:0.00:0:0.00:0.00:0:0.00:0.00:0.00:1416:285:0:0.00:0:0.00

chr22	23634671	gridss167_928h	C	C[chr9:133729678[	26757.49	.	AS=1;ASQ=8851.51;ASRP=568;ASSR=255;BA=0;BAQ=0.00;BEID=asm167-3386,asm285-1564;BQ=1021.84;BSC=42;BSCQ=1021.84;BUM=0;BUMQ=0.00;CAS=0;CASQ=0.00;CQ=26400.87;EVENT=gridss167_928;IC=0;IHOMPOS=0,0;IQ=0.00;PARID=gridss167_928o;RAS=1;RASQ=9798.25;REF=2746;REFPAIR=259;RP=287;RPQ=6093.37;SC=391M1X;SR=73;SRQ=2014.36;SVTYPE=BND	GT:ASQ:ASRP:ASSR:BAQ:BQ:BSC:BSCQ:BUM:BUMQ:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ	.:8851.51:568:255:0.00:1021.84:42:1021.84:0:0.00:0.00:0:0.00:26757.49:9798.25:1365:73:287:6093.37:73:2014.36	.:0.00:0:0:0.00:0.00:0:0.00:0:0.00:0.00:0:0.00:0.00:0.00:1381:186:0:0.00:0:0.00

**Comment by d-cameron** [comment]
> what the difference between these two records ? they are for the same SV ?

Please read the VCF file format specifications at https://samtools.github.io/hts-specs/VCFv4.3.pdf
GRIDSS writes VCF 4.3 compliant VCF files. If you are unable to interpret valid VCF files, I recommend https://www.biostars.org/ and http://seqanswers.com/ as useful places to ask questions.


>how to convert gridss result into gene fusion format ? like ChrA ,POSA,GeneA ,ChrB,POSB,GeneB

This is not trivial. Do you care about reading frame? Orientation? How do you handle overlapping genes? Which transcripts? Have you looked at examples/somatic-fusion-gene-candidates.R ?
