### ISSUE TITLE
it'is suitable for tumor only  from target panel sequencing?

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#122]
HI,
  I  just have only one tumor sample via target panel sequencing , gridss can do somatic calling for that ?
  I know gridss can deal with one sample bam .

**Comment by d-cameron** [comment]
I've only done this for tumour-only WGS but I don't see a reason this couldn't, in theory, be done for targeted sequencing as well.

See https://link.springer.com/chapter/10.1007%2F978-3-319-42044-8_27
