### ISSUE TITLE
gridss release 1.5.1 fails to run with picard error

### ISSUE THREAD

**Issue by RS1979** [PapenfussLab/gridss#125]
I grabbed version 1.5.1 of gridss releases and adapted the somatic.sh script to my case: search for somatic structural variants, given a tumor and a matching normal sample, just replacing some filenames.

When I run that script, I get an error at the step "Attempting to create sequence dictionary for *reference file*". The error is "ERROR: Unrecognized option: REFERENCE_SEQUENCE". Then it spits out usage help of the picard tools function CreateSequenceDictionary, which indeed states that there is no option REFERENCE_SEQUENCE. So it seems gridss is trying to invoke picard tools with an option that is not valid. I'm a bit at a loss why I should do that or even which picard tools it tries to use (internal/external?). I checked all my picard-tools versions on the server (the newest one is 2.10.3), and none of them allow an option REFERENCE_SEQUENCE for CreateSequenceDictionary. The correct option is REFERENCE or R. So, am I doing something completely wrong, or is there a problem with the picard tools invocation at that step?

I then tried to perhaps circumvent the problem by building from source (which hopefully links picard tools and gridss correctly), and run into an error during build tests. But I will open another issue for that.

**Comment by d-cameron** [comment]
You're missing a sequence dictionary for your genome reference.

> The correct option is REFERENCE or R. So, am I doing something completely wrong, or is there a problem with the picard tools invocation at that step?

You're fine, picard tools just lacks a consistent reference sequence command line argument name for all the picard tools across all the versions I've been using it. I've switched to the shorthand R which should always work.
