### ISSUE TITLE
Test during building from source fails

### ISSUE THREAD

**Issue by RS1979** [PapenfussLab/gridss#126]
I tried to build gridss from source with the command from the readme:
```
git clone https://github.com/PapenfussLab/gridss
mvn clean package
```
(mvn invoked, of course, after changing the directory into gridss, which is not mentioned in the readme)

The build failed during testing:
```
Running au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest
INFO	2018-04-05 16:29:18	ExternalProcessStreamingAligner	Starting external aligner
INFO	2018-04-05 16:29:18	ExternalProcessStreamingAligner	C:/dev/bin/snap-beta.18-windows/snap.exe single C:/dev/bin/snap-beta.18-windows -wbs 1 -map -fastq - -o -sam -
INFO	2018-04-05 16:29:19	ExternalProcessStreamingAligner	Starting external aligner
INFO	2018-04-05 16:29:19	ExternalProcessStreamingAligner	C:/dev/bin/snap-beta.18-windows/snap.exe single C:/dev/bin/snap-beta.18-windows -wbs 1 -map -fastq - -o -sam -
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE! - in au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest
basic_pipes_test(au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.io.IOException: Cannot run program "C:/dev/bin/snap-beta.18-windows/snap.exe": error=2, Datei oder Verzeichnis nicht gefunden
	at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest.basic_pipes_test(ExternalProcessStreamingAlignerTest.java:21)
Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
	at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest.basic_pipes_test(ExternalProcessStreamingAlignerTest.java:21)

ping_pong_pipes_test(au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.io.IOException: Cannot run program "C:/dev/bin/snap-beta.18-windows/snap.exe": error=2, Datei oder Verzeichnis nicht gefunden
	at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest.ping_pong_pipes_test(ExternalProcessStreamingAlignerTest.java:40)
Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
	at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAlignerTest.ping_pong_pipes_test(ExternalProcessStreamingAlignerTest.java:40)
```
To me it looks as if the test tries to start a Windows executable at C:\dev\bin, which of course does not exist on my linux machine (and should probably not exist on any random windows machine). It seems you have a hard-coded dependency that is not mentioned anywhere and breaks maven's dependency management, at least for the tests.

How do I build gridss successfully? Will switching to an older version result in a successful build? Can I suppress or circumvent that test fail?

**Comment by d-cameron** [comment]
>How do I build gridss successfully?

`mvn package -DskipTests`, or just download the pre-built jar from the releases.

> It seems you have a hard-coded dependency that is not mentioned anywhere and breaks maven's dependency management, at least for the tests.

That particular issue just got fixed in the dev branch last week. It now uses bwa, and attempts to use Windows Subsystem for Linux (WSL) bwa for windows machines. It still does rely on a hg19 chr12.fa existing with a bwa index so I've removed external aligner tests from the maven automated unit testing.

The latest `dev` branch should now work without having to skip unit testing.
