### ISSUE TITLE
failure to install R package 

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#127]
HI,
 for these code , i need to install some necessary package , but  can not install   VariantAnnotation and devtools package successfully !!! 

any other alternative tools like Python package ??

source("https://bioconductor.org/biocLite.R")
biocLite("VariantAnnotation")
library(stringr)
library(VariantAnnotation)
library(devtools)
install_github("PapenfussLab/StructuralVariantAnnotation")
library(StructuralVariantAnnotation)

thank you in advance !

**Comment by d-cameron** [comment]
> any other alternative tools like Python package ??

There might be but I am not aware of any.

**Comment by d-cameron** [comment]
Duplicate of #118
