### ISSUE TITLE
BND  vs DEL 

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#132]
@d-cameron 
I know you  use BND to flag all detected SV . But as we know DEL is different with BND .
BND means translocation(inter-chr) .
so  it's wrong with your definition ???

**Comment by d-cameron** [comment]
> BND means translocation(inter-chr)

No it doesn't. Interchromosomal translocations must be reported in the BND notation, but tools have a choice of three different notations for reporting deletion events. Deletion events can be reported directly using non-symbolic alleles (e.g. SNV & small indels callers use this notation), using SVTYPE=DEL, or by using breakend BND notation. GRIDSS reports using BND notation.

> so it's wrong with your definition ???

Being a member of the GA4GH working group responsible for writing and updating the VCF specifications, I am quite sure my definition is correct.

**Comment by WinterLi1993** [comment]
So  BND stands for what ??

**Comment by d-cameron** [comment]
Have you actually read the[ VCF file format specifications](https://samtools.github.io/hts-specs/VCFv4.3.pdf) like I recommended?

**Comment by WinterLi1993** [comment]
BND just means a breakend record. @d-cameron

**Comment by d-cameron** [comment]
Correct. It could constitute part of a DEL, and INS, a DUP, a chromosomal shattering or any other type of event. You might be interested in another tool from our lab: https://github.com/PapenfussLab/clove. It converts the breakends into SV event calls. E.g. calling a deletion for breakends in the correct orientation that also have a copy number loss in the deleted region.

**Comment by fitbio** [comment]
Hi,
I want to use clove for further analysis for the structural variants to capture complex events. Could you please tell me in clove option how do I get the values for mean coverage and coverage variance .?
