### ISSUE TITLE
Identify transgene insertion position with gridss

### ISSUE THREAD

**Issue by frymor** [PapenfussLab/gridss#133]
Hi,
I was wondering if it is possible to identify the insertion positions of our transgene in the mouse genome using gridss?
We have inserted a transgene into the mouse blastocystes. We can see a phenotype, but we don't really know, where these transgene was integrated in the mouse genome. 
I was wondering if it is possible to do this kin of analysis with gridss and identify the nucleotide-specific position of the insertion. 
If so, Do I need to map the sample to a genome constrains of both the mouse and the transgene genome or only of the mouse (or transgene)?

thanks 

Assa

**Comment by frymor** [comment]
Hi, I have two questions - do Socrates and gridss are the same tool? 
Is there any development in the new release?
thanks
Assa

**Comment by d-cameron** [comment]
Whilst Socrates and GRIDSS do use the same approach to identify split reads from soft clipped reads, they are different tools. Socrates performs only the split read analysis, whereas GRIDSS also incorporates read pair analysis and assembly. GRIDSS is a much more sophisticated tools should be used in preference to Socrates.

Details on the new features in the latest GRIDSS release can be found in the release notes found at https://github.com/PapenfussLab/gridss/releases. The new single breakend detection capability could be relevant to your project.
