### ISSUE TITLE
GRIDSS VCF FILTER

### ISSUE THREAD

**Issue by saty89** [PapenfussLab/gridss#138]
Hi, Just wondering what does '.' mean in the FILTER Column of GRIDSS Vcf. Does it mean as "Undetermined" even though the quality looks good (>500) for some breakpoints ? When using CLOVES to classify the GRIDSS output it treats them as FAILED/"." even though the quality is good. So I would like to understand GRIDSS output first.

**Comment by d-cameron** [comment]
"." is synonymous with "PASS" as it indicates that no filters were applicable for that variant call. Re-reading the VCF specifications, it does indeed appear to be the case that GRIDSS should be using PASS instead of "." as the filter checks were indeed performed.

**Comment by saty89** [comment]
Thanks that makes sense now. As "." in the standard VCF specifications is used bit differently. Do you plan to make this fix soon ?

**Comment by d-cameron** [comment]
Thanks for raising the issue.
Patched in 4afb082f3e9202a8ba683a0ee3830d85bbd67947. Will be included in the next GRIDSS release

**Comment by d-cameron** [comment]
https://github.com/PapenfussLab/gridss/releases/tag/v1.7.2

**Comment by saty89** [comment]
Hi Daniel,

I have a question regarding GRIDSS for Tumour-Normal pairs. We currently
process them through GRIDSS but wondering if GRIDSS actually uses the
information of being a tumour-normal pair or just considers as multiple bam
files for a given input?

Thanks,
Satwica

**Comment by d-cameron** [comment]
> GRIDSS actually uses the information of being a tumour-normal pair 

Yes, GRIDSS does joint assembly and variant calling when given multiple files. There are some scripts in the example directory that do some very basic somatic filter (somatic.R) - note how that when joint calling, the QUAL score is broken by sample which make it very easy to determine events present only the the tumour (or normal for somatic LoH events).

This capability is particularly useful when looking at related somatic samples (e.g. multiple biopsies) at is enables the detection of very low allelic fraction subclonal variants when the variant is present at a higher allelic fraction in another related sample.
