### ISSUE TITLE
Mate-pair library support

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#14]

**Comment by proukakis** [comment]
hi, this would be good, although i only have a couple of samples I would like to run them. Do you know if it will be added soon>
thanks
christos

**Comment by d-cameron** [comment]
The problem is that large fragment sizes make the assembly step slow. This will get fixed when I switch to an OLC assembler but realistically, that's 6-18 months away. All my collaborators are moving to long reads or chromium for SVs so mate-pair support is rather low on the priority list.

Cheers
Daniel
