### ISSUE TITLE
Crash: Too many open files

### ISSUE THREAD

**Issue by student-t** [PapenfussLab/gridss#146]
[gridss_JFCF6_SV.log](https://github.com/PapenfussLab/gridss/files/2113795/gridss_JFCF6_SV.log)

Attached the crash log. My command was also in there. Error message (line 8177):

    (Too many open files)

**Comment by student-t** [comment]
I think the program had too many temp open files on my WGS sample. Should I reduce the number of threads?

**Comment by fitbio** [comment]
My colleague and I recently ran gridds in wgs samples. The number of threads we specified was 24 WORKER THREADS. But before running gridds, I removed the temporary files and as well the folders created by gridds. It worked just fine after that.

**Comment by d-cameron** [comment]
This is a known issue. See https://github.com/PapenfussLab/gridss#error-messages for your choice of 3 possible resolutions to this error message.
