### ISSUE TITLE
Better somatic arguments?

### ISSUE THREAD

**Issue by student-t** [PapenfussLab/gridss#147]
I'm using the script on https://github.com/PapenfussLab/gridss/blob/master/example/somatic.sh for making a somatic call.

What concern me is the inputs:

	INPUT="$NORMAL" \
	INPUT="$TUMOUR" \

They are both "INPUT", what if we mix up the orders - the normal sample is given to the second option? The program apparently assumes that the first file is the normal sample, and the second file is tumor. This is not very explicitly stated and might cause confusion.

Can you please add something like "NORMAL=$NORMAL" and "TUMOR="$TUMOR"?

**Comment by d-cameron** [comment]
>Can you please add something like "NORMAL=$NORMAL" and "TUMOR="$TUMOR"?

Early versions of GRIDSS had this and I changed it to the current approach as our requirements expanded. Simple NORMAL/TUMOUR is too much of a special case: we've used GRIDSS for comparing between multiple metastases from the same patient and even mouse xenografts where we have 10+ related tumours that we reconstruct an evolutionary tree from the SVs.

>The program apparently assumes that the first file is the normal sample, and the second file is tumor. This is not very explicitly stated and might cause confusion.

GRIDSS doesn't actually care what is normal and what is tumour. It just calls multiple samples. The downstream analysis does care but that isn't too much of a problem as the only thing the ordering changes is the sample ordering in the VCF.

If you look at https://github.com/PapenfussLab/gridss/blob/master/example/somatic.R:14 you'll see that this example uses the sample name (which defaults to the file name) and not the ordinal to refer to the tumour and normal samples. Even if you did get the INPUT ordering incorrect, using explicit sample naming in the downstream analysis means this doesn't matter.
