### ISSUE TITLE
Crash: BinaryCodec in readmode; file?

### ISSUE THREAD

**Issue by student-t** [PapenfussLab/gridss#148]
[gridss.somatic.hpc147.240026.log](https://github.com/PapenfussLab/gridss/files/2126657/gridss.somatic.hpc147.240026.log)

I have got a crash in my input file, which is a valid BAM file.

**Comment by d-cameron** [comment]
> Caused by: java.io.IOException: Cannot allocate memory

Looks like you ran out of memory. A few possibililties:

- Not enough memory allocated to the JVM
 
- The computer you are running it on does not have enough memory

  -- the example gridss.sh uses -Xmx31g. This will only work if your computer has more than 32Gb of memory. You can drop this down to -Xmx8Gb pretty safely if you use too many threads at onoce.

- Rerun GRIDSS and it will continue from where it left off.
