### ISSUE TITLE
Bug: BWA mem -t should not be the memory

### ISSUE THREAD

**Issue by student-t** [PapenfussLab/gridss#151]
Hi,

    public static final List<String> BWA_COMMAND_LINE = ImmutableList.of("bwa", "mem", "-t", "%3$d", "%2$s", "%1$s");

    realigner.createSupplementaryAlignments(aligner, INPUT, OUTPUT, MAX_RECORDS_IN_RAM);

Are the lines correct? Number of threads BWA run should depend on the number of given working threads and probably not the number of records in RAM.

I'm encountering the problem as GRIDSS would internally spawn 64 threads BWA on a single core machine.

**Comment by d-cameron** [comment]
> Are the lines correct? Number of threads BWA run should depend on the number of given working threads and probably not the number of records in RAM.

Thread count is driven by the WORKER_THREADS parameter. You can see this in the log file as GRIDSS echos the aligner command line to INFO prior to invoking:
```
log.info("Invoking external aligner");
log.info(commandlinestr);
```

Note that the alignment invocation `aligner.align(fq, tmpout, pc.getReferenceFile(), workerThreads);` in createSupplementaryAlignments() is driven by workerThreads which in turn is set by SoftClipsToSplitReads.java:78
```
realigner.setWorkerThreads(WORKER_THREADS);
```

> I'm encountering the problem as GRIDSS would internally spawn 64 threads BWA on a single core machine.

GRIDSS spawning 60+ threads is a different issue to the number of threads passed to BWA. 64 threads is not unexpected and if you run a jstack trace or inspect with jvisualvm you can see the name of each of the threads. Generally these will be the standard java threads (GC, etc), main, the worker thread pool  (the number of these matches the WORKER_THREADS parameter), a thread with a file name will generally be an async thread for file reading, another thread pool (set to # cores on the machine regardless of WORKER_THREADS - this is htsjdk code) for async BAM decompression, and a few other assorted async buffering threads. The majority of these threads will be blocking and the fact that there are 60 idle threads is not problematic for a program that requires multiple gigabytes of memory.

**Comment by d-cameron** [comment]
Also note that WORKER_THREADS defaults to the number of cores reported by the OS. It does not default to single-core operation.
