### ISSUE TITLE
[help] interpretation of GRIDSS Somatic result.

### ISSUE THREAD

**Issue by FWTT** [PapenfussLab/gridss#158]
I got results by running GRIDSS on paired normal, tumor samples.

and then, I filtered the `vcf` file through the R script. 

I visualized `bam` with `IGV` using the coordinates of the bed file format.

I expected a `Structural Variation` with a significant difference between Tumor and Normal.

However, most of the intrachromosomal SVs were variants in Normal as well as Tumor.

Even if I gave a Quality score of 1000 or more, this trend did not change.

I don't know if I need an additional process to get a significant difference in paired sample.

I would appreciate your help.

**Comment by d-cameron** [comment]
> I filtered the vcf file through the R script.

The script is designed to serve as an example, not a turn-key solution.

> However, most of the intrachromosomal SVs were variants in Normal as well as Tumor.

Then the script is not filtering your variants correct. For example:
```
somatic_vcf <- vcf[geno(vcf)$QUAL[,"normal.bam"] == 0,]
```

If your normal bam is not literally named `normal.bam` then this line will fail to work correctly. The VCF is a standard `VariantAnnotation` VCF file so you can do all the usual bioconductor manipulations on it.

You don't need to convert to bedpe: you can also filter the VCF directly. Something like `writeVcf("somatic.vcf", somatic_vcf) should return you the somatic subset of variants.

>Even if I gave a Quality score of 1000 or more, this trend did not change.

There's a bug (#156) in 1.8.0 that causes some QUAL scores to report NaN which will mess up the somatic.R scripts for a subset of the variants. I've got a fix in the dev branch, I'm just waiting on some whole genome regression tests before formally releasing it.

**Comment by FWTT** [comment]
I proceeded according to the method you provided, 
so I got the results I wanted. Thank you very much!
