### ISSUE TITLE
Improve usage message: REFERENCE_SEQUENCE (Required) not in the default help message (requires --stdhelp)

### ISSUE THREAD

**Issue by arkyl** [PapenfussLab/gridss#159]
Hi,
Just a friendly notice that the REFERENCE_SEQUENCE doesn't seem to be in help message of gridss-1.8.0-gridss-jar-with-dependencies.jar. I figured out how to input the ref seq by looking through the github homepage. Thanks.
Yue

**Comment by d-cameron** [comment]
GRIDSS uses the picard tools command-line parsing library so from a user's perspective, GRIDSS behaves the same as picard tools with respect to arguments. `REFERENCE_SEQUENCE` is a standard picard tools common across all programs so you need to specify `--stdhelp` to get. Given it's not my code, I'm not sure what the best way to handle this is.

**Comment by d-cameron** [comment]
Blocked waiting on the picard tools parsing library overhaul to complete.

**Comment by arkyl** [comment]
I didn't know this. --stdhelp works perfectly fine. Thanks.

**Comment by d-cameron** [comment]
Closing as this is now hidden inside the gridss.sh driver script for most users.
