### ISSUE TITLE
All outputs are "BND"

### ISSUE THREAD

**Issue by weishwu** [PapenfussLab/gridss#165]
I ran Gridss successfully for my tumor-normal pair but all output variants contain "SVTYPE=BND". Does this mean all of them are translocations, without any other types of SV?

**Comment by d-cameron** [comment]
No. The VCF specifications allow simple events such as deletions to be reported in 3 different notations. GRIDSS reports all events in BND notation regardless of what other notations are also possible. See Section 5.4 of the VCF specifications: https://samtools.github.io/hts-specs/VCFv4.3.pdf

I've written some helper scripts (e.g. example/simple-event-annotation.R and a R (https://github.com/PapenfussLab/StructuralVariantAnnotation) package to assist with the downstream SV analysis from GRIDSS and most other popular callers.

**Comment by xxlpaladin** [comment]
Hello, I also had the same problems. But when I have run the latest R script (simple-event-annotation.R) you provided, I also could't got the annotated vcf of SVs. There were no changes in the annotated vcf file compared with my original vcf file, the SVtypes were all "BND" as before. So I want to know the reason, I think after run the R script (simple-event-annotation.R), I could get the SVs with four types (INS, INV, DUP and DEL), the same to other popular callers. And the two errors when I ran R script were shown below :
> info(vcf[gr$vcfId])$SIMPLE_TYPE <- svtype
Error in `[[<-`(`*tmp*`, name, value = c("INS", "INS", "INS", "INS", "INS",  : 
  843568 elements in value to replace 0 elements
> info(vcf[gr$vcfId])$SVLEN <- gr$svLen
Error in `[[<-`(`*tmp*`, name, value = c(0, 0, 0, 0, 3, 3, -37, -37, -11,  : 
  843568 elements in value to replace 0 elements
Thanks for your reply.
Best wishes.
Xinglong Xie

**Comment by d-cameron** [comment]
>I also could't got the annotated vcf of SVs. There were no changes in the annotated vcf file compared with my original vcf file, the SVtypes were all "BND" as before.

It doesn't change the SVTYPE: it just adds additional `SIMPLE_TYPE` and `SVLEN` fields.

**Comment by d-cameron** [comment]
> And the two errors when I ran R script were shown below :

It sounds like you ran some sort of filtering on the `vcf` object then attempted to rerun the annotation step. I've retested the script and confirms in works on the BioConductor version of the StructuralVariantAnnotation package.

**Comment by xxlpaladin** [comment]
> I also could't got the annotated vcf of SVs. There were no changes in the annotated vcf file compared with my original vcf file, the SVtypes were all "BND" as before.
> 
> It doesn't change the SVTYPE: it just adds additional SIMPLE_TYPE and SVLEN fields.
Thanks, but I have checked my annotated vcf (after run R script), neither SIMPLE_TYPE nor SVLEN was added. All the information in the annotated vcf is same to the original vcf (generated by latest gridss.sh, with command: ./gridss.sh --reference auto_all.fa --output Iran229_gridss.vcf --assembly assembly_Iran229.bam --threads 10 --jar gridss-2.4.0-gridss-jar-with-dependencies.jar --workingdir ./ --blacklist overlap_maskN.bed Iran229.BQSR.bam. The 'Iran229_gridss.vcf' is the input file of 'simple-event-annotation.R', output file is the annotated vcf), so maybe something wrong in my pipeline?

**Comment by xxlpaladin** [comment]
> And the two errors when I ran R script were shown below :
> 
> It sounds like you ran some sort of filtering on the vcf object then attempted to rerun the annotation step. I've retested the script and confirms in works on the BioConductor version of the StructuralVariantAnnotation package.

OK, thank you very much.

**Comment by xxlpaladin** [comment]
> I also could't got the annotated vcf of SVs. There were no changes in the annotated vcf file compared with my original vcf file, the SVtypes were all "BND" as before.
> 
> It doesn't change the SVTYPE: it just adds additional SIMPLE_TYPE and SVLEN fields.

Thanks, but I have checked my annotated vcf (after run R script), neither SIMPLE_TYPE nor SVLEN was added. All the information in the annotated vcf is same to the original vcf (generated by latest gridss.sh, with command: ./gridss.sh --reference auto_all.fa --output Iran229_gridss.vcf --assembly assembly_Iran229.bam --threads 10 --jar gridss-2.4.0-gridss-jar-with-dependencies.jar --workingdir ./ --blacklist overlap_maskN.bed Iran229.BQSR.bam. The 'Iran229_gridss.vcf' is the input file of 'simple-event-annotation.R', output file is the annotated vcf), so maybe something wrong in my pipeline?

**Comment by SunWinner01** [comment]
Hello, I would like to filter the gridss results using SU【Number of pieces of evidence supporting the variant across all samples】 as a threshold, but I can't find SU, which value represents SU in the actual gridss result file @d-cameron
