### ISSUE TITLE
stringr required

### ISSUE THREAD

**Issue by JocelynSP** [PapenfussLab/gridss#166]
The function breakpointRanges() required stringr for str_length
``` 
> breakpointRanges(kb1filtQ4k)
Error in str_length(gr$ALT) : could not find function "str_length"
```

**Comment by d-cameron** [comment]
https://github.com/PapenfussLab/StructuralVariantAnnotation/commit/b1ab33c3d518481ca005bbc375e0dfc7bcd67da1
