### ISSUE TITLE
GRIDSS currently supports only FR read pair orientation.

### ISSUE THREAD

**Issue by aoiein** [PapenfussLab/gridss#168]
Hi,
I'm running GRIDSS with WGS data, the aligner is BWA, and I got this ERROR message:

ERROR   2018-08-29 19:51:59     CallVariants    GRIDSS currently supports only FR read pair orientation. If usage with other read pair orientations is required, please raise an enchancement reque
st at https://github.com/PapenfussLab/gridss/issues
ERROR   2018-08-29 19:51:59     CallVariants    Fatal exception thrown by worker thread.
java.lang.RuntimeException: GRIDSS currently supports only FR read pair orientation. If usage with other read pair orientations is required, please raise an enchancement request at https://github
.com/PapenfussLab/gridss/issues

How to solve this problem？
Thank you.

**Comment by d-cameron** [comment]
Are you using a mate pair library? If so, then, as the error indicates, GRIDSS currently only supports paired-end sequencing. If you have done a normal Illumina library prep and you are getting this message, Can you please run picard tools CollectInsertSizeMetrics and attach the metrics file to this issue for me to investigate.

Cheers
