### ISSUE TITLE
Output breakpoint assembly sequences

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#17]
Output of the breakpoint consensus sequence can assist in downstream analysis.
VCF already supports this in the BKPTID info field as well as the ##assembly metadata header so this is just a matter of writing out the consensus.
Note that since the anchor lengths can be different, we need to encode the length of the flanking sequence either in a additional custom field, in the BKPTID, or both.

**Comment by genomematt** [comment]
This would be particularly useful for several non standard applications such a checking transgene integrity, transposon mapping, and TE studies.  I also think it would reduce the FN rate a little, making a call rather than the call in some complex cases.

**Comment by d-cameron** [comment]
Covered by the BEID field and assembly bam.
