### ISSUE TITLE
What level BAM should GRIDSS be run on

### ISSUE THREAD

**Issue by ahwanpandey** [PapenfussLab/gridss#171]
Hello,

Quick question. Should we run GRIDSS on a GATK realigned and recalibrated BAM or in the original BWA mapped bam? Would the results vary drastically if we ran it on both?

Thanks!

**Comment by d-cameron** [comment]
After deduplication, before GATK indel realignment. GATK indel realignment increases the FP rate of all SV callers I've tested, GRIDSS included.

**Comment by ahwanpandey** [comment]
Thanks for the guidance!
