### ISSUE TITLE
bcftools and GRIDSS vcf

### ISSUE THREAD

**Issue by ahwanpandey** [PapenfussLab/gridss#172]
Hello,

For some reason I can't seem to use bcftools on a VCF file generated by GRIDSS. I have had no issues using Lumpy and Manta with bcftools. Is there some reason bcftools is incomaptible with a GRIDSS VCF? Like a simple command to just view the PASS variants won't work. bcftools throws no errors and only returns the header.

I am using the following versions

```
gridss-1.9.0
bcftools 1.9
```

Thanks

**Comment by ahwanpandey** [comment]
Here's an example file to test:

[test.vcf.zip](https://github.com/PapenfussLab/gridss/files/2369211/test.vcf.zip)

**Comment by gkphilip** [comment]
Hello.

I am having this issue too though I am using gridss-1.8.1 and bcftool 1.8. 

The error I get is:
`[E::vcf_parse_format] Invalid character '.' in 'BANRPQ' FORMAT field at 1:261513528
Error: VCF parse error`

Thanks

**Comment by ahwanpandey** [comment]
Hi @d-cameron . Just wanted to see if you had a chance to test this out and and why it might be happening?

Thanks so much.

**Comment by d-cameron** [comment]
The BANRPQ and BANSRQ headers were incorrectly set to `Integer` when they contain `Float` values. I'll work on packaging up a new release later in the week. In the meantime, if you edit the VCF headers to the correct type, you'll be able to use your exiting VCFs. The following fixes the attached test.vcf:
```
sed -s 's/Type=Integer,Description="Quality/Type=Float,Description="Quality/' test.vcf > test.fixed.vcf
```

**Comment by lmanchon** [comment]
Hello,

me too i have a problem with gridss2 output:

bcftools norm -m-both -f $GENOME/GRCh38_p13.fa -Oz -o gridss.fixed.vcf.gz gridss.vcf.gz
Non-ACGTN alternate allele at chr1:1222499 .. REF_SEQ:'(null)' vs VCF:']chr4:54278520]GC'

has anyone ever successfully processed VCFs from GRIDSS ?

thank you --
