### ISSUE TITLE
GRIDSS ID

### ISSUE THREAD

**Issue by tgong1** [PapenfussLab/gridss#181]
Hi, Does the “o” and “h” suffix to the GRIDSS ID have any meaning? E.g. orientation?
Thank you!

**Comment by d-cameron** [comment]
It's just a unique identifier for the two breakends. They stand for  l**o**w and **h**igh breakend (I didn't use L for lower because in many fonts it looks like a 1).

**Comment by d-cameron** [comment]
The lower one being the one that has the lower genomic coordinate (using the chromosomal ordering specified in the reference genome fasta).
