### ISSUE TITLE
IdsvSamFileMetrics Single-End Warning

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#183]
According to #72 it has been fixed but I am using version 1.7.0 on the server, and I still see it. Paired-end alignment was done with Bowtie 2 and, to allow input to GATK, `picard AddOrReplaceReadGroups` was used to add read groups to the alignments. How can I avoid it?

**Comment by d-cameron** [comment]
Is this still an issues with v2.0.1? If the warning is on the asembly bam metrics then it is a false positive warning that isn't a problem (other that having issues such as these being raised by understandably concerned users)

**Comment by DarioS** [comment]
I guess so, because the code of IdsvSamFileMetrics was last changed before version 1.7.0 was released. If I do `ls -l` for the file mentioned, I see `No such file or directory`.
