### ISSUE TITLE
MAPQ should be 0 for unmapped read.

### ISSUE THREAD

**Issue by kievol** [PapenfussLab/gridss#184]
Hi folks,

I was trying to run the current version of GRIDSS (v2.0.1) but after it started running for a while I got this error message - "Read name D00468:110:HGJM2BCXX:1:1105:3521:74932, MAPQ should be 0 for unmapped read."

My sequencing data are 100-bp Illumina paired-end reads. I checked the named read in my input file and learned that its mate was mapped but not the read itself, and it has the "unmapped" bit flag but its MAPQ is not zero. I thought about removing those reads but were thinking that the reason I wanted to use GRIDSS is to check what's going on with those unmapped reads.

What would be your suggestion? Is there a "lenient" option in GRISS that I should use to allow those reads to go through? Or should I use tools such as samtools or picard to remove those reads before running GRIDSS?

Many thanks in advance!

**Comment by d-cameron** [comment]
GRIDSS is built on top of htsjdk/picard so VALIDATION_STRINGENCY=LENIENT should work.

**Comment by kievol** [comment]
Thank you for your help!
