### ISSUE TITLE
mismatch between reads and supposed insert size distribution 

### ISSUE THREAD

**Issue by JJK93** [PapenfussLab/gridss#189]
I have received an error message indicating a mismatch between my reads and the supposed insert size distribution for my library. May I know how I can solve the problem? I have attached the log and metrics files for your reference. Many thanks!
 
[test.log](https://github.com/PapenfussLab/gridss/files/2748333/test.log)
[metrics.zip](https://github.com/PapenfussLab/gridss/files/2748323/metrics.zip)

**Comment by d-cameron** [comment]
Would you be able to supply the SAM records for both reads in following read pairs:
- `ST-E00310:663:HT3KTCCXY:1:1202:20232:65617`
- `ST-E00310:663:HT3KTCCXY:1:1216:10581:56422`
- `ST-E00310:663:HT3KTCCXY:1:1219:16244:51148`

I've been attempting to reproduce the issue but I haven't been successful thus far.

**Comment by JJK93** [comment]
Hi Daniel, thanks a lot for your effort! Attached are the SAM records
[test.zip](https://github.com/PapenfussLab/gridss/files/2794574/test.zip)
