### ISSUE TITLE
invalid uncompressedLength

### ISSUE THREAD

**Issue by Nikhilasai1223** [PapenfussLab/gridss#194]
hello,
 while vaditating bam file i am getting this error .How to solve this?

java -jar picard.jar ValidateSamFile \
> I=aln-A93fixed_vs_R498.bam \
> MODE=SUMMARY
INFO	2019-01-30 15:04:59	ValidateSamFile	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    ValidateSamFile -I aln-A93fixed_vs_R498.bam -MODE SUMMARY
**********

15:04:59.485 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/ccmb/fasta_620/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jan 30 15:04:59 IST 2019] ValidateSamFile INPUT=aln-A93fixed_vs_R498.bam MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 SKIP_MATE_VALIDATION=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jan 30 15:04:59 IST 2019] Executing as ccmb@BIC-RKM-1 on Linux 4.4.0-47-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.25-SNAPSHOT
WARNING	2019-01-30 15:04:59	ValidateSamFile	NM validation cannot be performed without the reference. All other validations will still occur.
INFO	2019-01-30 15:05:36	SamFileValidator	Validated Read    10,000,000 records.  Elapsed time: 00:00:36s.  Time for last 10,000,000:   36s.  Last read position: Chr4:22,831,605
INFO	2019-01-30 15:06:12	SamFileValidator	Validated Read    20,000,000 records.  Elapsed time: 00:01:13s.  Time for last 10,000,000:   36s.  Last read position: Chr7:16,515,285
ERROR	2019-01-30 15:06:47	ValidateSamFile	/home/ccmb/fasta_620/aln-A93fixed_vs_R498.bam has invalid uncompressedLength: -1908167351
[Wed Jan 30 15:06:47 IST 2019] picard.sam.ValidateSamFile done. Elapsed time: 1.80 minutes.
Runtime.totalMemory()=124780544

**Comment by d-cameron** [comment]
Your input BAM is corrupt. you'll probably need to regenerate it from your fastq or re-download if you didn't generate it yourself.
