### ISSUE TITLE
Documentation for Input Files and Labels in Somatic Mode

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#197]
The example somatic analysis specifies both the cancer and the normal sample with the `INPUT` parameter. How does GRIDSS determine which sample is the normal sample used as the baseline? Is it dependent on the ordering of the values to the command? I think that specifying two or more `INPUT` parameters does joint germline calling but I'm confused since that also appears to be used for somatic analysis.

Also, the documentation of `INPUT_LABEL` is

> Labels to allocate inputs. The default label for each input file corresponds to the file name ...

There is a 1-to-1 relationship for germline analysis between an input file and a default label, but what is the default value if there are two `INPUT` parameters specified to `gridss.CallVariants`, such as for somatic analysis?

**Comment by d-cameron** [comment]
> The default label for each input file corresponds to the file name

If you have multiple input files, then there will be multiple VCF `FORMAT` field sample ID headers in output file and GRIDSS will give a breakdown of the contribution of each input file in the `FORMAT` fields corresponding for the corresponding sample ID (which by default is the input filename).

There is a 1-to-1 relationship between input files and labels no matter how many `INPUT` files you specify^. If you have 5 `INPUT` files, then the output VCF will have 5 `INPUT_LABEL`, which in VCF nomenclature, corresponds to 5 `FORMAT` sample IDs in the output VCF.


^ Exception: can be overridden by `INPUT_LABEL`. This is useful in scenarios where you have multiple BAMs for a single sample For example, if you have done matched normal/tumour sequencing of the same patient at different time points (e.g. cancer relapse), you'll likely want a single sample ID for the two normals.

**Comment by d-cameron** [comment]
See section 1.1 of https://samtools.github.io/hts-specs/VCFv4.3.pdf for an example of how this looks in VCF. In the example in the specs, the sample IDs are NA00001, NA00002, and NA00003. By default, GRIDSS uses the filename as the sample ID.

**Comment by DarioS** [comment]
Thanks for the clarification that each sample ends up in a different column of the VCF file. I'm still confused how GRIDSS does a somatic analysis. Other software has separate parameters for the normal and tumour files (e.g. Strelka uses `--normalBam`   and `--tumorBam`). If I provide two `INPUT` parameters, should I always input the tumour BAM second to get the desired somatic analysis from GRIDSS (tumour relative to normal, not normal relative to tumour)? If there's only one `INPUT`, then it's relative to the reference genome (germline analysis), isn't it (e.g. Strelka uses `--bam` to distinguish)?

**Comment by d-cameron** [comment]
>I'm still confused how GRIDSS does a somatic analysis.

Technically speaking, it doesn't. It performs joint multi-sample calling and reports a detailed breakdown of the per-sample support. Actually converting that into a somatic analysis happens downstream of the GRIDSS calls.

If you're wanting a high confidence somatic call set out of GRIDSS, then you'll need to perform that downstream analysis and filtering on the output. Fortunately, I've already written a quite comprehensive script to do this and it can currently be found at https://github.com/hartwigmedical/scripts/blob/master/gridss/gridss_somatic_filter.R. Give it a month or so and I'll have incorporated this (and other downstream somatic analyses) into the GRIDSS github and documentation.

**Comment by DarioS** [comment]
Ah, that makes sense. I'll await the next release of GRIDSS to do a conventional somatic analysis with its output files.
