### ISSUE TITLE
Out of date Docker containers

### ISSUE THREAD

**Issue by illusional** [PapenfussLab/gridss#214]
Hi, I was hoping to use a docker-variation of gridss, ie [`gridss/gridss`](https://hub.docker.com/r/gridss/gridss/tags) however the last Docker version was 2.0.1, and on Github we just saw the 2.2.2 release.

Not sure if docker autobuilds could be set up, or how I can help but it would be great to get some of the newer version on Docker. Cheers!

**Comment by d-cameron** [comment]
v2.2.3 has a container. I'll add docker generation to the release procedures as well.
