### ISSUE TITLE
Example usage with multiple samples and specific loci

### ISSUE THREAD

**Issue by dfermin** [PapenfussLab/gridss#219]
Hi

I have 120 BAM files I'd like to run through using GRIDSS. 
I have a BED file of 64 deletion calls I want to give GRIDSS to see if it detects them. 

I got the `gridss.sh` script to work on a few of the samples.
I could not figure out how to use/edit the `gridss_targeted.sh` script to give it a BED file and a bunch of BAM files.

I define the BED file variable in the script `BED_REGIONS_TO_TARGET` but I can't figure out how to define the folder of BAM files. 
The output should be a single VCF file right?

Can anyone provide an example of how to properly do this?

Thanks in advance,

**Comment by d-cameron** [comment]
> I can't figure out how to define the folder of BAM files. The output should be a single VCF file right?

Depends on how you run it. If you want multiple samples to be run together you just specify them on the command line
```
INPUT=sample1.bam
INPUT=sample2.bam
INPUT=sample3.bam
INPUT=sample4.bam
```

I've tested GRIDSS to around ~1500x aggregate coverage. If your files are high coverage then joint calling on120 samples will result in a very slow assembly. You might want to run them either in batches, or individually.

**Comment by dfermin** [comment]
Thanks for getting back to me.
Sorry I think I wasn't clear. I want to run gridss on a targeted set of regions that are in BED format. 
Using the `gridss.sh` script what is the correct to do this?

**Comment by d-cameron** [comment]
I hope you resolved your issue.

> I could not figure out how to use/edit the gridss_targeted.sh script to give it a BED file and a bunch of BAM files.

If you haven't, changing the following lines in gridss_targeted.sh should have worked:
```
BED_REGIONS_OF_INTEREST=example_regions_of_interest.bed
REFERENCE=hg19.fa
INPUT=chr12.1527326.DEL1024.bam
```
