### ISSUE TITLE
overlapping reads

### ISSUE THREAD

**Issue by helloeoh001** [PapenfussLab/gridss#222]
Hello, Dr. Cameron 

I have a question about the ovelapping read pairs from short fragments.
According to the supplementary material of the 'GRIDSS' paper, those reads will appear to be in an unexpected orientation if there is a microhomology between the adapter sequence of the reads and reference.
The solution is allowing '4bp dovetail' to filter the reads come from short fragments.
Could explain more 'why those reads appear to be in an unexpected orientation' and 'how 4bp dovetail helps to filter out the reads'? 
I am attaching the simple cartoon to give you how much I understand it. 
Thank you in advance!!!
![image](https://user-images.githubusercontent.com/16658129/60484204-9ac2c900-9cd3-11e9-8093-bd620ccd8994.png)

**Comment by d-cameron** [comment]
Your figure looks accurate. Picard tools (which GRIDSS uses for insert size distribution) will report that read1 with ref/adapter homology are RF, not FR. GRIDSS only supports FR reads as this time.

In general, if a RP overlaps then it is uninformative and GRIDSS filters them out. If the homology causes the orientation to change, then it looks like a tandem dup. This filter excludes this class of false positive evidence from consideration in GRIDSS.
