### ISSUE TITLE
configurations

### ISSUE THREAD

**Issue by helloeoh001** [PapenfussLab/gridss#223]
Hello Dr. Cameron

I am planning to integragrate GRIDSS to the DNA analysis pipeline that my collegues developed to analyse NGS data from cancer tissues.
About 1,000 cancer tissues were analysed with GRIDSS, and its performace was very impressive!
To prepare for any unexpected errors, I think I need to understand the algorithm in depth. (=
Here are some Congifurations that appered when running GRIDSS.

Could you explain them?
- assembly.positional.maxPathLengthMultiple = 1.1
- assembly.positional.retainWidthMultiple = 5
- assembly.positional.flushWidthMultiple = 10
- assembly.positional.maximumNodeDensity = 2
- assembly.downsample.targetEvidenceDensity = 6
- fallbackMapq = 20
- fallbackBaseq = 20

Thank you!!!

**Comment by d-cameron** [comment]
fallback mapq/baseq are the mapping/base quality scores assigned when the information is not available (ie no MQ/Q2 sam tag). Generally not relevant


All the assembly parameters can be considered internal to the assembly algorithm.
Multiples are all in multiples of the upper 99.5% fragment size distribution (ie multiple of the longest RP fragment still considered concordant).

> assembly.positional.maxPathLengthMultiple

Max length to compression a single compresed positional de Bruijn graph path node. Affects graph memory usage.

> assembly.positional.retainWidthMultiple = 5
> assembly.positional.flushWidthMultiple = 10

Offset in which RP-only assemblies are force-called in the assembly graph sliding window. Bounds graph size and theoretically could lead to suboptimal assembly contigs. The margins are so huge that this isn't a practical issue.

> assembly.positional.maximumNodeDensity = 2

Maximum nodes per base position in the compressed assembly graph. Reads overlapping a window (size = 99.5%)  with node density greater than this are excluded from assembly. Prevents stalling in low complexity sequence where the assembly graph is highly connected/degenerate

> assembly.downsample.targetEvidenceDensity = 6

Target density of SV-supporting reads. For 100bp reads, this translates to downsampling to 600x coverage of SV-supporting reads leading into the assembly. The downsampling is in a ~1k window so it targets poorly assemblied geneomic regions and not high coverage real events.

**Comment by d-cameron** [comment]
We should have a preprint for GRIDSS2+somatic CNV+downstream analyis out on bioarvix within a month. You might found our somatic analysis GRIDSS filtering scripts useful (or our entire pipeline of your cohort is WGS).
