### ISSUE TITLE
input BAMs (read groups, mark duplicates, genome with decoys etc)

### ISSUE THREAD

**Issue by darked89** [PapenfussLab/gridss#227]
Hello,

I wonder what is the best practice for calling structural variations with GRIDSS and possibly other packages with human sequences.
Meaning:

1. does version of the genome reduce i.e. the false positives?
I suspect that using say GRCh38.p13 with decoys: 
[ftp_dir_at_ncbi](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GRCh38_major_release_seqs_for_alignment_pipelines)

i.e.
```
GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.bwa_index.tar.gz	
```
should be better than i.e. cannonical hg38 genome (22 chromosomes, X, Y, MT only)?

2. While GRIDSS can work with BAMs without any read groups or marked duplicates, does adding this information to the input BAMs will make a notable difference in the results?

Best,

Darek Kedra

**Comment by d-cameron** [comment]
1. As GRIDSS relies on the quality of the read alignments, performance with decoy sequences should be marginally better. Just make sure to blacklist the decoy sequences or assembly in those regions will be very slow.


2. If there is a single read group, GRIDSS will use the `@RG` sample identifier as the output. If multiple files have the same read group identifier, their support will be merged in the VCF.

If you have a BAM file with multiple libraries in it (separated by read group), these must be split into separate BAM files. If you do not, GRIDSS will use the overall insert size distribution when determining discordant read pairs.

**Comment by d-cameron** [comment]
Some downstream analysis (e.g. viral integration detection) requires that you do not include a related decoy. E.g. don't use the hg19 hs37d5 decoy sequence if you're interested in EBV.
