### ISSUE TITLE
Break-end concept clarification

### ISSUE THREAD

**Issue by JuanmaMedina** [PapenfussLab/gridss#229]
Good morning Daniel,

First of all, thanks for the development of the software. 

I have been testing it during this week, and I have what must be a really basic issue that is limiting my understanding of some of its aspects and results. However, I have been completely unable to find a proper definition of it.

What do you exactly mean with **break-end** when talking about sequences, overlaps, etc? It is an extensively used term along the description of the program, as well as your explanations in Biostars/Github, etc.

Thanks in advance!

**Comment by d-cameron** [comment]
>It is an extensively used term along the description of the program, as well as your explanations in Biostars/Github, etc.

We use the terminology adopted by the VCF file format specifications (see section 5.3 of https://samtools.github.io/hts-specs/VCFv4.2.pdf). Unfortunately, it's not much used outside the VCF specifications themselves.

Mathematically, one would define a breakend as a (chr, position, orientation) tuple. Biologically, it correspond to the broken end of a the DNA. DNA repair connects two breakends together. We use breakend terminology to distinguish between breakpoint and single break-end SV calls.
