### ISSUE TITLE
Question about 'simple-event-annotation.R'.

### ISSUE THREAD

**Issue by xxlpaladin** [PapenfussLab/gridss#231]
Hello, I also had the same problem as the question #165. But when I have run the latest R script (simple-event-annotation.R) you provided, I also could't got the annotated vcf of SVs. There were no changes in the annotated vcf file compared with my original vcf file, the SVtypes were all "BND" as before. So I want to know the reason, I think after run the R script (simple-event-annotation.R), I could get the SVs with four types (INS, INV, DUP and DEL), the same to other popular callers. And the two errors when I ran R script were shown below :
  > info(vcf[gr$vcfId])$SIMPLE_TYPE <- svtype
  Error in `[[<-`(`*tmp*`, name, value = c("INS", "INS", "INS", "INS", "INS",  : 
    843568 elements in value to replace 0 elements
  > info(vcf[gr$vcfId])$SVLEN <- gr$svLen
  Error in `[[<-`(`*tmp*`, name, value = c(0, 0, 0, 0, 3, 3, -37, -37, -11,  : 
    843568 elements in value to replace 0 elements
  Thanks for your reply.
  Best wishes.
Xinglong Xie

**Comment by xxlpaladin** [comment]
I can get a *.simple.bed (shown below) file which contains the summary of information of all the SVs. 
1       9609    9647    DEL     1174.1  .
1       10916   10928   DEL     1216.45 .
1       10958   10959   INS     813.28  .
1       12490   13990   DEL     767.03  .
1       14932   14945   DEL     1545.84 .
1       20098   20099   INS     1331.63 .
1       20545   20561   DEL     1305.8  .
1       23384   23421   DEL     1443.5  .

But this information couldn't be found in the annotated vcf file of SVs which was generated by the  R cript (simple-event-annotation.R). I have already got the SVs data from manta, speedseq and novobreak. So the result of gridss is very important to me, I want use the gridss as a ciiterion because of it's advanced algorithm. 
I really need your suggestion about my question. Thank you very much.

**Comment by d-cameron** [comment]
> But this information couldn't be found in the annotated vcf file of SVs which was generated by the R cript (simple-event-annotation.R

In what way is this information not in the VCF? GRIDSS reports all variants in `BND` notation, so each of these events will have two `BND` VCF records associated it with it (one for each breakend in the breakpoint).

**Comment by xxlpaladin** [comment]
> But this information couldn't be found in the annotated vcf file of SVs which was generated by the R cript (simple-event-annotation.R
> 
> In what way is this information not in the VCF? GRIDSS reports all variants in BND notation, so each of these events will have two BND VCF records associated it with it (one for each breakend in the breakpoint).

Thanks, I know what you mean. But in the question #165, you said the SIMPLE_TYPE field would be added in the annotated vcf, and I think the svtype information (in the *.simple.bed file) should be added behind the SIMPLE_TYPE (e.g. SIMPLE_TYPE=INS, SIMPLE_TYPE=DUP). However, there is no  SIMPLE_TYPE field in my annotated vcf as I asked in #165.

**Comment by d-cameron** [comment]
Ok, retested on a clean environment and can now reproduce the problem. The `vcfId` column is called `sourceId` in the BioConductor version of StructuralVariantAnnotation. The GRIDSS script has noww been updated to reflect this.

**Comment by xxlpaladin** [comment]
> Ok, retested on a clean environment and can now reproduce the problem. The vcfId column is called sourceId in the BioConductor version of StructuralVariantAnnotation. The GRIDSS script has now been updated to reflect this.

Thanks very much, the problem has been sloved.
