### ISSUE TITLE
Error in PositionalAssembler - Null Pointer

### ISSUE THREAD

**Issue by paru16** [PapenfussLab/gridss#235]
Hello,

I've been trying to run CallVariants with Gridss V1.7.1, but I'm coming across Null Pointer Exceptions during the PositionalAssembler stage. I've processed two alignments with identical parameters without any issues - it's only failing for this particular file.

I've included the full error message/log in the attached text file. Any advice would be much appreciated.

Thank you!
[xha_gridss_log.txt](https://github.com/PapenfussLab/gridss/files/3500402/xha_gridss_log.txt)

**Comment by d-cameron** [comment]
>Any advice would be much appreciated.

There have been 14 GRIDSS releases since v1.7.1. I strongly recommend rerunning using the latest version.
