### ISSUE TITLE
ComputeSamTags step

### ISSUE THREAD

**Issue by SJ-Kang** [PapenfussLab/gridss#241]
Hello, thanks for your previous answers.
And i have some small question about ComputeSamTags  step.
I found explanation about other steps such as CollectGridssMetrics, ExtractSVReads.. except gridss.ExtractSVReads.
So i wonder what meaning of ComputeSamTags step is, and why carry out this step.

Thanks

**Comment by d-cameron** [comment]
Let me know if you need more details on top of what I've added to the readme.
