### ISSUE TITLE
More Than One Normal Sample for create_gridss_pon Error

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#248]
I have reduced it to a minimal example. Let the R script be:

```r
#!/usr/bin/env Rscript

library(argparser, quietly=TRUE)

argp = arg_parser("Test inputs.")
argp = add_argument(argp, "--test", type="integer", default=1, help="Test")
argv = parse_args(argp)
print(argv$test)
```

Now, run the script with one number 

```
$ Rscript testRscript.R --test 1
[1] 1
```

and a vector of numbers

```
$ Rscript testRscript.R --test 1:10
Warning message:
In asMethod(object) : NAs introduced by coercion
[1] NA
```

If a vector of indicies is provided, the argument parsing fails. How can the panel of normals be created if the input file has multiple samples which are normals (i.e. a separate set of normal samples were sequenced distinct from the matched normals of the cancer patients)?

**Comment by d-cameron** [comment]
This one is my fault: I ended up replacing the pon filtering script with a Java implementation because R kept running out of memory when loading thousands of VCFs.

I've added instructions to the GRIDSS readme:

https://github.com/PapenfussLab/gridss/blob/master/Readme.md#how-do-i-create-the-panel-of-normals-required-by-gridss_somatic_filterr

Thanks for the feedback

**Comment by d-cameron** [comment]
If you have a single VCF with multiple normals then you can use `StructuralVariantAnnotation` to do the filtering then just export to bedpe (breakpoints) and bed (single breakends). 

The score column should be set to the sample count, and files must be named `gridss_pon_breakpoint.bedpe` and `gridss_pon_single_breakend.bed` for `gridss_somatic_filter.R` to pick them up.

**Comment by DarioS** [comment]
> The score column should be set to the sample count

How's my approach based on non-zero VF?

```r
variantScores <- apply(geno(vcf)[["VF"]], 1, function(variantFragments) sum(variantFragments > 0))
```

Reading the manual, it seems like the files which need to be exported can be done in seven lines for _breakpoints_.

```r
vcf <- VariantAnnotation::readVcf(vcf.file)
gr <- breakpointRanges(vcf)
gr <- subset(gr, QUAL >= 75)
alignedScores <- variantScores[match(names(gr), names(variantScores))]
breakpointTable <- breakpointgr2bedpe(gr)
breakpointTable[, "score"] <- alignedScores
write.table(breakpointTable, file = "gridss_pon_single_breakend.bed", sep = '\t', row.names = FALSE, header = FALSE)
```

Is there a similar function to `breakpointgr2bedpe` for _breakends_? `breakendgr2bed` perhaps? Or, is the code below fine:

```r
bEnds <- breakendRanges(vcf)
bEnds <- subset(bEnds, QUAL >= 75)
alignedScores <- variantScores[match(names(bEnds), names(variantScores))]
breakEndBED <- data.frame(chrom = seqnames(bEnds), chromStart = start(bEnds) - 1, chromEnd = end(bEnds), name = names(bEnds), score = alignedScores, strand = strand(bEnds))
write.table(breakEndBED, file = "gridss_pon_breakpoint.bedpe", sep = '\t', row.names = FALSE, header = FALSE)
```
