### ISSUE TITLE
GRIDSS Apparently Not Reacting to Sambamba Failure

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#252]
In a recent run, it seems likely that the server's shared hard drive space filled up.

```
Filesystem Free
/scratch   0.4%
```

The analysis had an error after about three hours.

```
[Fri Sep 27 19:23:01 AEST 2019] Executing as dstr7320@hpc162.hpc.sydney.edu.au on Linux 2.6.32-696.16.1.el6.x86_64 amd64
INFO	2019-09-27 22:02:31	SinglePassSamProgram	Processed 1,110,000,000 records.  Elapsed time: 00:35:58s.  Time for last 10,000,000:   18s.  Last read position: 8:33,490,641
INFO	2019-09-27 22:02:50	SinglePassSamProgram	Processed 1,120,000,000 records.  Elapsed time: 00:36:18s.  Time for last 10,000,000:   19s.  Last read position: 8:46,841,624
sambamba-sort: Cannot open or create file '/scratch//HeadNeck/DNAsequencing/TCGA-CV-7180-01A-11D-2266-10_Illumina.bam.gridss.working/sambamba-pid227704-rzpn/stdin.4'
```

However, the analysis did not end until the requested time was used up and the CPU was probably idling for most of the time, because of the small overall usage:

```
Job run as chunks (hpc162:ncpus=8:mem=83886080kb)
Walltime requested:   20:00:00 :      Walltime used:   20:01:16
                               :   Walltime percent:     100.1%

-- node hpc162 summary
    Cpus requested:          8 :          Cpus used:       0.48
          Cpu Time:   09:30:47 :        Cpu percent:       5.9%
```

Could GRIDSS catch errors from its software dependencies and terminate as soon as possible?

**Comment by d-cameron** [comment]
> Could GRIDSS catch errors from its software dependencies and terminate as soon as possible?

```
set -o errexit -o pipefail -o noclobber -o nounset
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
trap 'echo "\"${last_command}\" command completed with exit code $?."' EXIT
```

That's exactly what this code at the start of the script is supposed to do. Are you using the v2.6.2 gridss.sh driver script?

> CPU was probably idling for most of the time

Do you have any visibility about what (if anything) was running?

**Comment by DarioS** [comment]
I am using version 2.6.1. It is not possible to see what else is running on the node when my analysis runs. Now that you mention the trap commands which I overlooked, I notice that there is some similarity to #251 The cluster I used has CentOS 6.9 operating system.

> Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)

Perhaps it's merely a coincidence, though.

**Comment by d-cameron** [comment]
Please re-open if this is still an issue with the latest driver script.
