### ISSUE TITLE
GRIDSS exiting without providing output

### ISSUE THREAD

**Issue by MaestSi** [PapenfussLab/gridss#253]
Hi,
I am running GRIDSS v2.6.2 with command:
```
GRIDSS=/mnt/cifs01/simone/software/gridss/scripts/gridss.sh
WORKING_DIR=/mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST
REFERENCE=$WORKING_DIR/Homo_sapiens_assembly38.fasta
BAM=$WORKING_DIR/NA24385_30X.bam

$GRIDSS \
--reference $REFERENCE \
--output $WORKING_DIR/GRIDSS_output.vcf.gz \
--assembly $WORKING_DIR/NA24385_assembly.bam \
--threads 24 \
--jar /mnt/cifs01/simone/software/gridss/gridss-2.6.2-gridss-jar-with-dependencies.jar \
--workingdir $WORKING_DIR \
$BAM
```
Stdout is the following:

> Using working directory "/mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST"
> Using reference genome "/mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/Homo_sapiens_assembly38.fasta"
> Using assembly bam /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/NA24386_assembly.bam
> Using output VCF /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/GRIDSS_output.vcf.gz
> WARNING: GRIDSS scales sub-linearly at high thread count. Up to 8 threads is the recommended level of parallelism.
> Using 24 worker threads.
> Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
> Using JVM maximum heap size of 25g for assembly and variant calling.
> Using input file /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/NA24385_30X.bam
> Found /mnt/cifs01/simone/software/miniconda3/envs/GRIDSS_env/bin/bwa
> Found /mnt/cifs01/simone/software/miniconda3/envs/GRIDSS_env/bin/Rscript
> Found /usr/bin/time
> Found /mnt/cifs01/simone/software/miniconda3/envs/GRIDSS_env/bin/sambamba
> Found /mnt/cifs01/simone/software/miniconda3/envs/GRIDSS_env/bin/java
> sambamba 0.7.0
> R scripting front-end version 3.6.1 (2019-07-05)
> bwa Version: 0.7.17-r1188
> GNU time 1.7
> GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
> java version "1.8.0_45"
> Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
> Max file handles: 16384
> dom 29 set 2019, 19.49.37, CEST Running GRIDSS. The full log is in /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/gridss.full.20190929_194937.hiseq2.11457.log
> dom 29 set 2019, 19.49.37, CEST Start pre-processing    /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/NA24385_30X.bam
> dom 29 set 2019, 19.49.37, CEST CollectInsertSizeMetrics        /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/NA24385_30X.bam      first 10000000 records
> dom 29 set 2019, 19.50.30, CEST CollectGridssMetricsAndExtractSVReads|sambamba  /mnt/cifs01/simone/NA24385/30X/GRIDSS_TEST/NA24385_30X.bam
> "/usr/bin/time -a -o $timinglogfile sambamba sort -n --tmpdir $dir -m 8GB -o $tmp_prefix.namedsorted.bam -t $threads /dev/stdin" command completed with exit code 1.

The last lines in the log file are the followings:

> Exception in thread "main" java.lang.NumberFormatException: For input string: "567,176827"
>         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
>         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
>         at java.lang.Double.parseDouble(Double.java:538)
>         at htsjdk.samtools.util.FormatUtil.parseDouble(FormatUtil.java:141)
>         at htsjdk.samtools.util.FormatUtil.parseObject(FormatUtil.java:191)
>         at htsjdk.samtools.metrics.MetricsFile.read(MetricsFile.java:388)
>         at gridss.analysis.InsertSizeDistribution.create(InsertSizeDistribution.java:33)
>         at gridss.cmdline.ProcessStructuralVariantReadsCommandLineProgram.getReadPairConcordanceCalculator(ProcessStructuralVariantReadsCommandLineProgram.java:68)
>         at gridss.analysis.CollectStructuralVariantReadMetrics.setup(CollectStructuralVariantReadMetrics.java:51)
>         at gridss.ExtractSVReads.setup(ExtractSVReads.java:50)
>         at gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram.setup(ByReadNameSinglePassSamProgram.java:156)
>         at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:138)
>         at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:563)
>         at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:66)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
>         at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:190)
>         at gridss.CollectGridssMetricsAndExtractSVReads.main(CollectGridssMetricsAndExtractSVReads.java:61)
> sambamba-sort: not enough data in stream
> 

Do you have any advice about how to solve this error?
Thanks in advance,
Simone

**Comment by d-cameron** [comment]
The issue is that numbers are getting written with a comma separator, yet expecting a peroid in the next step.

> Do you have any advice about how to solve this error?

Run 

```
export LC_ALL=C
```

before running GRIDSS to force a consistent locale.

**Comment by MaestSi** [comment]
Thank you!

**Comment by YuanwenGuo** [comment]
Hello,
I got similar error log file during SV calling process, even after adding export LC_ALL=C. Just wonder if this issue has been fixed and how to make it work?

Please see my error log records as following:
gridss.SoftClipsToSplitReads done. Elapsed time: 470.26 minutes.
Runtime.totalMemory()=4151836672
Exception in thread "main" java.lang.NumberFormatException: For input string: "asm4-34583"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at au.edu.wehi.idsv.SplitReadHelper.getRealignmentFirstAlignedBaseReadOffset(SplitReadHelper.java:231)
        at au.edu.wehi.idsv.SplitReadHelper.unclip(SplitReadHelper.java:175)
        at au.edu.wehi.idsv.SplitReadHelper.replaceAlignment(SplitReadHelper.java:275)
        at au.edu.wehi.idsv.SplitReadHelper.replaceAlignment(SplitReadHelper.java:260)
        at au.edu.wehi.idsv.SplitReadRealigner.prepareRecordsForWriting(SplitReadRealigner.java:273)
        at au.edu.wehi.idsv.SplitReadRealigner.writeCompletedAlignment(SplitReadRealigner.java:237)
        at au.edu.wehi.idsv.SplitReadRealigner.mergeSupplementaryAlignment(SplitReadRealigner.java:384)
        at au.edu.wehi.idsv.SplitReadRealigner.mergeSupplementaryAlignment(SplitReadRealigner.java:340)
        at au.edu.wehi.idsv.SplitReadRealigner.createSupplementaryAlignments(SplitReadRealigner.java:310)
        at gridss.SoftClipsToSplitReads.doWork(SoftClipsToSplitReads.java:95)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at gridss.SoftClipsToSplitReads.main(SoftClipsToSplitReads.java:118)
INFO    2019-10-10 17:34:34     IdentifyVariants        

Much appreciate if anyone can help with this issue.

Best,
Yuanwen
