### ISSUE TITLE
Instructions Advise Run AnnotateUntemplatedSequence Twice

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#258]
In the section titled How Do I Do RepeatMasker Annotation?, the instruction is that `AnnotateUntemplatedSequence` be manually used, but `gridss.sh` already does this. Similarly, the GRIDSS-PURPLE-LINX wrapper also inadvertently does this step twice.

**Comment by d-cameron** [comment]
It does the step twice intentionally. The first time against the ref, the
second against the viral database.

**Comment by DarioS** [comment]
Sure, but I'm saying that in `gridss.sh` on line 577, annotation is automatically done against the genome refence sequence. So, the user should not need repeat that part manually and only do the second annotation using the RepeatMasker database to avoid annotating with the genome refence sequence twice, right?
