### ISSUE TITLE
Negative values in INSs and INVs

### ISSUE THREAD

**Issue by CapitanFlint** [PapenfussLab/gridss#264]
Hi,

Collecting the metrics i realized that there are some negative values in "SVLEN=" in insertions and inversions classes. What does that mean? 

Thank you in advance,

Bruno.

**Comment by d-cameron** [comment]
Which downstream processing script are you referring to? GRIDSS itself does not write a `SVLEN` field as it reports all events in breakend notation.


Note that the VCF specifications define `SVLEN` as the `Difference in length between REF and ALT alleles` so negative values are possible (although one wouldn't expect it for `INS` events).

**Comment by CapitanFlint** [comment]
I used simple-event-annotation.R. 
And yes, exactly, i didn't understod why an insertion could have a negative value, because that makes them a deletion. By the way, of all variant finded, it is only one that have a negative value but change all statistics values. So im not sure if that is an artifact or a bug, or is indeed a somewhat expected behaviour. 

Thank you so much

**Comment by d-cameron** [comment]
Can you post the VCF record in question so I can reproduce your issue locally?
