### ISSUE TITLE
CollectGridssMetrics error

### ISSUE THREAD

**Issue by jiadong324** [PapenfussLab/gridss#265]
Dear authors,

I am working with the NA19240, the BAM file is from 1000 Genome Project. When I run gridss, it raises error at step CollectGridssMetrics. 

Here is the error message:

> Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 6684, Read name ERR894723.121198723, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned.

Thanks for the help!

**Comment by d-cameron** [comment]
Your input bam bin fields are incorrect. This can be fixed by converting to SAM then back to BAM.

Note that any htsjdk based tool (e.g picard tools, GATK) will also raise this error on your input file.
