### ISSUE TITLE
Consistency Of Post-processing Output Formats

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#269]
It would be nice when writing BASH scripts if the user didn't need to remember which script automatically outputs bgz files and which outputs plain text files. `gridss_annotate_insertions_repeatmaster.R` automatically compresses the output and adds the bgz suffix. The user might then want to do viral annotation by using gridss.AnnotateUntemplatedSequence which outputs a plain VCF file. Then, `gridss_somatic_filter.R` could be used, which outputs a bgz file. Could all of the steps output either plain VCF or bgz consistently?

**Comment by d-cameron** [comment]
> Could all of the steps output either plain VCF or bgz consistently?

The R based steps all output as .bgz. The java based steps output based on the suffix so support `.vcf``, `.vcf.gz` and `.bgz` formats.

It's probably worth raising an issue with BioConductor VariantAnnotation and asking them to change the output suffix from `.bgz` to `.gz` as I have no control over that. Even if you specify the output as `out.vcf.gz`, it writes to `out.vcf.bgz`.

**Comment by DarioS** [comment]
Oh, the Java process can do either automatically, based on the suffix. I'll just change my output suffix.
