### ISSUE TITLE
Somatic Structural Variant Already in Reference Genome

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#270]
I am exploring the results after somatic filtering and RepeatMasker annotation. I notice one variant that's defined as

```
chr14   87955674        gridss228bb_117o        C       [chr22:28669361[CAAATGAGTATAAATC        412.27  PASS
chr22   28669361        gridss228bb_117h        G       [chr14:87955674[ATTTATACTCATTTGG        412.27  PASS
```

It doesn't have any annotation such as `INSRMRT` but looking at the reference genome, it's adjacent to a known retrotransposon.

![somaticLINE1](https://user-images.githubusercontent.com/631218/67546600-8a35d300-f748-11e9-8553-8dac63d46b90.png)

Should it be filtered out at some stage? It seems that the read mates are matching to various different chromosomes, so I wonder why it's matched to chr14.

I also notice a lot of variants that have N as the first base of the alternative allele.

```
chr1    231391039       gridss23bf_271o T       ]chr1:231391183]N       497.44  PASS
chr1    231391183       gridss23bf_271h C       N[chr1:231391039[       497.44  PASS
```

Is it unexpected?

**Comment by DarioS** [comment]
Ah, grouping by chromosome mate provides a clear visualisation. I see it's next to the LINE1 element, not in it, so it makes sense it's not annotated as LINE1. I'm still unsure about Ns in the alternate allele, though.

![image](https://user-images.githubusercontent.com/631218/67549413-ee0fca00-f74f-11e9-9295-a5071552e19e.png)

**Comment by d-cameron** [comment]
>I'm still unsure about Ns in the alternate allele, though.

What processing steps did you perform? I suspect they've been introduced by a step that adjusted the call position without access to the reference genome sequence (e.g `gridss_adjust_call_positions.R`)

**Comment by DarioS** [comment]
Actually, I traced it back to the output VCF of `gridss.sh` - before any annotation or somatic filtering is done. The VCF file has 608232 entries. Only 135 of them have N.

```r
> length(grep("N[", fixed = TRUE, variants[["ALT"]]))
[1] 66
> length(grep("]N", fixed = TRUE, variants[["ALT"]]))
[1] 69
```

They look like

```r
                             seqnames    ranges strand | paramRangeID            REF                       ALT      QUAL                   FILTER
                                <Rle> <IRanges>  <Rle> |     <factor> <DNAStringSet>           <CharacterList> <numeric>              <character>
       gridss93bf_1h             chr5  49650756      * |         <NA>              N          N[chr5:49599355[    455.64 LOW_QUAL;SINGLE_ASSEMBLY
       gridss93bf_8h             chr5  49662045      * |         <NA>              N          N[chr5:49660659[    740.59              NO_ASSEMBLY
   gridss101bf_1123h             chr5 139452750      * |         <NA>              N         N[chr5:139452156[    163.72     LOW_QUAL;NO_ASSEMBLY
  gridss101fb_10318o             chr5 139452751      * |         <NA>              N         N[chr5:139453710[    179.37 LOW_QUAL;SINGLE_ASSEMBLY
   gridss103fb_6313o             chr5 155760387      * |         <NA>              N         N[chr5:155761290[    922.09          SINGLE_ASSEMBLY
```

Looking at chr5:49650756 using IGV, for example, it is in a segment of repeated N of the hg38 reference genome. Do you find any of them in your analyses using `grep`?

The variant described in the original question doesn't have N allele nor PASS filter value in the unannotated VCF.

```r
                  seqnames    ranges strand | paramRangeID            REF               ALT      QUAL                   FILTER
                     <Rle> <IRanges>  <Rle> |     <factor> <DNAStringSet>   <CharacterList> <numeric>              <character>
  gridss23bf_271o     chr1 231391038      * |         <NA>              T ]chr1:231391182]T    497.44 LOW_QUAL;SINGLE_ASSEMBLY
```

**Comment by d-cameron** [comment]
The Ns component of this issue has been resolve and GRIDSS now uses centre alignment.

`gridss_adjust_call_positions.R` has been removed from GRIDSS releases
