### ISSUE TITLE
Add documentation and fix gridss_targeted.sh example

### ISSUE THREAD

**Issue by vladsaveliev** [PapenfussLab/gridss#273]
Hi Daniel,

Wondering if you are planning to support the `gridss_lite.sh` script. Just can't find it in the repo and it wasn't in the releases since 2.4.0. The reason I'm asking is that I've got a sample (very mutated, FANCA-deficient and with a HPV16 integration) that it takes over 48 hours for GRIDSS to run the assemble-breakends step so the cluster job just expires. Wondering if GRIDSS-lite can be helpful.

**Comment by d-cameron** [comment]
Most of the performance optimisations in `gridss_lite.sh` got folded into gridss.sh so it wasn't needed as a separate script anymore.

If you want to do a gridss lite run now, you need to run `gridss.ExtractFullReads` with your `REGION_BED` specifying your region of interest, plus about 10kbp of padding (`REGION_PADDING_SIZE`) so the metrics aren't too biased, then just run `gridss.sh` on the subset BAM.

>The reason I'm asking is that I've got a sample (very mutated, FANCA-deficient and with a HPV16 integration) that it takes over 48 hours for GRIDSS to run the assemble-breakends step so the cluster job just expires. 

If you're hitting cluster timeouts then the latest release (v2.6.3) is exactly what you're looking for. I've added additional parameters to allow the assembly work to spread across multiple jobs/nodes. You should be able to adapt the torque example script qutie easily. 

See https://github.com/PapenfussLab/gridss/blob/master/example/torque_example.sh

**Comment by d-cameron** [comment]
Note that if you just rerun gridss after your 48 hour timeout, it'll pick up where it left off (max loss of work = chunkSize * thread count).

**Comment by ohofmann** [comment]
Daniel, thanks for the quick follow-up. Do I get this right, performance-wise there are few differences at this point between gridss_lite and gridss? If so we should probably give the distributed approach a try (though I worry how this works in an AWS environment). More than 2 days for the SV step might mean we have to limit this to the research samples.

**Comment by d-cameron** [comment]
Gridss is around 18h all up using a single 8core google cloud node on
hartwig samples. Over 48h for just assembly seems very high. Are you hg19
or hg38?

**Comment by ohofmann** [comment]
I'll defer to Vlad, but I suspect GRCh37 on 28 cores.

**Comment by d-cameron** [comment]
With that many cores, it could be something as simple as you being out of
memory. If you slowly creep up to your max heap, java has the annoying
habit of spending more and more time doing garbage collection instead of
actual work. Unless you're doing a big memory allocation, Java will spend
far far too long effectively stalled with almost no progress before finally
throwing a GC time exceeded exception. In my experience, the jvm is way too
conservative when throwing that exception.

**Comment by vladsaveliev** [comment]
That's right, it was GRCh37 and a 28 core node.

I actually started with 100G available, and it oom'ed indeed. Then I restarted with 256G, and it worked well until the node has died with the walltime expired. But I'm gonna try parallelized across nodes, with a lower amount of cores on each one, will see how it goes. Thanks Daniel!

**Comment by d-cameron** [comment]
Use a java heap memory size less than 32Gb for each node. Once java hits 32Gb of heap, it switch to 64-bit object pointers which massively inflates memory usage requirements. You're more likely to OOM with a 40GB heap than a 31GB one.

**Comment by vladsaveliev** [comment]
Huh, that explains why it consumed so much. Thanks Daniel!

**Comment by ohofmann** [comment]
Following up on this - we still run into issues with some samples. Got the
okay to share one of the problematic cases with you / PMCC if you want to
give the sample a try on your compute environment?

Best, Oliver
