### ISSUE TITLE
Unable to find gridss jar. Specify using the environment variant GRIDSS_JAR

### ISSUE THREAD

**Issue by datakid** [PapenfussLab/gridss#275]
If changing the name of - for eg - `gridss-2.6.3-gridss-jar-with-dependencies.jar` is required, it should be documented in the installation instructions.

If setting the GRIDSS_JAR environment var is required it should be documented in the installation instructions.

**Comment by d-cameron** [comment]
The instructions specify that you should use the `--jar` command line argument.

Using `GRIDSS_JAR` is an alternate to using --jar. I've updated the error message to reflect this.

**Comment by datakid** [comment]
Thanks!
