### ISSUE TITLE
Driver Script Parameter Validation

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#276]
`gridss.sh` could validate all of its parameters at the beginning before doing any lengthy processing. For example, if `--assembly` is provided with a path that has a folder which doesn't exist, the breakend assembly will run for a long time

> gridss.AssembleBreakends done. Elapsed time: 226.29 minutes.

and then an error will stop the analysis

> Cannot write file: /scratch/assembled/assembly.bam. Neither file nor parent directory exist.

**Comment by d-cameron** [comment]
In the case of being unable to create a directory, an error message was printed at start-up, it just didn't immediately halt execution.
