### ISSUE TITLE
More Information About Viral Annotation

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#277]
In the section titled How Do I Do Viral Annotation? could there be more details about how to find the variants which are annotated with virus parts in the VCF? The repeat annotation function adds fields such as `INSRMRC` and `INSRMRT` but what field would store information about viruses?

**Comment by d-cameron** [comment]
Updated https://github.com/PapenfussLab/gridss#how-do-i-do-viral-annotation
