### ISSUE TITLE
Reported breakend positions can be inconsistent

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#278]
https://github.com/hartwigmedical/hmftools/issues/62 indicates that different positions can be reported even in the absence of assembly inconsistency (#167).

When reporting the nominal position, ties for the highest scoring evidence should be resolved deterministically, and not just choose the first as the first record can be different at each breakend.

**Comment by hkeward** [comment]
Hey @d-cameron, I am trying to use [gridss-purple-linx](https://github.com/hartwigmedical/gridss-purple-linx) and came across this issue a few months ago during the PURPLE step, specifically via the issue you linked. I tried again today using gridss version 2.8.1 and encountered the same issue.

Do you know of any way I can get around this other than by manually editing the VCF file produced by gridss? Any more info I can provide to help debug?

**Comment by d-cameron** [comment]
Fixed in v2.8.2. Combination of input data inconsistencies (now adjusted for), RP support existing for supp alignments (RP support is now for primary alignments only), and a off-by-one error in the config pro-rataing (resulting in slightly different assembly score on either side of a breakpoint).

**Comment by d-cameron** [comment]
I've added a lot of extra debugging functionality to resolve this. If you still get any errors in 2.8.2, rerun gridss.sh with the new `--sanityCheck` argument and cut/paste the offending records into be issue text.

**Comment by hkeward** [comment]
Thanks a lot, I will test it out!
