### ISSUE TITLE
Somatic filtering script documentation

### ISSUE THREAD

**Issue by ivanbelzen** [PapenfussLab/gridss#280]
Would it be possible to provide documentation on GitHub for what filtering is conducted with the R script?  The recent pre-print from biorxiv contains a list of criteria but the script seems to have been updated since. A similar documentation page on GitHub or as more extensive comments in the code itself would be highly appreciated. 

It also seems that a PON and a reference is not required to run the filtering script, is that correct?

**Comment by DarioS** [comment]
I thought a PON is necessary but now I notice it's not. It's indeed confusing.

**Comment by d-cameron** [comment]
Is https://github.com/PapenfussLab/gridss/wiki/Somatic-Filtering sufficient, or do you need more details? If so, which section(s) would you like expanded?

**Comment by DarioS** [comment]
I think it's good but it doesn't explicitly answer Ivan's original question.

> It also seems that a PON and a reference is not required to run the filtering script, is that correct?

I was also thinking that `gridss.soft_filters` and `
gridss.very_hard_filters` could list all valid values.

**Comment by d-cameron** [comment]
Thanks for the feedback @DarioS. It has been incorporated into the page.

>The recent pre-print from biorxiv contains a list of criteria but the script seems to have been updated since

The VCF filter and annotation names have been changed to be more consistent and meaningful, but the actual filtering is still matches the preprint.
