### ISSUE TITLE
Running GRIDSS on multiple samples without a matched normal

### ISSUE THREAD

**Issue by bzk18** [PapenfussLab/gridss#281]
Hi,

I am trying to find structural variants in a non-model organism genome. I have multiple sample NGS libraries. I can't figure out how to run GRIDSS for all samples simultaneously as input. Since this is not cancer related, I don't have a matched normal sample. How do I tell GRIDSS this? Will it treat the first sample as normal by default? 

Edit: The matched normal sample is relevant only for gridss_somatic_filter.R right? So GRIDSS treats all samples identically ? I don't need to worry about this issue, since I won't be calling gridss_somatic_filter.R right?

Thank you so much!
Balaji

**Comment by d-cameron** [comment]
Correct, just specify all your BAMs on the command line and GRIDSS will do joint calling and provide a per-sample breakdown of the support from each sample.

If some of your samples have multiple BAMs for the one sample, you can override the default per-bam output using the `--labels` command line parameter.
