### ISSUE TITLE
Inconsistent breakpoint filtering in raw GRIDSS output.

### ISSUE THREAD

**Issue by CapitanFlint** [PapenfussLab/gridss#290]
Hi,

In the .vcf file obtained with 'CallVariants', and after filtering the data with the annotation script (.R), there is an ID line in every variation which generally look like this:

gridss61fb_1221h

My question is what is the meaning of the last letter, in this case "h", because in most of cases there is an "analogous" with an "o" instead of "h". 

For example:

Seg600	17972	gridss61fb_1221o	T	T[Seg600:17993[	788.14	PASS	AS=1;ASC=53M1X;ASQ=258.52;ASRP=0;ASSR=17;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm61-4043,asm61-8735;BEIDH=3,3;BEIDL=3,3;BQ=0;BSC=0;BSCQ=0;BUM=0;BUMQ=0;BVF=0;CAS=0;CASQ=0;CQ=788.14;EVENT=gridss61fb_1221;IC=8;IHOMPOS=0,0;IQ=258.52;PARID=gridss61fb_1221h;RAS=1;RASQ=271.11;REF=12;REFPAIR=0;RP=0;RPQ=0;SB=0.72;SC=56M1X;SR=0;SRQ=0;SVLEN=-20;SVTYPE=BND;VF=8;SIMPLE_TYPE=DEL	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:258.52:0:17:0:0:0:0:0:0:0:0:0:0:0:0:0:0:8:258.52:788.14:271.11:12:0:0:0:0:0:8

Seg600	17993	gridss61fb_1221h	T	]Seg600:17972]T	788.14	PASS	AS=1;ASC=1X69M;ASQ=271.11;ASRP=0;ASSR=17;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm61-4043,asm61-8735;BEIDH=3,3;BEIDL=3,3;BQ=12.59;BSC=1;BSCQ=12.59;BUM=0;BUMQ=0;BVF=0;CAS=0;CASQ=0;CQ=788.14;EVENT=gridss61fb_1221;IC=8;IHOMPOS=0,0;IQ=258.52;PARID=gridss61fb_1221o;RAS=1;RASQ=258.52;REF=12;REFPAIR=0;RP=0;RPQ=0;SB=0.692308;SC=1X69M;SR=0;SRQ=0;SVLEN=-20;SVTYPE=BND;VF=8;SIMPLE_TYPE=DEL	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:271.11:0:17:0:0:0:0:0:0:0:12.59:1:12.59:0:0:0:0:8:258.52:788.14:258.52:12:0:0:0:0:0:8

Are gridss61fb_1221o and  gridss61fb_1221h part of the same break point? Also, there are some variant that finished with a "b" instead of "o" and "h".  I want to do statistical analysis on the samples, but the problem is that there are some "h" alone without any "pair" ("o"), so i don't know what to do with them.

**Comment by d-cameron** [comment]
>My question is what is the meaning of the last letter, in this case "h", because in most of cases there is an "analogous" with an "o" instead of "h".

h high breakpoint position
o low breakpoint position
b single breakend position 

> the problem is that there are some "h" alone without any "pair" ("o"), so i don't know what to do with them

You filter them out. Breakpoints require both records to be present in the VCF. In some cases, data inconsistencies will result in the two ends of breakpoint having different QUAL scores (e.g. a split read with a missing record on one side), which results in only one side getting filtered when both should.

**Comment by d-cameron** [comment]
- Add VcfTranform to filter output to include only pairs. Requires additional pass over VCF.

**Comment by d-cameron** [comment]
Should be fixed in 2.8.2
