### ISSUE TITLE
CollectAlignmentSummaryMetrics Missing Genome Reference File

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#301]
I did a test run of GRIDSS 2.8 and there is only one warning in the log file:

```
WARNING	2020-02-20 09:32:23	CollectAlignmentSummaryMetrics	Without a REFERENCE_SEQUENCE, metrics pertaining to mismatch rates will not be collected!
```

but other components of the analysis seem to work fine with the reference sequence I provided.

```
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -L 0,0 -t 8 /project/HeadNeck/indexes/bwa/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna ...
[main] Real time: 649.423 sec; CPU: 4111.060 sec
```

What should end-users do about such warnings?

**Comment by d-cameron** [comment]
> What should end-users do about such warnings?

GRIDSS doesn't actually use the output of CollectAlignmentSummaryMetrics so the warning is a false positive
