### ISSUE TITLE
Command line argument using conda

### ISSUE THREAD

**Issue by whelena** [PapenfussLab/gridss#304]
I have been running gridss using this command line code:
gridss.sh --reference <ref> --output <output> --assembly <assembly> --threads 4 --jar /path/to /gridss-2.7.3-gridss-jar-with-dependencies.jar --workingdir gridss/ <input>

I am wondering on how to replicate this in a conda environment.

**Comment by d-cameron** [comment]
The bioconda wrapper was a community contribution so there's some features missing in there. There's currently no conda equivalent of the driver script.

I'm made a PR with a new conda recipe. Currently still a work in progress.

https://github.com/bioconda/bioconda-recipes/pull/20651

**Comment by d-cameron** [comment]
Now just waitiing on a review by the bioconda team.

**Comment by d-cameron** [comment]
bioconda recipes have been corrected in bioconda gridss version 2.8.0-1

Command-line is the same as GRIDSS documentation except that the command line program is called `gridss`, not `gridss.sh`.

**Comment by whelena** [comment]
Thank you!
