### ISSUE TITLE
RepeatMasker Annotation CIGAR Error

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#306]
I have done a test run using GRIDSS 2.8.0 and the VCF was successfully created. Now, I'm using the R annotation script and get the error (AnnotateUntemplatedSequence and human_virus.fa work):

```r
Error in .Call2("cigar_width", cigar, flag, space, PACKAGE = "GenomicAlignments") : 
  in 'cigar[7939]': unexpected CIGAR end after char 2
Calls: with ... mutate_impl -> <Anonymous> -> .cigar_width -> .Call2
```

My command for testing was:

```
Rscript gridss_annotate_insertions_repeatmaster.R --input OSCC_1structural.vcf.gz --output OSCC_1structuralAnnotatedRetrotransposons.vcf --repeatmasker RepeatMaskerDNAhg38.fa.out.gz --scriptdir .
```

Looking at the bioinformatics core facility's report, base quality score recalibration was done.

> Following GATK Best Practices, we then perform base quality score recalibration with GATK4.

This seems relevant to the issue I have, although I have never done BQSR myself nor know its purpose.

**Comment by d-cameron** [comment]
> This seems relevant to the issue I have, although I have never done BQSR myself nor know its purpose.

That won't be it. The error will be coming from:
```
insseqgr = with(data.frame(
    sourceId=rep(names(rowRanges(vcf)), lengths(info(vcf)$BEALN)),
    BEALN=unlist(info(vcf)$BEALN)) %>%
  separate(BEALN, sep="[:|]", into=c("chr", "start", "orientation", "cigar", "maqp")) %>%
  mutate(
    start=as.integer(start),
    end=start+GenomicAlignments::cigarWidthAlongReferenceSpace(cigar))
```

In particular, a parsing error in `GenomicAlignments::cigarWidthAlongReferenceSpace(cigar)`.
Do any records have a BEALN field that isn't a valid CIGAR? If you can identify the offending record(s), I can fix the error. Alternatively, if you're able to, you could email me (cameron.d wehi.edu.au) OSCC_1structural.vcf.gz and I could do the debugging myself.

**Comment by DarioS** [comment]
Aha! It's because the core facility supplements the standard set of chromosomes with HLA alleles using bwakit. The previous line splits on colon, but the reference sequence names contain colons from IMGT/HLA (e.g. contig=<ID=HLA-A*01:01:01:01,length=3503>). So the result is:

```r
> BEALNtable[7939, ]
          sourceId         chr start orientation cigar  maqp
7939 gridss1b_175b HLA-DRB1*15    03          01    01 10202
```

By the way, if I will use LINX later, should I still use this script to annotate retrotransposons?

**Comment by d-cameron** [comment]
Yes. Retrotransposon annotation is done based on the repeatmasker annotation of `BEALN` locations. I'll be pushing up a new GRIDSS release including a fix for this later in the week.

**Comment by DarioS** [comment]
Will the new change work with `contig=<ID=chr1_KI270762v1_alt,length=354444>` also present?

**Comment by d-cameron** [comment]
Should be fine. It's  only `:` and `|` involved in `BEALN` parsing.
