### ISSUE TITLE
READ_PAIR_CONCORDANT_PERCENT via gridss.sh or config file

### ISSUE THREAD

**Issue by cbrueffer** [PapenfussLab/gridss#307]
Hi,

following the latest changes to the bioconda package I switched from calling `gridss.CallVariants` directly to using the `gridss.sh` driver script (thanks for the recipe update!). My gridss version is therefore 2.8.0 (bioconda package version 2.8.0-1).

I used the `READ_PAIR_CONCORDANT_PERCENT=null` option for `gridss.CallVariants`, but do not see a way to set it via the driver script. I also don't see a way to specify it via the config file. Is that correct or am I missing something?

Thanks!

**Comment by d-cameron** [comment]
It's not surfaced through the driver script as I wasn't aware that anyone was actually using it. Whic aligner/tool are you using to set the proper pair flag, and what's your reasoning behind not using the GRIDSS default distribution? Did you get better results from overriding?

**Comment by cbrueffer** [comment]
I use bwa 0.7.17. I've only started with `READ_PAIR_CONCORDANT_PERCENT=null` recently when trying to figure out why a few SVs were not bring called when using gridss default settings. Setting the above recovered some of them, so I was considering using it by default.

**Comment by cbrueffer** [comment]
Thanks for adding the driver script flag! I tested with the new 2.8.1 release (via bioconda) and I get the following error when running with `--useproperpair`. Without the flag things work.

```
$ gridss --threads 1 --jvmheap 8G --reference reference.fna --output gridss/sample.vcf.gz  --assembly gridss/sample_assembly.bam --labels sample --workingdir tmp --useproperpair bam_markdup/sample_markdup.bam 
Using working directory "tmp"
Using reference genome "reference.fna"
Using assembly bam gridss/sample_assembly.bam
Using output VCF gridss/sample.vcf.gz
Using 1 worker threads.
Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Using JVM maximum heap size of 8G for assembly and variant calling.
Using input file bam_markdup/sample_markdup.bam
label is sample
Found .snakemake/conda/0f813ccd/bin/bwa
Found .snakemake/conda/0f813ccd/bin/Rscript
Found .snakemake/conda/0f813ccd/bin/samtools
Found .snakemake/conda/0f813ccd/bin/java
which: no time in (/usr/bin)
Not found /usr/bin/time
1.10+htslib-1.10.2
R scripting front-end version 3.6.2 (2019-12-12)
bwa Version: 0.7.17-r1188
which: no time in (/usr/bin)
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)
Max file handles: 4096
Thu Mar 12 13:29:08 CET 2020    Running GRIDSS steps preprocess, assemble, call,. The full log is in tmp/gridss.full.20200312_132908.mito.91646.log
Error: Preprocessing does not support multiple nodes for a given input file.
        To perform parallel per-input preprocessing, run independent preprocessing per input file.
"exit 16" command completed with exit code 16.
```

The log file mentioned in the messages does not get written.

**Comment by d-cameron** [comment]
Ergh, I change a whole lot of command-line arguments so this will work properly, regression test it all but don't actually test --useproperpair. Fixed in dev (can download https://github.com/PapenfussLab/gridss/blob/dev/scripts/gridss.sh in lieu of waiting for the next release).
