### ISSUE TITLE
Unrecognized option command line error (connected to issue #304)

### ISSUE THREAD

**Issue by whelena** [PapenfussLab/gridss#309]
I am trying to run gridss using the updated bioconda wrapper (issue #304) using the following command
`export GRIDSS_JAR=$(ls $(dirname $(readlink -e which gridss))/*.jar) `
`gridss --reference <ref.fa> --output gridss/A48301/SV.vcf --assembly gridss/A48301/assembly.bam --threads 4 --jar $GRIDSS_JAR --workingdir gridss/A48301 <input.bam>`

This gives me an error:
`Unrecognized option: --reference`
`Error: Could not create the Java Virtual Machine.`
`Error: A fatal exception has occurred. Program will exit.`

**Comment by d-cameron** [comment]
If that's literally the exact command you're running then the issue is with your `<` and `>` characters on your command line as they'll be being treated as shell redirects.

**Comment by d-cameron** [comment]
Also, `export GRIDSS_JAR` should not be required as the `gridss` wrapper script should find the jar location and add it to the command line.

**Comment by whelena** [comment]
I am not actually using the < and > characters and I tried running it without `export GRIDSS_JAR` and still receive the same error. I also tried using `-r` instead and it still doesn’t recognize it. 

I’m using gridss v2.8.0 from bioconda, would this be the right version?

**Comment by cbrueffer** [comment]
@whelena could you state the exact version of the gridss package you're using? `2.8.0-1` has the new wrapper, `2.8.0-0` doesn't. I've had cases where the conda solver didn't install the latest version of the package unless explicitly specified..

**Comment by whelena** [comment]
That's it! I have gridss 2.8.0=0, i will update gridss and rerun the command. Thank you!

**Comment by d-cameron** [comment]
Should be fine in 2.8.1-0
