### ISSUE TITLE
CollectInsertSizeMetrics file not generated and pipeline stopped

### ISSUE THREAD

**Issue by philtat** [PapenfussLab/gridss#310]
Im using 2.8.0 gridss. In my log I get the following errors:

WARNING	2020-03-11 17:51:53	SinglePassSamProgram	File reports sort order 'unsorted', assuming it's coordinate sorted anyway.
WARNING	2020-03-11 17:51:53	CollectInsertSizeMetrics	All data categories were discarded because they contained < 0.05 of the total aligned paired data.
WARNING	2020-03-11 17:51:53	CollectInsertSizeMetrics	Total mapped pairs in all categories: 0.0
[Wed Mar 11 17:51:53 MDT 2020] gridss.analysis.CollectGridssMetrics done. Elapsed time: 0.00 minutes.

and these

WARNING	2020-03-11 17:51:54	SinglePassSamProgram	File reports sort order 'unsorted', assuming it's coordinate sorted anyway.
WARNING	2020-03-11 17:51:54	ProcessStructuralVariantReadsCommandLineProgram	Missing ./saccer3noCup1.1BWA.fa.amb.gridss.working/tmp.saccer3noCup1.1BWA.fa.amb.insert_size_metrics
INFO	2020-03-11 17:51:54	SAMFileWriterFactory	Unknown file extension, assuming BAM format when writing file: file:///dev/stdout
WARNING	2020-03-11 17:51:54	ProcessStructuralVariantReadsCommandLineProgram	Missing ./saccer3noCup1.1BWA.fa.amb.gridss.working/tmp.saccer3noCup1.1BWA.fa.amb.insert_size_metrics
WARNING	2020-03-11 17:51:54	CollectInsertSizeMetrics	All data categories were discarded because they contained < 0.05 of the total aligned paired data.
WARNING	2020-03-11 17:51:54	CollectInsertSizeMetrics	Total mapped pairs in all categories: 0.0

My terminal output looks like this:

/home/blacklab/gridss-2.8.0/gridss.sh --jar /home/blacklab/gridss-2.8.0/gridss-2.8.0-gridss-jar-with-dependencies.jar -r /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa* -t 3 -l sample.noCup1.1 -o out.vcf -a out.bam --picardoptions VALIDATION_STRINGENCY=LENIENT /media/blacklab/raid10Storage/yeast/cu1/sort.sample.NCup1.1.bam
Using working directory "."
Using reference genome "/media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa"
Using assembly bam out.bam
Using output VCF out.vcf
Using 3 worker threads.
Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Using JVM maximum heap size of 25g for assembly and variant calling.
Using input file /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.amb
Using input file /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.ann
Using input file /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.bwt
Using input file /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.fai
Using input file /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.pac
Using input file /media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.sa
Using input file /media/blacklab/raid10Storage/yeast/cu1/sort.sample.NCup1.1.bam
label is sample.noCup1.1
Found /usr/bin/bwa
Found /usr/bin/Rscript
Found /usr/bin/samtools
Found /usr/bin/java
Found /usr/bin/time
1.7+htslib-1.7-2
R scripting front-end version 3.6.3 (2020-02-29)
bwa Version: 0.7.17-r1188
GNU time 1.7
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
Max file handles: 4096
Wed Mar 11 17:32:22 MDT 2020	Running GRIDSS steps preprocess, assemble, call,. The full log is in ./gridss.full.20200311_173222.blacklab-PowerEdge-R510.4951.log
Wed Mar 11 17:32:22 MDT 2020	Start pre-processing	/media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.amb
Wed Mar 11 17:32:22 MDT 2020	CollectInsertSizeMetrics	/media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.amb	first 10000000 records
Wed Mar 11 17:32:23 MDT 2020	CollectGridssMetricsAndExtractSVReads|samtools	/media/blacklab/raid10Storage/ChromosomesSacSer3NoCup1.1/saccer3noCup1.1BWA.fa.amb
rm: cannot remove './saccer3noCup1.1BWA.fa.amb.gridss.working/tmp.saccer3noCup1.1BWA.fa.amb.insert_size_metrics': No such file or directory
rm: cannot remove './saccer3noCup1.1BWA.fa.amb.gridss.working/tmp.saccer3noCup1.1BWA.fa.amb.insert_size_histogram.pdf': No such file or directory
"rm $tmp_prefix.insert_size_metrics $tmp_prefix.insert_size_histogram.pdf" command completed with exit code 1.

I have sorted my bam file input using samtools and Ive tried picard, same error both times. This is paired end sequencing in yeast.

Any ideas how to get around it?

**Comment by d-cameron** [comment]
>Any ideas how to get around it?

Delete the following line from gridss.sh:
```
rm $tmp_prefix.insert_size_metrics $tmp_prefix.insert_size_histogram.pdf
```

A fix will be included in the next GRIDSS release.

**Comment by d-cameron** [comment]
If your data is actually paired-end sequencing data, then you need to check your pipeline because it's being treated as single-end sequencing data.
