### ISSUE TITLE
VCF REF is not correct when homology is present.

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#321]
REF is not rewritten when centre-aligning

**Comment by RobinVanSchendel** [comment]
why are you aligning events with homology in the middle of the homology in the first place? Most SV callers place it either at the start or at the end. In the middle of the homology is obviously just as arbitrary as any other position, but I am curious about your rationale behind the choice.

**Comment by d-cameron** [comment]
There are two reasons:

The 'normalised' form for SNV/indels is to left-align the homology. For ++ or -- breakpoints, left-aligning the lower breakend will force right-alignment of the upper breakend. Similarly for right-alignment of the lower. This means that it is impossible to univerally left-align, or right-align breakpoints without resulting in an incorrect nominal call position. Centre-alignment is the option that does not cause this problem ( technically speaking, you still have an off-by-one problem for odd-length homology but that's less problematic).

Secondly, centre-aligning exact breakpoints with microhomolgy is consistent with centre-aligning imprecise calls. Centre-aligning imprecise calls makes sense as it is (usually) the centre position that is the most likely to be correct. Left or right alignment of an imprecise call will result in the nominal call being at the edge of the confidence interval bounds.
