### ISSUE TITLE
Conflicting Default Value in AnnotateUntemplatedSequence Documentation

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#324]
The `THREADS` option contains "Defaults to number of cores available." but also "Default value: 48." AnnotateUntemplatedSequence is a pretty short running command. Is such a large number efficient?

**Comment by d-cameron** [comment]
The underlying code is
```
public int WORKER_THREADS = Runtime.getRuntime().availableProcessors();
```
You're running it on a 48 core machine.
