### ISSUE TITLE
ProcessExecutor	Rscript execution error: No such file or directory

### ISSUE THREAD

**Issue by Chipcui** [PapenfussLab/gridss#325]
Hi，

When I run GRIDSS with 44 samples, it occurs "ProcessExecutor	Rscript execution error: No such file or directory". So, what's the problem?
My PBS server script and log files like this:
[gridss.pbs.txt](https://github.com/PapenfussLab/gridss/files/4467761/gridss.pbs.txt)
[gridss.full.20200413_095853.comput16.4417.log](https://github.com/PapenfussLab/gridss/files/4467764/gridss.full.20200413_095853.comput16.4417.log)
[gridss.timing.20200413_095853.comput16.4417.log](https://github.com/PapenfussLab/gridss/files/4467765/gridss.timing.20200413_095853.comput16.4417.log)

Thanks in advance!

**Comment by d-cameron** [comment]
It looks like you don't have `Rscript` on `PATH` on your PBS nodes.

This error is happening when picard CollectInsertSizeMetrics attempts to generate it's histogram. A good way to debug this particular error to check that the Picard tools CollectMultipleMetrics command works (on a tiny sample bam). The GRIDSS jar includes a copy of picard tools and it's this picard tools step is failing.

**Comment by Chipcui** [comment]
Yeah, according to you, I have added the Rscript to PATH. When I run GRIDSS to test one bam file, it also has error like this:
```
INFO	2020-04-13 16:33:01	RExecutor	Executing R script via command: Rscript /home/cuixb/data/analysis_data/SV/gridss-result/./TH001.bam.gridss.working/script2241519958251443277.R /home/cuixb/data/analysis_data/SV/gridss-result/./TH001.bam.gridss.working/tmp.TH001.bam.insert_size_metrics /home/cuixb/data/analysis_data/SV/gridss-result/./TH001.bam.gridss.working/tmp.TH001.bam.insert_size_histogram.pdf TH001.bam
ERROR	2020-04-13 16:33:01	ProcessExecutor	Rscript execution error: No such file or directory
[Mon Apr 13 16:33:01 CST 2020] gridss.analysis.CollectGridssMetrics done. Elapsed time: 0.21 minutes.
Runtime.totalMemory()=1883766784
Exception in thread "main" picard.PicardException: R script picard/analysis/insertSizeHistogram.R failed with return code 255
	at picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:182)
	at picard.analysis.SinglePassSamProgram$SinglePassSamProgramRunner.run(SinglePassSamProgram.java:280)
	at java.lang.Thread.run(Thread.java:745)
```
