### ISSUE TITLE
Fatal error during breakpoint identification java.io.IOException: Invalid BAM file header

### ISSUE THREAD

**Issue by nayfous** [PapenfussLab/gridss#327]
Hello, When I try to run GRIDSS with a single sample, I get a Invalid BAM file header error at the VariantCaller step. Could you give me some advice how to solve this error.
The generated log files:
[gridss.full.20200413_213451.DESKTOP-V4F4OQ0.5950.log](https://github.com/PapenfussLab/gridss/files/4471715/gridss.full.20200413_213451.DESKTOP-V4F4OQ0.5950.log)
[gridss.timing.20200413_213451.DESKTOP-V4F4OQ0.5950.log](https://github.com/PapenfussLab/gridss/files/4471716/gridss.timing.20200413_213451.DESKTOP-V4F4OQ0.5950.log)
Thank you in advance.

**Comment by nayfous** [comment]
Solved after rerunning a few times

**Comment by d-cameron** [comment]
You might have run out of open file handles. See https://github.com/PapenfussLab/gridss#too-many-open-files
