### ISSUE TITLE
Add arbitrary jvm_args through driver `script.sh`

### ISSUE THREAD

**Issue by illusional** [PapenfussLab/gridss#328]
Hi,

I'm using the driver script through the docker (`gridss/gridss:2.6.3`), but one of our users have run into a "too many open files" error. I want to add `-Dgridss.defensiveGC=true` to the command line, but it doesn't seem possible.

I think it might be good to add some mechanism for users adding their own jvm args through the driver script, but my main objective is to try and get this pipeline running.

**Comment by d-cameron** [comment]
> my main objective is to try and get this pipeline running

The best option is to increase your OS ulimits.

The next best options is to add a configuration file using a larger chunk size (so fewer files to deal with)
e.g create `gridss.properties` with the following content:
```
chunkSize = 50000000
```

and run with `grids.sh --configuration gridss.properties`. As the default chunk size is 10Mb, increasing this to 50Mb will reduce the # open file handles 5-fold.


PS any suggestions for a good format for a user guide? Just a pdf docs? Stuff like this is document in the source code javadocs but that's not at all intuitive for a user looking to work around an OS/htsjdk limitation.

**Comment by d-cameron** [comment]
Defensive GC is really a last-ditch workaround since it forces a full GC every time a chunk is finished. If you're running on exome data (which is where you're likely to run of of handles since you're processing chunks really quickly since they're mostly empty), you'd be triggering hundreds of unnecessary GCs which really does slow things down.

**Comment by d-cameron** [comment]
Advice changed to recommend defensive GC as a option of last resort. Config file is a better solution.

Closing as wontfix since I won't be updating the driver script for this issue (but will laster if another one issue comes up where changing the jvm args is indeed the best approach).

**Comment by d-cameron** [comment]
Also, `JAVA_TOOL_OPTIONS` exists if you really need to inject additionals args.

See https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html

**Comment by illusional** [comment]
Thanks @d-cameron, appreciate the advice!

Re docs: I use readthedocs to host a sphinx docs project (but I use Python). I'm sure there's probably something similar for Java (to get the source javadocs). Can always just use sphinx / mkdocs to host a bunch of MD / RST files on readthedocs. I like it better than GitHub Wiki, and can be set to just update the docs on each push of the repo.
