### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by woodoo46** [PapenfussLab/gridss#331]
Hi, there,

What would a record like this mean?

chr1    1929438 gridss0b_7222b  G       .GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

Instead a breakend represention, there is a sequence of bases plus a dot, the dot could be before or after the sequences?

Thanks.

George

**Comment by d-cameron** [comment]
See Section 5.4.9 of the VCF specifications.
https://samtools.github.io/hts-specs/VCFv4.3.pdf

It's a single breakend variant for which the flanking sequence is known, but the other side is unknown/multimapping.
