### ISSUE TITLE
Error messages v2.8.3

### ISSUE THREAD

**Issue by tgong1** [PapenfussLab/gridss#332]
Hi Daniel,

I'm running my samples on gridss v2.8.3 and got hundreds of error messages, while finished successfully. How will that affect the final SV results? What can I do to avoid those error messages?

Many thanks,
Tingting

Error 1: NonReferenceContigAssembler
For example:
ERROR	2020-04-24 18:15:22	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr1
ERROR	2020-04-24 18:15:36	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr1

Error 2: SupportNodeIterator
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493627 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493628 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493629 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493630 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493631 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493632 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493633 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493634 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493635 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493636 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493637 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>
ERROR	2020-04-25 00:03:21	SupportNodeIterator	Error: kmer in evidence yjIBZ0CXE6K_Z9IZw1zLY-mYsbBZqPVf of read A00488:59:HMKCWDSXX:3:2336:32732:32127 (chr7:494671 129S21M) out of bounds. Kmer support starts at 493638 which is more than 1028 before the breakpoint start position at <(6):494669(494667-494671) (6):494668(494666-494670)>

**Comment by d-cameron** [comment]
Should be fixed in 2.9.1
