### ISSUE TITLE
More Flexible Specification of Tumour and Normal Samples

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#333]
It seems that the code in a number of places makes assumptions that there will be one healthy sample per patient. I think a different way of specifying the normal sample(s) would allow the software to generalise to more experiments (it currently seems specific to Hartwig Medical Database).

Regarding GeneratePonBedpe, "Only the first sample per VCF is processed which is useful for generating a panel of normals (PON) from a cohort of cancer samples with matched normals".

Similarly, the somatic filter has `--normalordinal` which can be a single number specifying the order of the sample in the VCF file. Also, code such as `tumourordinal = seq(ncol(geno(raw_vcf)$VF))[-argv$normalordinal]` assumes that there is exactly one healthy sample per patient and might lead to the incorrect samples being considered as cancer for users who don't read the documentation properly.

Could such functions accept a pattern to match to the sample IDs instead of (or in addition to) a position? It would make them easier to apply to different experimental designs, such as those which have patients who have blood and adjacent normal sequenced.

**Comment by d-cameron** [comment]
GeneratePonBedpe does indeed assume a single normal as the first ordinal.

> code such as `tumourordinal =`

>somatic filter has --normalordinal which can be a single number ...assumes that there is exactly one healthy sample per patient

The assumption made was that multiple been labelled as such when running GRIDSS. The multiple normal samples would then be aggregrated into a single VCF output column and the somatic filtering script would work fine.

For example, something along the lines of  `gridss.sh .... -l normal -l normal -l tumour1 -l tumour2 normal_blood.bam normal_tissue.bam tumour_primary.bam tumour_met.bam` would produce a VCF with 3 (not 4) samples and the differences between the two normal samples (e.g. library fragment size distributions) would be handled correctly, and aggregated in the final output.

**Comment by DarioS** [comment]
Thanks for highlighting the use of identical `--labels` to do collapsing. I over-looked that. I was trying to use a more popular experimental design in my question, but mine is stranger. What would be the best to do in my real use case of: 

1. 20 pairs of tumour and normal pairs, one for each cancer patient.
2. 10 healthy donors of same tissue type who came to hospital for a non-cancer surgery but kindly volunteered to have a tiny part of their tongue cut out in surgery because they're generous people.

I plan to run GRIDSS on each pair of cancer patient samples separately and also run it on all 10 volunteer samples in one execution. I suppose that I must not collapse the 10 volunteers into a single sample in their VCF file. But, how do I use all 30 healthy samples as a PON, given that GeneratePonBedpe only allows one position per VCF file and the file containing volunteers will have 10 columns of relevant information? Does that firstly need the enhancement of GeneratePonBedpe?

**Comment by d-cameron** [comment]
`GeneratePonBedpe` update. For your use case, you'll need to run it twice: once for the 20 paired normals, and again for the 10 healthy samples.

The command line gets way too messy if we allow multiple files all with different normal ordinals. I went with the cleaner and more flexible approach allowing incremental PON update through INPUT_BEDPE and INPUT_BED parameters.

**Comment by DarioS** [comment]
To confirm, would I run GRIDSS on the healthy volunteer samples one at a time to create one VCF file per person and then run GeneratePonBedpe in a loop to add each volunteer's variants to the PON created earlier by running GeneratePonBedpe once to extract the normal sample (first position) of each cancer patient?

**Comment by d-cameron** [comment]
You'd use your existing VCFs and call GeneratePonBedpe with your 20 controls with `NORMAL_ORDINAL=1 NORMAL_ORDINAL=2 NORMAL_ORDINAL=3, ...`, then again with all your 10 paired T/N with `INPUT_BEDPE` and `INPUT_BED` set to the files generated by the first call. Only two invocations required since you only have two different sample configurations in your VCFs

**Comment by DarioS** [comment]
The command documentation has

> 0-based ordinals of the normal samples in the VCF.

Did you mean `NORMAL_ORDINAL=0 NORMAL_ORDINAL=1 NORMAL_ORDINAL=2 ...` or is the documentation outdated?

**Comment by d-cameron** [comment]
Revisiting old issues. Ordinals do indeed start at 0.

> To confirm, would I run GRIDSS on the healthy volunteer samples one at a time to create one VCF file per person and then run GeneratePonBedpe

If you have sample per 1 VCF on your healthy samples, and normal then tumour on your paired samples, then you could throw all the VCFs into one `GeneratePonBedpe` call with `NORMAL_ORDINAL=0` since the normal is the first sample in each VCF.
