### ISSUE TITLE
somatic filter is_unique error

### ISSUE THREAD

**Issue by jaesvi** [PapenfussLab/gridss#337]
Hi Daniel,
I am getting an error using the gridss_somatic_filter.R script:

`Calculating assembly links cov50.raw.vcf
Calculating bebe insertion links cov50.raw.vcf
Calculating bebp insertion links cov50.raw.vcf
Calculating simple inversions cov50.raw.vcf
Calculating dsb links cov50.raw.vcf
Error: object 'is_unique' not found
Execution halted`
The libgridss.R is read correctly and I have not done any changes to it. This object seems to be in the linked_by_adjacency() function, that is called linked_by_dsb() , but I can't figure out why is this object not found. 
This is the command I'm running:
`Rscript gridss_somatic_filter.R --normalordinal 2 -p /hpc/cog_bioinf/cuppen/project_data/Roel_pipeline_validation/gridss -i cov50.raw.vcf -o cov50.somatic.vcf -f cov50.somatic.full.vcf -s libgridss/`
Have you seen this before? any hints of where to look at? 
I can provide vcf by e-mail if needed. 
Thanks

**Comment by d-cameron** [comment]
Maintainence of `gridss_somatic_filter.R`/`libgridss.R` has moved from github.com/hartwigmedical/scripts/gridss/ to github.com/PapenfussLab/gridss/scripts/ and it is now included in GRIDSS releases.

Note that the HMF script relies on the prebioconductor release of the `StructuralVariantAnnotation` package (and required devtools::install_github() to install), whereas the GRIDSS release has been updated to use the BioConductor version.
