### ISSUE TITLE
Input Parameter Requirements for Various Steps

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#338]
Is there some place to read about which input parameters are required by which steps? For example, are `--output <output.vcf.gz>` and `--assembly <assembly.bam>` needed if `--steps PreProcess`? I'm doing a trial run to figure out suitable values for `#PBS -l mem` and `-l walltime` in each of the 3 stages for typical Illumina WGS (45 coverage of healthy and 90 coverage of cancer, so quite similar to HMF). I will do the testing using the upcoming Release version with even more enhancements than 2.9.0. Also, is sambamba still required anywhere? I only see it in a couple of example scripts and Dockerfile.

**Comment by d-cameron** [comment]
No parameter changes required if you're not attempting to do jobs in parallel. If you're doing parallel jobs then preprocess jobs have 1 input file each, and assembly jobs need `--jobindex` and `--jobnodes` (following by an assembly gather step without those parameters).

With the latest round of optimisation in 2.9.0 (namely, in-process BWA alignment) GRIDSS now has pretty good CPU utilisation for standard 8core/32gb compute node.

Sambamba is no longer used.
