### ISSUE TITLE
Running GRIDSS with bowtie2

### ISSUE THREAD

**Issue by GeoMicroSoares** [PapenfussLab/gridss#339]
Hi there,
Could you please provide specific instructions for running `GRIDSS` with `bowtie2` instead of `bwa-mem`? It is specified in the README and in the software's journal article that this is possible, however no specific instructions are provided.
Thanks!

**Comment by d-cameron** [comment]
There are two scenarios, and it's unclear as to which you are referring to:

1) Using bowtie2-aligned input files. This is covered by https://github.com/PapenfussLab/gridss#what-aligner-should-i-use and requires no additional configuration. GRIDSS should 'just work' with bowtie2-aligned input.

2) Using bowtie2 for the GRIDSS-internal soft-clip to split read realignment steps. This is more complicated and is covered in the command line usage messages for the `gridss.SoftClipsToSplitReads`:

```
> java -cp target/gridss-2.9.1-gridss-jar-with-dependencies.jar gridss.SoftClipsToSplitReads
...
ALIGNER_COMMAND_LINE=String   Command line arguments to run external aligner. Aligner output should be written to stdout
                              and the records MUST match the input fastq order.Java argument formatting is used with
                              %1$s being the fastq file to align, %2$s the reference genome, and %3$d the number of
                              threads to use.  Default value: [bwa, mem, -L, 0,0, -t, %3$d, %2$s, %1$s]. This option can
                              be set to 'null' to clear the default value. This option may be specified 0 or more times.
                              This option can be set to 'null' to clear the default list.
...
```

So, to use bowtie2 (or another aligner), you would edit your `gridss.sh` and add the following command-line arguments to the `gridss.SoftClipsToSplitReads` step:
```
ALIGNER_COMMAND_LINE="null"
ALIGNER_COMMAND_LINE="bowtie2"
ALIGNER_COMMAND_LINE="--threads"
ALIGNER_COMMAND_LINE="%3$d"
ALIGNER_COMMAND_LINE="--local"
ALIGNER_COMMAND_LINE="--mm"
ALIGNER_COMMAND_LINE="--reorder"
ALIGNER_COMMAND_LINE="-x"
ALIGNER_COMMAND_LINE="%2$s"
ALIGNER_COMMAND_LINE="-U"
ALIGNER_COMMAND_LINE="%1$s"
```

**Comment by d-cameron** [comment]
Part of the reason that GRIDSS has a preprocess step is to adjust the input BAMs into a format GRIDSS can use. For bowtie2-aligned input files, this includes converting the soft clipped reads into split reads (since bowtie2 does not do split-read alignment). This is all done automatically by GRIDSS. The only real limitation on your input file is that there should be a single (possibly split) alignment per read. This means that options such as `bwa mem -a` or `bowtie2 -k`/`bowtie2 -a`

**Comment by GeoMicroSoares** [comment]
Thanks for the quick reply @d-cameron !
Ran GRIDSS on my bowtie2-aligned reads though and it complained about my bowtie2-aligned reference genome:
```
Unable to find bwa index ref_v1.1.2.fasta.bwt for reference genome.
Please create using bwa index ref_v1.1.2.fasta
```

What do you suggest?

**Comment by d-cameron** [comment]
A bwa index consists of 5 files, the largest of which has a .bwt suffix.

> What do you suggest? 

Run `bwa index ref_v1.1.2.fasta` so the bwa index exists.

The user experience for this issue was improved in GRIDSS v2.9.0 - GRIDSS will make the call to `bwa index` itself so you shouldn't see this error message anymore.
