### ISSUE TITLE
Running this suite on ICGC vcf data.

### ISSUE THREAD

**Issue by mortunco** [PapenfussLab/gridss#35]
Hi, 

I would like to call a specific gene fusion called TMPRSS2:ERG for my ~250 vcf files. The vcfs were obtained from brass. So I actually have a vcf file for structural variants. But I couldnt figure out how to visualise them. I know this is not your directly expertise but, can I make those fancy circos plots with the VCF files (or bedpe) formatted outputs.

Best,

Tunc.

**Comment by d-cameron** [comment]
GRIDSS requires BAM files for input so to run GRIDSS you'll need to actual sequence files, not the VCFs. A quick and dirty way of calling a specific fusion is to filter reads to only those near the regions of interest (eg gene + 1kbp flanking), then run GRIDSS on the much smaller BAM files.

If you're using the CIRCOS program to generate a circos plot, then you want BEDPE as input.

If your VCFs are standards-compliant (I couldn't find any information about the output file anywhere in the brass documentation), then you should be able to use my https://github.com/d-cameron/StructuralVariantAnnotation R package to convert them to BEDPE (see https://github.com/PapenfussLab/gridss/blob/master/example/somatic.R for an example of saving to BEDPE).
