### ISSUE TITLE
hang forever at SequentialCoverageAnnotator

### ISSUE THREAD

**Issue by icanwinwyz** [PapenfussLab/gridss#351]
Hi,
I am using GRIDSS v2.9.1 for my WGS data. I found the process hung at the step "SequentialCoverageAnnotator" and no updates anymore, though VCF was generated.  Also, there is only one file "<sample_name>_dedup_reads.vcf.breakpoint.vcf" in the folder <sample_name>_dedup_reads.vcf.gridss.working/. I deleted the VCF file and <sample_name>_dedup_reads.vcf.gridss.working/ folder and ran it agian, sometimes, it can complete successfully to the final step "VcfTransformCommandLineProgram" and calculated total "Elapsed time". Could you let me know how to fix this problem? Many thanks in advance!

###last two lines for job hanging forever:
INFO	2020-05-18 18:28:43	SequentialCoverageAnnotator	Processed   820,000,000 records.  Elapsed time: 00:28:37s.  Time for last 10,000,000:   16s.  Last read position: chrY:56,461,403
INFO	2020-05-18 18:29:25	SequentialCoverageAnnotator	Processed   830,000,000 records.  Elapsed time: 00:29:19s.  Time for last 10,000,000:   42s.  Last read position: chrUn_JH584304:53,975

###last two lines for job finished successfully:
INFO	2020-05-18 17:44:30	SequentialCoverageAnnotator	Processed   980,000,000 records.  Elapsed time: 00:36:44s.  Time for last 10,000,000:   40s.  Last read position: chrUn_JH584304:83,944
INFO	2020-05-18 17:44:35	VcfTransformCommandLineProgram	Annotated variants written to 30_dedup_reads.vcf
[Mon May 18 17:44:35 PDT 2020] gridss.CallVariants done. Elapsed time: 978.55 minutes.
Runtime.totalMemory()=7272923136

**Comment by d-cameron** [comment]
Please attach the full log files from the problematic run to this issue so it can be investigated further. 

Thanks
