### ISSUE TITLE
Preprocessing Failing

### ISSUE THREAD

**Issue by nivanmamak** [PapenfussLab/gridss#356]
I am running gridss v2.9.2.

I have only two samples and I am running each step individually (not in parallel). There was no issues with the set up reference step but preprocessing seems to fail on the first bam at the same stage everytime. I was initially using 2.9.1 before the 2.9.2 release and was getting the same issue. 

This is my command:

$gridss --reference /home/s1507740/schoenebeck_group/INDEXED_GENOME/canis_familiaris_99/dna_index/Canis_familiaris.CanFam3.1.dna.toplevel.fa --output gridss_3921_5331.vcf.gz --jar ~/NIVAN/BIN/gridss/gridss-2.9.2-gridss-jar-with-dependencies.jar --assembly gridss_3921_5331_assembly.bam  --labels 5331,3921 ../ROS.gDNA.SID05331.bam ../ROS_gDNA_SID03921.bam --jvmheap "72g" --steps preprocess

This is the error I keep getting about 2-3 hours into the run:

14:10:22.542 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/exports/cmvm/eddie/eb/groups/schoenebeck_group/NIVAN/BIN/gridss/gridss-2.9.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu May 21 14:10:22 BST 2020] PreprocessForBreakendAssembly ALIGNER=BWAMEM ALIGNER_BATCH_SIZE=10000 INPUT=./ROS.gDNA.SID05331.bam.gridss.working/tmp.ROS.gDNA.SID05331.bam.namedsorted.bam OUTPUT=/dev/stdout WORKER_THREADS=8 WORKING_DIR=. TMP_DIR=[./ROS.gDNA.SID05331.bam.gridss.working] COMPRESSION_LEVEL=0 REFERENCE_SEQUENCE=/home/s1507740/schoenebeck_group/INDEXED_GENOME/canis_familiaris_99/dna_index/Canis_familiaris.CanFam3.1.dna.toplevel.fa    MIN_CLIP_LENGTH=15 MIN_CLIP_QUAL=5.0 ASSUME_SORTED=false TAGS=[R2, MQ, SA, MC, NM] IGNORE_DUPLICATES=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu May 21 14:10:22 BST 2020] Executing as s1507740@node2i04.ecdf.ed.ac.uk on Linux 3.10.0-862.14.4.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_74-b02; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.9.2-gridss
INFO    2020-05-21 14:10:23     BwaAligner      Loading bwa mem index image from /home/s1507740/schoenebeck_group/INDEXED_GENOME/canis_familiaris_99/dna_index/Canis_familiaris.CanFam3.1.dna.toplevel.fa.img
INFO    2020-05-21 14:10:24     SAMFileWriterFactory    Unknown file extension, assuming BAM format when writing file: file:///dev/stdout
INFO    2020-05-21 14:10:30     StreamingSplitReadRealigner     Seen many non-increasing record positions. Printing Read-names as well.
[Thu May 21 14:24:22 BST 2020] gridss.PreprocessForBreakendAssembly done. Elapsed time: 14.00 minutes.
Runtime.totalMemory()=2058354688
Exception in thread "main" java.lang.NumberFormatException: For input string: "E00375:336:HJTCGCCXY:6:1101:1073:9115"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at au.edu.wehi.idsv.SplitReadHelper.getRealignmentFirstAlignedBaseReadOffset(SplitReadHelper.java:269)
        at au.edu.wehi.idsv.SplitReadHelper.unclip(SplitReadHelper.java:213)
        at au.edu.wehi.idsv.SplitReadHelper.replaceAlignment(SplitReadHelper.java:321)
        at au.edu.wehi.idsv.SplitReadHelper.replaceAlignment(SplitReadHelper.java:306)
        at au.edu.wehi.idsv.SplitReadRealigner.prepareRecordsForWriting(SplitReadRealigner.java:101)
        at au.edu.wehi.idsv.SplitReadRealigner.writeCompletedAlignment(SplitReadRealigner.java:53)
        at au.edu.wehi.idsv.StreamingSplitReadRealigner.processAlignmentRecord(StreamingSplitReadRealigner.java:115)
        at au.edu.wehi.idsv.StreamingSplitReadRealigner.processCompletedAsyncRealignments(StreamingSplitReadRealigner.java:70)
        at au.edu.wehi.idsv.StreamingSplitReadRealigner.process(StreamingSplitReadRealigner.java:43)
        at gridss.PreprocessForBreakendAssembly.doWork(PreprocessForBreakendAssembly.java:157)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.PreprocessForBreakendAssembly.main(PreprocessForBreakendAssembly.java:75)
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Thu May 21 14:24:23 BST 2020: pre-processing failed for ../ROS.gDNA.SID05331.bam

**Comment by d-cameron** [comment]
Please post the all the SAM records for the offending read `E00375:336:HJTCGCCXY:6:1101:1073:9115`

**Comment by nivanmamak** [comment]
E00375:336:HJTCGCCXY:6:1101:1073:9115   1123    4       87590204        60      149M    =       87590979        868     ANGAAGGAGTCATCGCCATTTAACATAGATGTTATATCATTTCCCATATAAGGGCAATAATAAGACTCTTCTTTAACTCTTACTCCAAATCATCAGCATAAATAGCAAAATATCGGTGAGGATGGATTTGAAAAGGGAAATTCGAGGCA     >#;>=?=??>?>>?8>=>>>>>>=>>>??>?>>>>>>?>>;>==<>>>>>>?==>>>>>>>>>?><2=?>=?>>>>=<=?>>=;=<=>=>?>===?>=>>>>>>?>>>9>9=:?7=:6;?=>>>;;0:?;??;=>=;?>??..11-:<<     MC:Z:56S93M     BD:Z:FFFFJHKJFKJIIIFEGHHF?DEEEHEHDGIEFDEEEHHHF?EHCHHEEEEDGBGIGEEEEEEDDGHEDEEDE?DEEHEDEDHHEHHG?EHHHHHHIIHEE?EEHIIG??EEEIFEHFIEHHHJIHHG@GIF@AFIDIGBHIIJKEHHJ        MD:Z:1A147RG:Z:1  BI:Z:FFFFHGHHFIFHGFFEFHGD@EEEFGEGEGGFFEFEFFHGD@DFCHGEFEEEFCGHGFEEFEEEEEIEFDEFDAFFFIEFDFGIEGIHAGGIHGIIIIHFFAGFHIIHAAGFGGGFHFHFHIIIIIIFBHIICCHJGKKELJKMNFGHI        NM:i:1  MQ:i:60 AS:i:147        XS:i:0  mc:i:87591071   ms:i:3985
E00375:336:HJTCGCCXY:6:1101:1073:9115   1171    4       87590979        60      56S93M  =       87590204        -868    GNTCCCCCTCAACCGACACTCAAAGCGCNTGACACCAGCTGCTCATGCAAGNACTGGTTCNTCTTCCTNGACCANACCAGNCTTCATCGACATCANCCCTGTATTGTAGANAAACAAATGCTTCCTTCAAACTCTCTGANCTCACCNTN     -#08&2*+0)-8&$-0,.;>6--3&7><#>=>?>=?;><09<>;=>=>;>4#<5/):==>#=;5838*#+7=;>#>=7=+#4==8.>8?>?><?=#=;9><>>>;==>?=#>>>?>>7>>?>?==>=9=>=?>?<:>?>#?>?=<<#<#     SA:Z:4,87590585,-,63M86S,49,7;  MC:Z:149M BD:Z:FFHCGFKHKIIIFGJGGKEIG@FJFFFFFIIFFHIIJJIJJEIJIJIFEEEEIHHHEEEEEDDEGGEEEHGHEEEGHHEEEDEHIGFEHEIGHEEEBGHEHEEGEHHDEEE?FEF?FHIIDEGGDEHF?FIDDDEIIFFGFKHKJFFFF        MD:Z:4C7T5A5T7A6A14C28G6C1C0    RG:Z:1  BI:Z:FFHDIILKMKKKIJIIHKHIHBEJGGGGGJHGFHHHIIIIIFHHHIGGDFFFIIIGFGFFFFFGHGFFFGHHFFFHHHFFFFGGGGFFFFGGGEEECFHFFEFGFFGEEEE@FFF@DGHHEFGFEFGF@FHEEEEHHEEEFHFIGFFFF        NM:i:10 MQ:i:60 AS:i:71 XS:i:19 mc:i:87590204   ms:i:5379

**Comment by d-cameron** [comment]
Which aligner did you use? You appear to have a split read alignment that is `149M` on one side, and `63M86S` on the other side. This is a nonsensical split alignment as one side doesn't have a soft clip at all.

It looks like I might need to add extra input sanity checking to filter out such records.

**Comment by d-cameron** [comment]
Are those all the alignments for that read? What about the record starting at 4:87590585? Is that one missing?

**Comment by nivanmamak** [comment]
> Are those all the alignments for that read? What about the record starting at 4:87590585? Is that one missing?

Seems like it, there is no record starting at 4:87590585. These are the two records and there is nothing between them:

E00375:336:HJTCGCCXY:6:1204:22648:62804 83      4       87590566        60      82M67S  =       87590225        -423    TCACTCACAGATGATCCCTGTTCCCCATCAACAGACACTCAAAGCGCATGACACCAGCTGCTCATGCAAGAACTAGTTCCTCTTCCTTGACCAAACCAGTCTTCATCGACATCAACCCTGTATTGTAGACAAACAAATGCTTCCTTCAA     ?>=??@?@@@??@?@=>@?>??===??@?>>???>?>???>>?>8>?>>?>?>=??>?>>???>>>?>??>>>>?==>=???>?=?>>?>=?>>>=??=??>??>?8?>?>??>>==?>=>>>>=>??>?>>>?>>>>>?>?=?=>==>     SA:Z:4,87590974,-,70S79M,60,1;  MC:Z:150M BD:Z:IFJEMJIKGKJJJIIDHIFFFHCCIJHIGGFIEIFFIDHF?EIEEIIHHHEEGHHIIHIIDHIHIIFEDEFIHHHEEGGDDDEGGDGHHGHF?FGHHHGDDEHIGFEHEIGHFFGBGHEHEEGEHHDHEF?FEF@GIJKFGJKHJIGFF        MD:Z:82 RG:Z:1  BI:Z:HFIFOLMMKKLLJKJFIKHGHIEEIIIIHGGHFGGFIFHGADIFFGHHIGGFHHHIIIIIFHHHIGGDFEGIHHIFGHGFFFGGFEGHFGGF@FGGGHEEEFGGGFFFFGGGFFGCFHFFEFGFFGEFFF@FFF@DGHHFGHHGHHGFF        NM:i:0  MQ:i:60 AS:i:82 XS:i:19 mc:i:87590225   ms:i:6023
E00375:336:HJTCGCCXY:6:1220:26991:20014 129     4       87590643        0       150M    29      25560300        0       CCCTCGGGATCCCTGGGTGGCGCAGCGGTTTGGCGCCTGCCTTTGGCCCAGGGCGCGATCCTGGAGACCCGGGATCGAATCCCACGTCGGGCTCCCAGTGCATGGAGCCTGCTTCTCCCTCTGCCTGTGTCTCTGCCTCTCTCTCTCTCT    =:;==8==?=?==??==>?==7>>?>8=>>>?=>8>=??>=?=>?=>==>>==>8>8?>?=??=???===8==?>>8?>>?==>=8=?8==>:<==>?>?>>>?=??>=@@??>?>?==??@@?>@>>@?@?@@?>>?@3>?=>>=;:;?    XA:Z:X,-36381762,148M2S,0;5,+14554914,150M,1;16,-19790610,150M,1;13,-6888868,4S146M,4;    MC:Z:36M7I107M  BD:Z:FFDHJIGEIIIIDHIHBGEHGEEIHIEDGF?FHGEEGGHIGGE?FHGGCHHGBGEEEFGHHGHHGDDGHCDDBGGHEFEEHHCHEGGHEDBGIEHCHHIEIIHJIHEJHHIJJFFEFIDHFEIJHHIFFFIFGFJKIIHGHHIHJIFEFE       MD:Z:0T149      RG:Z:1  BI:Z:FFDHFHFDHGFFCGGGCGEGGEEHHHEEGF@FGGEEFGGFFGC@FGGFCHHFCGEEEFGFFGGGGEFFGDFFDHHGGGGGGGDIEHHGGFDHIEGDIIIFGIHHHHFIGHHGIDEFEGEIFGIHHIIHGHIHGHJJJKIJJKJKJKEFEF       NM:i:1  MQ:i:60 AS:i:149        XS:i:148 mc:i:25560300    ms:i:5309

**Comment by DarioS** [comment]
What alignment software and version of it did you use? It seems like every one of them makes some different assumptions about the vaguely-worded SAM format. GRIDSS prefers BWA alignments.

**Comment by nivanmamak** [comment]
I don't have much experience working with SAM/BAM files. I believe this BAM was processed by Illumina to be analysis ready and they use the GATK Best Practice guidelines. I think GATK uses BWA?

I've used the exact same BAMs to successfully run pindel, delly, and lumpy which have also required BWA sorted files so I don't think that can be the issue.

**Comment by d-cameron** [comment]
Should be fixed in the next release.

There was an edge case in GRIDSS's handling in the fixing of the incorrect records being written by GATK indel realignment. GATK indel realignment does not update the SA tag, nor the mate record field with the new alignment so results in an internally inconsistent BAM file. In your example, the first record has an SA tag referring to 

The specific bug is due to GRIDSS preprocessing converting soft clips to split reads (so it works with aligners such as bowtie2 which, unlike bwa, does not report split read alignments at all), and the GATK indel-realigned record having a better mapping with a better mapping than the GATK indel realigned read (i.e. undoing the GATK indel realignment) which gets extended to the full read length (`36M7I107M`) causing GRIDSS to replace the primary alignment with this alignment (usually they're just additional supplementary alignments). GRIDSS had a bug in this last part.

> I believe this BAM was processed by Illumina to be analysis ready and they use the GATK Best Practice guidelines

GATK indel realignment has not been part of GATK best practice guidelines for quite a few years.
