### ISSUE TITLE
When SVLEN is set to 0?

### ISSUE THREAD

**Issue by woodoo46** [PapenfussLab/gridss#357]
I noticed that some vcf records have SVLEN=0, some have SVLEN > 0; when SVLEN is set to 0? Thanks!

**Comment by d-cameron** [comment]
Which records? GRIDSS does not report SVLEN. Are you referring to the svLen from the `StructuralVariantAnnotation` package?

**Comment by d-cameron** [comment]
VCF defines `SVLEN` as:
```
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
```

**Comment by woodoo46** [comment]
After simple-event-annotation.R annotation, sometimes, in some SIMPLE_TYPE=INS records, there is a >0 number for SVLEN; while others have SVLEN=0. I am guessing this may be due to breakpoint?

**Comment by d-cameron** [comment]
Yyes, small insertion will be essentially be reported as deletions with insertions of sequence of the same length. I don't (yet) have special case code to check the inserted sequence against the reverse-complement of the deleted sequence and report matches as `<INV>` events.

SVLEN=0 only when the inserted sequences exactly matches the deleted sequence length. Even for actual inversion events, this is frequently not the case.
