### ISSUE TITLE
IMPRECISE flag and CI fields clarification

### ISSUE THREAD

**Issue by cbrueffer** [PapenfussLab/gridss#358]
Hi Daniel,

I wonder about the potentially two definitions of "imprecise" in the GRIDSS VCF header.

The way I read the VCF header info for the CI fields (CIPOS etc) is that those fields should only be present for imprecise SVs. Then there is the IMPRECISE flag; naively I would think that all SVs with CI fields should also be IMPRECISE, but I see plenty of SVs where that's not the case. Looking at CIPOS, IMPRECISE seems to be set only for very imprecise SVs, while CIPOS of e.g. -2,1 is considered precise in this context.

Am I missing something, or are there indeed two "imprecise" definitions? If yes, does it make sense to include a bit more information in the IMPRECISE VCF header?

**Comment by d-cameron** [comment]
I thought I'd replied to this at the time. I must not have actually clicked the comment button - sorry about this.

GRIDSS follows the VCF specifications for breakpoint microhomology.

IMPRECISE+CIPOS means: I don't know where this breakpoint could be

CIPOS without imprecise means: there is a breakpoint microhomology and all breakpoint positions in this interval result in the same sequence.


See Section 5.4.8 and Figure 9 of https://samtools.github.io/hts-specs/VCFv4.2.pdf for an example of the latter.

**Comment by d-cameron** [comment]
GRIDSS uses the description specified in the VCF specifications. Yes, these could be worded better.
