### ISSUE TITLE
Document Example of Somatic Filter and tumourordinal Usage

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#359]
It fails with an obscure error message if `--tumourordinal` is not specified.

```
Error in (function (object, class, nargs)  : 
  Invalid argument value: expecting integer but got: (NA).
Calls: parse_args -> mapply -> <Anonymous>
Execution halted
```

I would like to see an example in the documentation of a way to specify "all samples in the VCF file other than the value of normalordinal" when the different VCFs have a different number of tumours per patient. Could that be the default value, perhaps?

**Comment by d-cameron** [comment]
Waiting for the https://bitbucket.org/djhshih/argparser/issues/21/optional-integer-vectors-fail-to-parse fix to make it into CRAN.

**Comment by DarioS** [comment]
For the benefit of other readers, it's easy to install the development version of argparser

```r
library(devtools)
install_bitbucket("djhshih/argparser") # Installs version 0.6.1 which has a fix.
```

The somatic filter analysis will then proceed without error.

**Comment by DarioS** [comment]
argparser version 0.7.1 is now in CRAN and the issue above is closed. Documentation update can happen.
