### ISSUE TITLE
Somatic Filter Could Have Number of Normal Samples As User Parameter

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#360]
The R script could accept a score threshold to quickly test out how different scores affect the result.

**Comment by d-cameron** [comment]
The final qual filtering just adds a "qual" filter. The best way to test the qual threshold is to load the full somatic output file into R, strip the `qual` filter, `source("libgridss.R")`, then just call the `passes_final_filters()` from libgridss.R with different `gridss.min_qual` and `gridss.single_breakend_multiplier` thresholds set.

Much faster than subsetting the full ~1Gb input files and rerunning with different parameters.
