### ISSUE TITLE
AlignerFactory Error in Assembly step gridss docker 

### ISSUE THREAD

**Issue by Swanthana-bioinfo** [PapenfussLab/gridss#368]
Hello
I am trying to run gridss through docker with individual steps, here is the error I am getting for assembly step

ERROR   2020-06-29 11:54:13     AlignerFactory  Unable to use Intel GKL library for accelerated Smith-Waterman alignment

Here is assembly script
# Assembly
/usr/bin/time -v singularity run -B /proj ../gridss_latest.sif -r $ref_genome -o 60707-F.vcf.gz -w gridss_tempdir --steps Assemble -a 60707-F.bam -t 8 --jvmheap 31g --labels 60707-F --jobindex $SLURM_ARRAY_TASK_ID --jobnodes 6 $input1

Please point me out where to look at and debug it. I am using BWA aligner 

Thank you.

**Comment by d-cameron** [comment]
> ERROR 2020-06-29 11:54:13 AlignerFactory Unable to use Intel GKL library for accelerated Smith-Waterman alignment

That's not a fatal error as GRIDSS will fall back to libssw, and then to jaligner if that also fails.

That message has now been downgraded to a warning message.
