### ISSUE TITLE
GRIDSS2

### ISSUE THREAD

**Issue by alhafidzhamdan** [PapenfussLab/gridss#369]
Hi all,

Saw your biorxiv paper on GRIDSS2- congrats on putting it together and thank you for your dedication to short read sequencing!  I was wondering if this github page is already catering for that version, rather than GRIDSS1? Very interested to try. 

A

**Comment by DarioS** [comment]
Yes, you can download it from the Releases section. GRIDSS2 just mean GRIDSS version 2.0 or greater - 2.9.4 will be much faster.
