### ISSUE TITLE
T/N sample processing

### ISSUE THREAD

**Issue by alhafidzhamdan** [PapenfussLab/gridss#370]
Hi all,

I have 100s of T/N WGS samples. Each pair only has one tumour and one normal sample.
I am trying to run GRIDSS on them on an HPC scheduler.
I wonder if I should run them seperately at a time like this?

> 
> 
> $GRIDDS \
>     --reference $REFERENCE \
>     --output $OUTPUT_RAW \
>     --assembly $ASSEMBLY \
>     --jvmheap 25g \
>     --workingdir $WORKING_DIR \
>     --blacklist $ENCODE_BLACKLIST \
>     --repeatmaskerbed $REPEAT_MASKER \
>     --jar $GRIDDS_JAR \
>     --steps All \
>     --maxcoverage 50000 \
>     --labels ${PATIENT_ID}${TYPE} \
>     $ALIGNED_BAM_FILE
> 

This will generate GRIDSS VCF output for each sample for each patient in parallel, obtaining vcf files for each tumour and normal sample for each patient. So now i'd have 100 tumour VCFs and 100 normal VCFs.
Then, will I generate the GRIDSS panel of normal like so? :

> 1) Select only "PASS" variants from normal vcf file from each patient.
> 2) Run 
> java -Xmx8g \
>         	-cp $GRIDDS_JAR \
>         	gridss.GeneratePonBedpe \
>         	$(ls -1 $OUTPUT_RAW/*N.vcf.gz | awk ' { print "INPUT=" $0 }') \
>         	O=$GRIDSS_PON/${BATCH}/gridss_pon_breakpoint.raw.bedpe \
>         	SBO=$GRIDSS_PON/${BATCH}/gridss_pon_single_breakend.raw.bed \
>                 NORMAL_ORDINAL=0, NORMAL_ORDINAL=1 .... NORMAL_ORDINAL=99 \   ##Since I have 100 normal VCFs, and using 0-based coordinate ##
>         	THREADS=12 \
>         	REFERENCE_SEQUENCE=$REFERENCE

Next is to use the bed/bedpe files to filter out normal variants from the raw somatic vcfs?

> 1) Select normal variants occuring 3 or more times:
> cat $GRIDSS_PON/${BATCH}/gridss_pon_single_breakend.raw.bed | awk '$5>=3' > $GRIDSS_PON/${BATCH}/gridss_pon_single_breakend.bed
> cat $GRIDSS_PON/${BATCH}/gridss_pon_breakpoint.raw.bedpe | awk '$8>=3' > $GRIDSS_PON/${BATCH}/gridss_pon_breakpoint.bedpe
> 
> 2) Filter these out:
> Rscript $GRIDSS_SOMATIC_FILTER \
>  --pondir $GRIDSS_PON/${BATCH} \
>  --ref $HG38_BSGENOME \
>  --input $OUTPUT_RAW \
>  --output $OUTPUT_FILTERED \
>  --plotdir $GRIDSS_PLOT_DIR/${BATCH} \
>  --scriptdir $LIBGRIDSS
> 

Apologies for the questions but GRIDSS keep throwing errors at different stages and rather than randomly troubleshooting each stage I thought I should just display my thought processes and see if you could help me debug it. Thanks in advance!

A

**Comment by d-cameron** [comment]
>I wonder if I should run them seperately at a time like this?

No. You should do joint analysis for all samples from the same patient. That is, `gridss.sh ... patientX_normal.bam patientX_primary.bam patientX_met.bam`

You then run `gridss_somatic_filter.R` on the per-patient VCF.

>Then, will I generate the GRIDSS panel of normal like so? :

If you're using hg19, you can download a GRIDSS PON from https://resources.hartwigmedicalfoundation.nl/ (HMFTools-Resources -> gridss). You can probably generating PON, although you might want to augment this PON with your samples.

> Select only "PASS" variants from normal vcf file from each patient.

Not required. See `gridss.GeneratePonBedpe` command line arguments. Technically speaking, the PON is there to remove both germline event and systematic noise. If you filter to PASS only your PON won't filter out the systematic noise.

> NORMAL_ORDINAL=0, NORMAL_ORDINAL=1 .... NORMAL_ORDINAL=99 \ ##Since I have 100 normal VCFs, and using 0-based coordinate ##

The ordinal is _per file_. You have no VCFs containing joint calling from 99 BAMs so NORMAL_ORDINAL=99 doesn't make sense. Your arguments should look like `INPUT=patient1.vcf NORMAL_ORDINAL=0 INPUT=patient2.vcf  NORMAL_ORDINAL=0 ...` so your script should be doing something along the lines of:
```
$(ls -1 $OUTPUT_RAW/*N.vcf.gz | awk ' { print "INPUT=" $0 "NORMAL_ORDINAL=0"  }')
```

**Comment by alhafidzhamdan** [comment]
Hi there- thanks for getting back a while ago.
I have since run your recommendations and now at the somatic filtering stage.
Some samples proceeded successfully but there are some that throw an error.



This is my commands:

```
Rscript $GRIDSS_SOMATIC_FILTER \
 --pondir $GRIDSS_PON/${BATCH} \
 --ref $HG38_BSGENOME \
 --input $GRIDSS_RAW \
 --output $GRIDSS_FILTERED \
 --scriptdir $LIBGRIDSS
```

```
Tumour samples: E22T
Matched normals: E22N
2020-08-25 10:17:45 Parsing single breakends /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:17:52 Calculating single breakend VAF /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:17:59 Filtering single breakends /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:00 Loading from cache  /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/pondir/GCGR/gridss_pon_single_breakend.bed.cached.parsed.rds
2020-08-25 10:18:03 Parsing breakpoints /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:04 Calculating breakpoint VAF /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:05 Filtering breakpoints /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:05 Loading from cache  /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/pondir/GCGR/gridss_pon_breakpoint.bedpe.cached.parsed.rds
2020-08-25 10:18:18 Calculating transitive links /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:18 Calculating assembly links /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
`summarise()` ungrouping output (override with `.groups` argument)
2020-08-25 10:18:18 Calculating bebe insertion links /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:18 Calculating bebp insertion links /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:19 Calculating simple inversions /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:19 Calculating dsb links /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
2020-08-25 10:18:19 Removing duplicated/conflicting links /exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/sv/gridss/results/E22.gridss.raw.test.vcf.gz
Error: Can't subset elements that don't exist.
✖ Location 1 doesn't exist.
ℹ There are only 0 elements.
Backtrace:
     █
  1. ├─`%>%`(...)
  2. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5. │     └─`_fseq`(`_lhs`)
  6. │       └─magrittr::freduce(value, `_function_list`)
  7. │         └─function_list[[i]](value)
  8. │           ├─dplyr::mutate(...)
  9. │           └─dplyr:::mutate.data.frame(...)
 10. │             └─dplyr:::mutate_cols(.data, ...)
 11. │               ├─base::withCallingHandlers(...)
 12. │               └─mask$eval_all_mutate(dots[[i]])
 13. ├─base::.signalSimpleWarning(...)
 14. │ └─base::withRestarts(...)
 15. │   └─base:::withOneRestart(expr, restarts[[1L]])
 16. │     └─base:::doWithOneRestart(return(expr), restart)
 17. └─(funct
Execution halted
```

It says at the removing duplicated/conflicting stage "Location 1 doesn't exist".

Here's the head of the vcf.
`
chr1	10021	gridss0bf_1o	A	]chr1:10330]A	99.25	LOW_QUAL;NO_ASSEMBLY	AS=0;ASC=1X3N1X;ASQ=0.00;ASRP=0;ASSR=0;BA=0;BANRP=6;BANRPQ=99.25;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BMQ=26.20;BMQN=21.00;BMQX=42.00;BQ=127.22;BSC=1;BSCQ=21.04;BUM=4;BUMQ=106.18;BVF=5;CAS=0;CASQ=0.00;CIPOS=-2,2;CIRPOS=-19,20;CQ=99.25;EVENT=gridss0bf_1;IC=0;IMPRECISE;IQ=0.00;MATEID=gridss0bf_1h;MQ=37.83;MQN=29.00;MQX=47.00;RAS=0;RASQ=0.00;REF=467;REFPAIR=0;RP=6;RPQ=99.25;SB=1.0;SC=1X3N1X139M32D35M2D96M;SR=0;SRQ=0.00;SVTYPE=BND;VF=6	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0.00:0:0:3:48.75:0:0.00:0.00:0:0:24.00:0:0.00:1:24.00:1:0.00:0:0.00:48.75:0.00:181:0:3:48.75:0:0.00:3	.:0.00:0:0:3:50.49:0:0.00:0.00:0:0:103.22:1:21.04:3:82.18:4:0.00:0:0.00:50.49:0.00:286:0:3:50.49:0:0.00:3
`

Also attached the log file for the initial GRIDSS calling step.

Any ideas?
Thank you.
[log.txt](https://github.com/PapenfussLab/gridss/files/5122819/log.txt)
