### ISSUE TITLE
No overlap with Genome in a Bottle benchmark NA24385

### ISSUE THREAD

**Issue by pauline-ng** [PapenfussLab/gridss#371]
Hi,

I was trying to run GRIDSS on GiaB NA24385 (HG002) and benchmark its performance. Strangely, the structural variants I get from GRIDSS doesn't overlap at all with the Genomes in a Bottle benchmark set. 
I downloaded the bam file for NA24385 (HG002) from [here](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_Illumina_2x250bps/novoalign_bams/). 

I ran gridss:
`./gridss.sh  --threads 12 --reference  ref_genome/hs37d5.fa --output results.vcf.gz --assembly results/HG002.output --jar gridss-2.9.3-gridss-jar-with-dependencies.jar  --workingdir results/ HG002.hs37d5.2x250.bam`

and after 10 hours, the results.vcf.gz was generated.

To benchmark GRIDSS performance, I tried using

- Truvari : I get 0 true positives  (and 0 precision, 0 recall). I tried the VCF directly generated by GRIDSS and also the VCF generated from the simple-event-annotation.R script

`truvari -bNA24385_benchmark/HG002_SVs_Tier1_v0.6.vcf.gz -c results_simple-event.vcf.gz -o gridss_result --passonly --pctsim 0
`

- bed intersect showed only 30 regions from the GRIDSS bed file overlaps with the 34,830 SVs in the benchmark bed file.

intersectBed  -a HG002_SVs_Tier1_v0.6.bed -b gridss_results.simple.bed -wao  -f 0.5 | cut -f4-6  | sort | uniq | wc -l

Do you have any suggestions why my GRIDSS results are not working on benchmark data? I'd appreciate any hints or suggestions. 

Many thanks in advance,
Pauline

**Comment by d-cameron** [comment]
Have you compared any other callers? It's a good idea to sanity check your results by inspecting some of the 'easy' to detect SVs.

My best guess is that you have adjusted for the fact that hs37d5 uses NCBI-style chromosome names (1, 2, 3, ...), and HG002_SVs_Tier1_v0.6.vcf.gz uses UCSC-style chromosome names (chr1, chr2, chr3, ...).

Your results should be similar to the ones I obtained from a 60x downsampling of HG002_hs37d5_300x.bam using the StructuralVariantAnnotation package to do the comparison (https://github.com/PapenfussLab/gridss/blob/master/scripts/gridss2_manuscript/germline.R)

<img width="985" alt="hg002" src="https://user-images.githubusercontent.com/6036536/87497043-16ea3d80-c698-11ea-8f6c-18c043df4a5c.png">

**Comment by pauline-ng** [comment]
Hi Daniel,

Can I checked if you preprocessed the bam files? I noticed that in your sv_benchmark repo, the file names are HG002_hs37d5_2x250.sc.bam and was wondering if the sc meant something.

I'm using the HG002 Novoalign .bam files from [NCBI](https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_Illumina_2x250bps/novoalign_bams/)  and there's no .sc suffix.

I have Manta working and it benchmarks to GiaB correctly. I'm using hs37d5 for both GRIDSS and the GiaB benchmark and the chromosomes are "1", "2" so that isn't the issue.

Best,
Pauline

**Comment by d-cameron** [comment]
>was wondering if the sc meant something

**S**orted by **C**oordinate. It's just a file convention for the driver script. Found downloaded from `ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_Illumina_2x250bps/novoalign_bams/HG002.hs37d5.2x250.bam` with md5sum of `1f9a36450839bde584ce4be5ec6df2ad`.

> Truvari : I get 0 true positives (and 0 precision, 0 recall).

This sounds like Truvari does not fully support the VCF specifications.

> also the VCF generated from the simple-event-annotation.R script

That won't help since that script doesn't change the `SVTYPE` nor changes the format from `BND` notation to symbolic allele notation.


An issue has been raised with truvari: https://github.com/spiralgenetics/truvari/issues/55

**Comment by d-cameron** [comment]
In the meantime, I've been using `StructuralVariantAnnotation::findBreakpointOverlaps()` for matching breakpoints.

If you're benchmarking short read callers against, the GiaB NIST Tier1 call set then you should be aware that many tandem duplications which are reported as duplication events by the short read callers are included in the truth set as insertions calls.

**Comment by d-cameron** [comment]
I've done a bit more benchmarking for you. Here are my internal benchmarks for HG002 Illumina Platinium Genomes samples against the NIST Tier 1 truth set. The 2x250bp call set is surprisingly conservative compared to the other ones but it's definitely not zero overlap.
![image](https://user-images.githubusercontent.com/6036536/87540683-715cbb80-c6e3-11ea-9cf4-7dc608ca1d15.png)

**Comment by pauline-ng** [comment]
Hi Daniel,

Thanks so much for all your help. Your germline.R script did the trick and it's working now.

Thanks also for opening the issue with Truvari. 

Best,
Pauline
