### ISSUE TITLE
Add config option to limit size of IO thread pool

### ISSUE THREAD

**Issue by christopher-schroeder** [PapenfussLab/gridss#372]
When I perform the -s call step for gridss and its running the IdentifyVariants, it seems that gridss ignores the -threads parameter. It takes the full number of available cores independent from any given parameter.

**Comment by d-cameron** [comment]
`--threads` specifies worker threads. IO threads are not included in the worker thread count. By default, GRIDSS uses multithreaded IO so peak CPU usage can exceed the # worker threads specified since BAM decompression and parsing is done on the IO threads. Since a large part of `IdentifyVariants` is reading the files and parsing the records. If you really need CPU usages hard limited, the multi-threaded IO can be disabled my editing lines 467-472 of `gridss.sh`.

**Comment by d-cameron** [comment]
Nevermind, I already put that config option in. `-Dasync_io_read_threads=1` will limit BAM decompression and parsing to a single thread.

Some of the `IdentifyVariants` steps are processed in seperate threads. These also are not included in the worker thread parameter.

**Comment by tedil** [comment]
I know that this has been closed already, but for some further reasoning behind this request: When running gridss steps in workflows/pipelines, especially in a distributed or benchmark setting, you need to be able to control the number of cores and or threads (and memory) so it does not exceed certain limits (which you could do with containers, but that incurs additional overhead).

**Comment by d-cameron** [comment]
GRIDSS is much more strict in terms of respecting memory limits than it is for CPU.

I've chosen to err on the side of improving the default performance and accepting higher peak CPU utilisation and the associated increased contention between threads, than treating the `--thread` parameter as a hard limit. A good example of this is the metrics collection. That uses Picard tools code and is single threaded so the only way to speed that up (without a massive PR to Picard tools).

GRIDSS has been optimised to run on a 8core/32gb^ cloud compute node and the multi-threaded design decisions have been made to minimum wall time in such an environment. Pre-optimisation, running GRIDSS on such a system cost ~$30 in cloud compute costs - a non-trivial cost given we have run GRIDSS on over 5,000 100x/40x tumour/normal samples. With optimisations and pre-emptible GCE instances, our cost is now ~$3.30 per sample. Unless there is an extremely compelling reason, I am unlikely to be making any threading changes that increases this cost.

Is there a reason that cpulimit(1) is not an acceptable solution for hard limiting max CPU usage? Many of the clusters I've used do in fact max limit job CPU utilisation to the # cores requested in the job.

^Technically, the default settings are designed to run on a machine with 29gb available for compatibilty with the sizing of DNA Nexus compute nodes.

**Comment by tedil** [comment]
Thank you for the information!
Indeed, cpulimit / limitcpu is a reasonable alternative, perhaps even `-XX:ActiveProcessorCount=...`.

**Comment by d-cameron** [comment]
> perhaps even `-XX:ActiveProcessorCount=`

GRIDSS invokes `bwa mem` and the passes through the `--threads` parameter to bwa. There's a java thread feeding bwa, and one parsing the output and N doing the async BAM compression and writing to disk. bwa batch size is pretty huge so these mostly end up blocking on bwa, or bwa blocking on them, but you do still get brief spikes above the nominal max.
