### ISSUE TITLE
Allow user to specify path to gridss_config.R

### ISSUE THREAD

**Issue by lkhilton** [PapenfussLab/gridss#376]
I've come across several reasons to tweak the values in `gridss_config.R`, especially with respect to the very hard filters and the allowable normal contamination for cancers with tumour-in-normal contamination. However currently the path to `gridss_config.R` is hard-coded in `libgridss.R`, which means I have to duplicate both scripts to modify the values in `gridss_config.R` if I want to keep the version with the default values. Would it be possible to allow the user to specify the path to the `gridss_config.R` on the command line when launching `gridss_somatic_filter.R`?

**Comment by DarioS** [comment]
Also, I am wondering how the R script filtering compares to [GRIPSS](https://github.com/hartwigmedical/hmftools/tree/master/gripss) - GRIDSS Post Somatic Script Java application?

**Comment by d-cameron** [comment]
GRIPSS is a reimplementation of `gridss_somatic_filter.R` in kotlin. It's a drop-in replacement but there has been some additional development on the GRIPSS side (specifically, additional logic for the LINC00486 hotspot, and better identification of LINE translocation events).

The development version of the Hartwig pipeline has already migrated to GRIPSS. If you are using human data, I recommend GRIPSS for somatic filtering - it's much faster and has additional features.

I'm still working out the exact details, but I plan to include GRIPSS in future GRIDSS releases.

**Comment by lkhilton** [comment]
I will definitely try out GRIPSS. Thank you both for your quick response on this.
