### ISSUE TITLE
Viral insertion breakpoint with QUAL=0

### ISSUE THREAD

**Issue by vladsaveliev** [PapenfussLab/gridss#377]
I'm trying to run GRIDSS+AnnotateInsertedSequence+GRIPSS on a sample with an HPV16 viral integration. There is an integration site on chr20, visible in IGV. For this screenshot, reads aligned to a hg38+HPV16 combined fasta are groupped by the chromosome of mate, so those 2 pink clusters correspond to 2 breakpoints on chr20:

![image](https://user-images.githubusercontent.com/1575412/90006061-8b39f000-dcdb-11ea-83fa-9a5ee58fd86b.png)

The left one is more clear, and lumpy catches the position precisely using split reads: 

```
chr20   57221460        20_1    N       N]HPV16:3442]   .       PASS    SVTYPE=BND;STRANDS=++:79;EVENT=20;MATEID=20_2;CIPOS=-9,9;CIEND=-3,3;CIPOS95=0,0;CIEND95=0,0;SU=79;PE=71;SR=8
```

I ran GRIDSS on the same data, but aligned to hg38 only, to test drive the novel insertion annotation. GRIDSS successfully calls this breakpoint, and gridss.AnnotateInsertedSequence correctly annotates it as an HPV16 insertion. However, the PR, SR and QUAL values are 0, so GRIPSS hard-filters this event out as a . Wondering why the read support was assigned zero?

```
chr20   57221460        gridss277f_17711b       G       GCAAGGCGACGGCTTTGGTATGGGTCGCGGCGGGGTGGTTGGCCAAGTGCTGCCTAATAATTTCAGGAGAGGATACTTCGTTGCTGCTAAACACAGATGTAGGACATAATATTACCTGACCACCCGCATGAACTTCCCATACTTTATTTTTACTATATTTTTCTGCATCATCTTTAAACTGCACAAAATATGTTCGTATTCCTTCATGAACATAATATAAACCATAATAGTCAACTTGACCCTCTACCACAGTTACTGATGCTTCTTCACAAATATATATATGTGTCCAGTTTGTATAATGCATTGTATTGCATATGTCTCCATCAAACTGCACTTCCACTGTATATCCATGTTTTTTTATACATCCTGTTGGTGCAGTTAAATACACTTCAAGGCTAACGTCTTGTAATGTCCACTTTTCATTACTATATTGTGAGTTATATATTGTTTCTAACGTTAGTTGCAGTTCAATTGCTTGTAATGCTTTATTCTTTGATACAGCCAGTGTTGGCACCACCTGGTGGTTAATATGTTTAAATCCCATTTCTCTGGCCTTGTAATAAATAGCACATTCTAGGCGCATGTGTTTCCAATAGTCTATATGGTCACGTAGGTCTGTACTATCATTTTCATAATGTGTTAGTATTTTGTCCTGACACACATTTAAACGTTGGCAAAGAGTCTCCATCGTTTTCCTTGTCCTCGTCCTCGTGCAAACTTAATCTGGACCACGTCCTTGAGAAAAAGGATTTCCAGTTCTTATCATTAAGCTCATACACTGGATTTCCGTTTTCGTCAAATGGAAACTCATTAGGAAATGTAAACACCA.  4634.43 PASS    AS=0;ASC=1X;ASQ=0;ASRP=0;ASSR=0;BA=1;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=2317.22;BASRP=51;BASSR=26;BEALN=HPV16:2615|-|828M|60;BEID=asm277-28602;BEIDH=-1;BEIDL=0;BMQ=60;BMQN=60;BMQX=60;BQ=4634.43;BSC=26;BSCQ=738.93;BUM=51;BUMQ=1578.28;BVF=67;CAS=0;CASQ=0;CQ=4664.58;EVENT=gridss277f_17711;IC=0;IQ=0;RAS=0;RASQ=0;REF=186;REFPAIR=187;RP=0;RPQ=0;SB=0.384615;SC=1X;SR=0;SRQ=0;SVTYPE=BND;VF=0    GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF   .:0:0:0:0:0:0:0:2317.22:51:26:4634.43:26:738.93:51:1578.28:67:0:0:0:0:0:121:134:0:0:0:0:0       .:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:65:53:0:0:0:0:0
```

Happy to do more tests, or isolate a small bamlet if it would be helpful.

Vlad

**Comment by vladsaveliev** [comment]
Have to note that comparing to Lumpy is a bit unfair because when GRIDSS is run the same way (on a "unmapped + reads with an unmapped mate" subset of reads from the tumor sample, aligned to a combined hg38+HPV16 fasta), it calls the same breakpoint with a non-zero QUAL:

```
chr20   57221460        gridss277ff_12o G       G]HPV16:3442]   2089.65 SINGLE_ASSEMBLY AS=1;ASC=1X;ASQ=1082.99;ASRP=77;ASSR=11;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID
=asm277-26;BEIDH=823;BEIDL=0;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=76.33;BSC=3;BSCQ=53.61;BUM=1;BUMQ=22.71;BVF=0;CAS=0;CASQ=0.00;CQ=2067.57;EVENT=gridss277ff_12;IC=0;IHOMPOS=0,0;IQ=0.00;MATEID=gridss277ff_12h;MQ=59.28;MQN=23.00;MQX=60.00;RAS=0;RASQ=0.00;REF=3;REFPAIR=0;RP=76;RPQ=839.36;SB=1.0;SC=822M1X;SR=8;SRQ=167.30;SVTYPE=BND;VF=80 GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF   .:1082.99:77:11:0:0.00:0:0.00:0.00:0:0:76.33:3:53.61:1:22.71:0:0.00:0:0.00:2089.65:0.00:3:0:76:839.36:8:167.30:80
```

So just curious if it's possible to catch it from a tumor/normal data aligned to the host genome alone.

**Comment by d-cameron** [comment]
> However, the PR, SR and QUAL values are 0 ... Wondering why the read support was assigned zero?

Single breakends never have SR/RP/IC/AS/RAS/CAS/VF support since there's nothing aligned to the other side (in this case, because it's not in the reference genome).

The fields relevant to single breakends are the single breakend equivalents: BSC, BUM, BA, BVF, BQ.

>so GRIPSS hard-filters this event out as a

That's not why GRIPSS filtered the event. It's got a QUAL score of 4634.43 so it shouldn't have been filtered.

It looks like GRIPSS filtered the event because your sample ordering in your VCF was tumour.bam then normal.bam, not normal.bam then tumour.bam that the hartwig pipeline assumes.

> So just curious if it's possible to catch it from a tumor/normal data aligned to the host genome alone.

We do this in the HMF pipeline and our detection results look the same as what you've found: single breakends with sequence annotated with the viral sequence.

**Comment by d-cameron** [comment]
I'm currently working on a more comprehensive version of host-aligned bam to viral integrations calling that should hopefully be able to detect viral integrations in unmappable sequence (e.g. centromeres).

I've just started testing so if all goes well, it will be included in the next GRIDSS release.

**Comment by d-cameron** [comment]
Would you be interesting in beta testing?

**Comment by vladsaveliev** [comment]
Huh, indeed. Was confused by the FORMAT/QUAL field which is 0 for both tumor and normal. Which is expected for single breakend events as you pointed. The qual value here is read from FORMAT/BQ instead.

Thanks!

By the way, what's the way to get the matching breakpoint position in the viral sequence? I understand it's encoded in the BEALN field, e.g. the start position for my example is 2615 according to `BEALN=HPV16:2615|-|828M|60`. However as I see in IGV, 2615 is the start of the leftmost discordant-paired read supporting the event. According to split reads and GRIDSS run on a combined hg38+HPV reference, the exact breakpoint is at 3442: `G]HPV16:3442]`. Unless I'm blind again.

And I'd be interested in testing the new version, though I don't have test use cases with insertions in centromeres.

**Comment by d-cameron** [comment]
>I don't have test use cases with insertions in centromeres.

You might, you just don't know know it because there's currently nothing that can detect these events.

>what's the way to get the matching breakpoint position in the viral sequence? 

You need to calculate it from the `BEALN` alignment and the breakend orientation.

```
chr20   57221460        gridss277f_17711b       G       GCA<snip>CCA.  <snip> BEALN=HPV16:2615|-|828M|60
```

In this case, the breakend is in forward orientation, and the alignment to HPV is on the negative strand. The `BEALN` alignment sequences are the verbatum breakend sequences so the 'first' base of the sequence is the one closes to the chr20. Since the alignment is on the negative strand, this 'first' base is the last aligned base. The alignment starts at 2615, has a CIGAR of 828M so the position of the integration site is 2615 + 828 - 1 = 3442 which matches the hg38+HPV result.

**Comment by vladsaveliev** [comment]
Thanks a lot for the explanation!

> You might, you just don't know know it because there's currently nothing that can detect these events

Huh, fair :)
