### ISSUE TITLE
Single-breakend event not called?

### ISSUE THREAD

**Issue by vladsaveliev** [PapenfussLab/gridss#381]
Hi Daniel,

I'm trying to understand why GRIDSS wouldn't call this breakpoint. It's an HPV18 integration site on a chromosome 8, with lots of discordant and split reads supporting it. The tracks on this screenshot, from top to bottom, are:

- oviraptor.vcf corresponds to lumpy calls on a BAM aligned to a hg38+HPV18 combined reference
- gridss.vcf.gz are GRIDSS calls on a hg38-aligned BAM
- diploid_tumor-ready.bam is the BAM file used to run GRIDSS.

<img width="1440" alt="Screen Shot 2020-08-15 at 11 09 27" src="https://user-images.githubusercontent.com/1575412/90302226-0e2f9600-dee8-11ea-8fbd-5f44cd71ccf1.png">

It shouldn't be the maxcoverage option as it defaults to 50k, but the coverage in the region is around 5k. Shouldn't be the blacklist - I used a new ENCODE one and this site doesn't overlap it.

The command I used was:

```
gridss --reference hg38.fa --output hg38-gridss.vcf.gz --assembly assembly.bam --threads 8 --workingdir work --blacklist encode4_unified_blacklist.bed.gz  hg38-bwa.bam
```

Happy to slice and share portions of the BAM that would be helpful to debug this. Unless it's a user error that I can't see again :)

Vlad

**Comment by d-cameron** [comment]
A copy of the input.bam.gridss.working directory with the sv.bam file sliced to the region of interest (+- 2kb) would be great.

What's the assembly.bam look like?

**Comment by vladsaveliev** [comment]
Attached the working directory with a sliced sv bam: [diploid_tumor-ready.bam.gridss.working.zip](https://github.com/PapenfussLab/gridss/files/5080291/diploid_tumor-ready.bam.gridss.working.zip)

The assembly BAM doesn't have anything overlapping this site. Here I added the sv.bam and the assembly.bam as the bottom 2 tracks: 

<img width="1440" alt="Screen Shot 2020-08-16 at 19 02 13" src="https://user-images.githubusercontent.com/1575412/90330839-36f08200-dff3-11ea-9071-ce739334dd93.png">

**Comment by d-cameron** [comment]
Sorry this took too long to look at. The problem is that coverage was so high that that region hit the assembly graph complexity threshold and was excluded from assembly.

You can see this in the assembly.bam.excluded_0.bam file in the assembly working directory.
```
track name="excludedDueToGraphComplexity" description="excludedDueToGraphComplexity" useScore=0
chr8    127289577       127292059
```

To assemble in regions of high coverage, the GRIDSS assembly thresholds need to be relaxed. VIRUSBreakend, which has to handle 1000x+ coverage viral genomes, uses the following assembly overrides for it's configuration file:
```
assembly.downsample.acceptDensityPortion = 5
assembly.downsample.targetEvidenceDensity = 50
assembly.positional.maximumNodeDensity = 100
assembly.positional.safetyModePathCountThreshold = 250000
assembly.positional.safetyModeContigsToCall = 12
```
