### ISSUE TITLE
AsyncBufferedIterator delays exception when it is occurs in a empty buffer.

### ISSUE THREAD

**Issue by dlopez-bioinfo** [PapenfussLab/gridss#389]
Hi,
I'm trying to call SVs on some CRAM files from the 1000 genomes project but it seems it is not working.
```bash
ID="NA18951"
CRAM_FILE="NA18951.final.cram"  # downloaded from ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239400/NA18951.final.cram
CRAI_FILE="NA18951.final.cram.crai"  # downloaded from ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239400/NA18951.final.cram.crai
REF="GRCh38_full_analysis_set_plus_decoy_hla.fa"  # downloaded from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa

gridss.sh -r ${REF} -o ${ID}.vcf -a ${ID}.assembly.bam -t 8 --jar gridss-2.9.4-gridss-jar-with-dependencies.jar --labels ${ID} ${CRAM_FILE}
```

First attempt failed at `CollectInsertSizeMetrics` step. The log shows there was a problem with the CRAI file, so I deleted it and created it again with samtools:
```bash
rm ${CRAI_FILE} && samtools index -@ 64 ${CRAM_FILE}
```

This time GRIDSS ended without any error, but the VCF file were empty.

> gridss v2.9.4
> samtools v1.9
> R v3.6.2
> bwa v0.7.16a-r1181

**Comment by d-cameron** [comment]
Please attach the gridss full log file to this issue

**Comment by d-cameron** [comment]
Reproduced locally and fix will be included in next release. The underlying issue was the lack of a reference genome being passed to the metrics calculations and htsjdk ignoring the passed via system defines.

In the meantime, the workaround is to convert to bam, then run GRIDSS.
