### ISSUE TITLE
Issues with repeatmasker and viral annotation

### ISSUE THREAD

**Issue by alhafidzhamdan** [PapenfussLab/gridss#393]
Hi there,

I ran GRIDSS with this command:

```
$GRIDDS \
    --reference $REFERENCE \
    --output $GRIDSS_RAW \
    --assembly $ASSEMBLY \
    --jvmheap 32g \
    --workingdir $WORKING_DIR \
    --blacklist $ENCODE_BLACKLIST \
    --repeatmaskerbed $REPEAT_MASKER \
    --jar $GRIDDS_JAR \
    --steps All \
    --maxcoverage 50000 \
    --labels ${PATIENT_ID}N,${PATIENT_ID}T \
    $ALIGNED_BAM_FILE_NORMAL $ALIGNED_BAM_FILE_TUMOR

```
And as you can see above I have included -repeatmaskerbed option.
Do I need to re-run this after GRIDSS calling ? using 
```
java -Xmx3g -cp $GRIDSS_JAR gridss.AnnotateInsertedSequence \
				REFERENCE_SEQUENCE=$reference \
				INPUT=$raw_gridss_output \
				OUTPUT=$annotated_gridss_output \
				WORKER_THREADS=$threads \
				ALIGNMENT=REPLACE \
				REPEAT_MASKER_BED=hg19.fa.out.bed 
```

And I've had problems with trying to do viral annotation. My command is

```
java -Xmx6g -cp $GRIDSS_JAR gridss.AnnotateInsertedSequence \
    REFERENCE_SEQUENCE=$VIRAL_GENOME \
    INPUT=$GRIDSS_RAW \
    OUTPUT=$GRIDSS_RAW_VIRAL_ANNOTATED \
    WORKER_THREADS=8 \
    ALIGNMENT=APPEND
```
With $VIRAL_GENOME pointing to a fasta file generated as per https://github.com/hartwigmedical/scripts/tree/master/virus

The error is :
```
Error: Could not find or load main class REFERENCE_SEQUENCE=.exports.igmm.eddie.resources.viralgenome.human_virus.fa
Caused by: java.lang.ClassNotFoundException: REFERENCE_SEQUENCE=.exports.igmm.eddie.resources.viralgenome.human_virus.fa

```

I am not sure what is causing both errors.
And if repeatmasker annotation needs to be repeated if already included at the initial GRIDSS calling stage.

**Comment by DarioS** [comment]
Good question. I wasn't aware that the GRIDSS driver script even had such an option.

**Comment by d-cameron** [comment]
>Error: Could not find or load main class

Looks like your `GRIDSS_JAR` environment variable isn't set so it's treating gridss.AnnotateInsertedSequence as the `CLASSPATH` and `REFERENCE_SEQUENCE=$VIRAL_GENOME` as the main entry point.

**Comment by d-cameron** [comment]
FYI: I've been working on a proper viral integration detection utility over the last few months.

If you're interested in beta testing, it's available in [dev branch]/scripts/virusbreakend.sh. I'm currently doing cohort validation on the Hartwig cervical and liver samples.

In related news, the next release will include `gridss.AnnotateVariantsRepeatMasker` `gridss.AnnotateVariantsKraken` utilities that will annotate inserted sequence. See #380 for a RepeatMasker annotation example.
