### ISSUE TITLE
Virus Database Creation Error

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#398]
The instructions state

> Run virusbreakend-build.sh virusbreakenddb to download and generate the reference data.

But that causes an error

```
$ scripts/virusbreakend-build.sh virusbreakenddb
scripts/virusbreakend-build.sh: line 28: virusbreakenddb: unbound variable
```

Looking inside the script, the variable seems to be `dbname` and hard-coded to the string `virusbreakenddb`.

```
dbname=virusbreakenddb
```

but later in the file, it's treated as a variable rather than a string: `[--db $virusbreakenddb]`.

**Comment by d-cameron** [comment]
Be aware that internal call to `kraken2-build` might fail unless you do the `chmod` work-around I outlined here:
https://github.com/DerrickWood/kraken2/issues/318
