### ISSUE TITLE
Virus Database Creation Output Directory Should Be Customisable

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#399]
On HPC systems, the convention is to only allow 10 GB in the backed-up user home directory and many terabytes in the scratch directory which may be emptied regularly by the system administrator. Currently, it seems that the database creation simply puts all files into the virusbreakenddb sub-directory. Having gridss in `~/software/`, I quickly hit the limit:

```
Downloading taxonomy tree data... done.
Uncompressing taxonomy data...
gzip: nucl_gb.accession2taxid: Disk quota exceeded
"kraken2-build --download-taxonomy --db $dbname" command completed with exit code 1.
```
Specifying a full path such as `./virusbreakend-build.sh /scratch/hm82/Reference/viralForKraken/` still seems to be putting large files into the home directory and reaching the quota. It looks like it's hard-coded `dbname=virusbreakenddb`.

**Comment by d-cameron** [comment]
I'm not able to reproduce this locally.

> It looks like it's hard-coded dbname=virusbreakenddb

That's just the default value, it gets updated to the value specified on the command-line on line 46.

> still seems to be putting large files into the home directory and reaching the quota

My guess is kraken is writing some temp files to locations outside the db path. Does it run if your working directory is on scratch? Does the following work?

```
cd /scratch/hm82/Reference/
~/virusbreakend-build.sh viralForKraken
```

**Comment by DarioS** [comment]
Ah, it's a small mistake in the instructions:

> Run `virusbreakend-build.sh virusbreakenddb` to download and generate the reference data.

There is a missing `--db` in the user guide example and so the value is not taken as the database name by the `case` statement. No more disk space errors if I specify the --db part. I will leave this issue open as a reminder to fix the example.

**Comment by DarioS** [comment]
It's worth mentioning in the user guide that the database build process takes a long time and needs quite a bit of memory. It easily reaches the 4 GB RAM limit on a HPC login node and needs to be submitted to a queue with lots more RAM.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3179343 ds6924    20   0 5784880   3.9g   2712 R  39.4   1.6   5:12.72 build_db
```
