### ISSUE TITLE
 No pair-end insert size metrics found

### ISSUE THREAD

**Issue by JFS31** [PapenfussLab/gridss#40]
Hello Mr. Cameron, 

as requested on BioStars here is the metrics-instertsize.txt file. I hope it will help you but I doubt that it is that informative. There is not much in there but maybe its just uniformative for me. Thanks for the help. 

Best, 
Julian 

[G507_UDG.combined_rmdup.sorted.idsv.metrics.insertsize.txt](https://github.com/PapenfussLab/gridss/files/557868/G507_UDG.combined_rmdup.sorted.idsv.metrics.insertsize.txt)

**Comment by d-cameron** [comment]
Thanks for that. It looks like when there is no paired read data at all then I'm unnecessarily raising an error that the reads are not in FR orientation.

What do you do with the read pairs that you aren't able to merge into a longer read? Do you get any of these at all?

**Comment by JFS31** [comment]
The read pairs that are not merged are left as unmerged read pairs. For example in this file 13% consist of unmerged read pairs.
