### ISSUE TITLE
VIRUSBreakend Database Folder or Archive

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#400]
The end of the build tries to put all of the files into an archive:

```
tar -czvf virusbreakend.db.$dbname.tar.gz \
	$dbname/*.k2d \
	$dbname/taxonomy/nodes.dmp \
	$dbname/virushostdb.tsv \
	$dbname/library/viral/*.fna* \
	$dbname/library/added/*.fna* \
```

It looks like `dbname` should not be an absolute path, although the code preceding it allows it to be used in that way.

```
tar (child): virusbreakend.db./verona/nobackup/dario/HeadNeck/viralForKraken/.tar.gz: Cannot open: No such file or directory
```

 Looking at the virusbreakend.sh itself, the archive doesn't seem to be used at all and `--kraken2db` seems to be a path to a folder of items. Is the archive used for anything or left-over code from an old pipeline design?

**Comment by d-cameron** [comment]
If you have the build directory, then that'll work fine but it's more that twice the size of the minimal subset required by VIRUSBreakend.

The .tar.gz contains just the files actually required by VIRUSbreakend.

**Comment by DarioS** [comment]
I don't see an input to specify the full path to the archive. but it seems to require individual files specified via multiple parameters.

**Comment by d-cameron** [comment]
It's designed as a redistribution package. The archive needs to be decompressed before it's usable.

1. Run `virusbreakend-build.sh` on an internet-enabled build machine with high enough specs to build the kraken index
2. Copy the .tar.gz to your protected HPC environment
3. Decompress on your HPC file system
4. Run `virusbreakend-sh` with `--kraken2db` set to the location of decompressed directory. Virusbreakend will now run without any internet connectivity.

It sounds like I should just replace various virusbreakend db paths with a single `--db` option - they're all handled by the build script now.
