### ISSUE TITLE
Annotate Kraken Fails GC Limit if VCF Contains Multiple Cancer Samples

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#407]
It looks like an extremely small amout of RAM is permitted for the annotation stage

```
java -Xmx128m $jvm_args -cp $gridss_jar gridss.kraken.AnnotateVariantsKraken
```

The overall RAM usage doesn't get close to the computing node limit

```
Mem requested:     64.0GB
     Mem used:     10.5GB
```

it appears to cause failures if four or more samples per patient are processed

```
[Sun Sep 27 02:53:54 AEST 2020] gridss.kraken.AnnotateVariantsKraken done. Elapsed time: 110.70 minutes.
Runtime.totalMemory()=81264640
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
```

For the executions with only a pair of samples per patient, I see successes

```
[Sat Sep 26 14:55:24 AEST 2020] gridss.InsertedSequencesToFasta done. Elapsed time: 3.07 minutes.
Runtime.totalMemory()=66584576
577305 sequences (49.11 Mbp) processed in 200.017s (173.2 Kseq/m, 14.73 Mbp/m).
  56933 sequences classified (9.86%)
  520372 sequences unclassified (90.14%)
[Sat Sep 26 14:56:26 AEST 2020] gridss.kraken.AnnotateVariantsKraken done. Elapsed time: 4.10 minutes.
Runtime.totalMemory()=119537664
```

The memory limit explains why the run time blew out to almost 2 hours compared to 4 minutes for a normal-tumour sample pair. Could viral annotation be made more robust to different experimental designs?

**Comment by d-cameron** [comment]
> the run time blew out to almost 2 hours compared to 4 minutes

Java is really bad at actually dying when it's OOM. It'll stall for a long time with 99%+ of CPU spend doing GC before it actually decides to die.
