### ISSUE TITLE
Fatal exception thrown by worker thread

### ISSUE THREAD

**Issue by yeroslaviz** [PapenfussLab/gridss#413]
Hi,
 sorry for the ominous title, but I can't define the error better, as this is the error I get:

```
[Thu Oct 15 14:35:04 CEST 2020] gridss.analysis.CollectGridssMetrics done. Elapsed time: 11.42 minutes.
Runtime.totalMemory()=5961678848
ERROR   2020-10-15 14:35:05     CallVariants    GRIDSS currently supports only FR read pair orientation. If usage with other read pair orientations is required, please raise an enchancement request at https://github.com/PapenfussLab/gridss/issues
ERROR   2020-10-15 14:35:05     CallVariants    Fatal exception thrown by worker thread.
java.lang.RuntimeException: GRIDSS currently supports only FR read pair orientation. If usage with other read pair orientations is required, please raise an enchancement request at https://github.com/PapenfussLab/gridss/issues
        at gridss.CallVariants$1$1.call(CallVariants.java:58)
        at gridss.CallVariants$1$1.call(CallVariants.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I'm not really sure what to do here, as I don't define any directionality in the reads/mappings. The reads were mapped using bwa with the following commands

```
bwa mem -t 13 $Comb_b $fastq1 $fastq2 | samtools sort -@13 -O BAM -o combined.sorted.bam -
samtools index combined.sorted.bam
```

any ideas?

thanks

**Comment by d-cameron** [comment]
Are you using a mate pair library?

If you can attach the insert size metrics file found in the .gridss.working for the input bam then I give you more details.

**Comment by yeroslaviz** [comment]
ok,
 forget it I think I have found the problem. I have mapped the read1 file only, but twice 👎 

```
fastq1="F245.conc.R1.fastq.gz"
fastq2="F245.conc.R1.fastq.gz"

bwa mem -t 13 $genome $fastq1 $fastq2 | samtools sort -@13 -O BAM -o Tgu.sorted.bam -
samtools index Tgu.sorted.bam
```

I'm keeping it open until I re-run the mapping and then `gridss`. I'll report afterwards.

**Comment by yeroslaviz** [comment]
ok, so it works now. Sorry about the confusion. 

I have a different question though.

If I expect, that only part of the transgenic sequence will be integrated to the genome of interest (Only part of the plasmid injected into the cell should be integrated), is it ok to attach the whole sequence of the plasmid, or would be better (or even a Must) to add only the part of the transgene, which is also integrated into the genome?

thanks

**Comment by d-cameron** [comment]
I recommend using the host genome + full plasmid sequence as your reference genome. This approach allows you to validate that only the intended sequence was inserted.

Whenever I've done transgene analysis, I've also done manual inspection of the coverage and of all breakpoints in the plasmid sequence. I'm yet to have a colleague actually give me the full, correct sequence for the transgene they've inserted. One had PhiX sequence in there that they didn't tell me about (look for GRIDSS single breakend calls on the plasmid reference then BLAST the breakend sequence to see what the sequence is that's not in your reference). Another gave me the full sequence of a gene (including introns), when they'd actually inserted a transcript so I had to follow all the exon juctions (breakpoint from plasmid reference to plasmid reference) to make sure it was fully intact. Yet another had multiple copies inserted in tandem (DUP-like breakpoint or circularisation breakpoint in the plasmid with plasmid coverage higher than expected compared to the host genome (one would expect 50% lower coverage of the plasmid if the host is diploid).
