### ISSUE TITLE
Workflow confusion

### ISSUE THREAD

**Issue by alhafidzhamdan** [PapenfussLab/gridss#414]
Hi there,

I'm testing GRISS v2.10.
I'm confused as to what are the steps to actually get a final VCF file i can use with LINX.
Is it 
`gridss.sh -> gridss_annotate_vcf_repeatmasker.sh -> GRIPSS -> LINX?`
or 
`gridss.sh -> gridss_annotate_vcf_repeatmasker.sh -> virusbreakend.sh -> GRIPSS -> LINX?`

If it's the latter then according to the readme of virusbreakend.sh there is no way to input a RepeatMasker annotated VCF into virusbreakend.sh. GRIPSS requires both repeatmasker and viral annotations.

https://github.com/hartwigmedical/hmftools/issues/116

What about gridss_somatic_filter.R ?

Could you please, when you have time, update your readme page to give us a clear workflow as to what is currently the best way to generate a final annotate SV file from GRIDSS?

Btw I found that the best way to use RepeatMasker is to use the conda version- one needs to set the server to RMBlast, using perl ./configure

Many thanks in advance, and thank you for your work in improving GRIDSS.

**Comment by DarioS** [comment]
Don't forget about gridss_annotate_vcf_kraken2.sh ! virusbreakend.sh is optional.

**Comment by d-cameron** [comment]
`gridss.sh`: general purpose SV caller: BAM -> VCF (reference genome <-> reference genome)
`virusbreakend.sh`: specialised viral integration caller: BAM -> VCF (reference genome <-> viral sequence)

>there is no way to input a VCF into virusbreakend.sh

It's a separate program.

> I'm confused as to what are the steps to actually get a final VCF file i can use with LINX.
> gridss.sh -> gridss_annotate_vcf_repeatmasker.sh -> GRIPSS -> LINX?

> gridss.sh -> GRIPSS -> gridss_annotate_vcf_repeatmasker.sh -> PURPLE -> LINX?

We're working on a new docker and driver script to help simplify usage of combined pipeline


Leaving this issue open until I update the readme and/or make other clarifying changes

**Comment by alhafidzhamdan** [comment]
Thanks, this seems to work ->
`gridss.sh -> GRIPSS -> gridss_annotate_vcf_repeatmasker.sh -> PURPLE -> LINX`
Without viral annotations despite what GRIPSS suggested.
Thanks again.

**Comment by DarioS** [comment]
I do RepeatMasker and Kraken2 annotation before GRIPSS successfully. Who knows which is better.
