### ISSUE TITLE
VAF Small Event Calculation NaN Results

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#417]
I use the following code to calculate VAF of retrotransposons in normal samples to try to pick anything that's closer to VAF 0.5 than to zero, so variants that are at least heterozygous and possibly homozygous are retained.

```r
library(VariantAnnotation)
variants <- readVcf(VCF)
keep <- grepl("LINE/L1|Alu|SVA", info(variants)[["INSRMRC"]]) & qual(variants) > 1000
variants <- variants[keep]
keep <- (geno(variants)[["VF"]][, 1] / (geno(variants)[["VF"]][, 1] + geno(variants)[["REF"]][, 1])) > 0.25
variants[keep] # Error: logical subscript contains NAs
```

However, the ratio that is calculated is sometimes NaN because both VF and REF are 0, so 0/0 is NaN.

```r
> geno(variants)[["VF"]]["gridss9f_22992b", ]
OSCC_1-N OSCC_1-P 
       0        0 
> geno(variants)[["REF"]]["gridss9f_22992b", ]
OSCC_1-N OSCC_1-P 
       0        0
```

The problem seems to happen for about 1 in every 100 such variants.

**Comment by d-cameron** [comment]
Sounds like homozygous single breakend variants. Single breakends use BVF.

Any reason the VAF function in libgridss.R isn't suitable for your purposes?

**Comment by DarioS** [comment]
Ah, I suppose that you are referring to gridss_be_af. Now I know about it, I will make use of it. It looks like `includeRefPair=rep(TRUE, length(gr))` is hard-coded inside the function, but the [Wiki](https://github.com/PapenfussLab/gridss/wiki/GRIDSS-Documentation#calculating-variant-allele-fraction-vaf) explains that REFPAIR shouldn't be included for the calculation of short events. To my mind, a breakend like a retrotransposon insertion is a short event. Have I misunderstood something? Secondly, what needs be be specified for `gr` and `vcf`?

**Comment by d-cameron** [comment]
A single breakend has an unknown length since the location of the other
side is unknown.

**Comment by d-cameron** [comment]
> like a retrotransposon insertion is a short event

Retrotransposons have a donor elements which are long enough to align to the reference genome. They won't be called as insertion events. What you'll see are two breaks in opposite orientations at the insertion site with a (usually) polyA single breakend or breakpoint to donor element on one side, and a breakpoint to the donor element or single breakend containing LINE sequence on the other side. You'd also need to handle 3' transduction as well as multi-break scenarios in which the insertion is not clean.

Here is a summary of how LINX classifies LINE insertions: https://github.com/hartwigmedical/hmftools/blob/master/sv-linx/README.md#identification-of-suspected-line-source-elements

**Comment by DarioS** [comment]
So, it's actually quite complicated. My main goal is to subset the VCF to only those retrotransposons which are likely to be germline / non-reference ones. Re-reading Tingting's question and your answer, I suppose you were recommending to use the sample-wise QUAL for this. I overlooked that and was just thinking about the variant-wise QUAL. Is that still the best approach these days?

**Comment by d-cameron** [comment]
I'm a bit unclear of what you're trying to do. Are you wanting a set of germline retrotransposon calls from a T/N paired sample? If that's the case, then you'd subset calls by normal QUAL score then identify the retrotransposon. The latter is messy since LINX doesn't yet do germline classification so we don't currently have a nice pretty tool to spit out your results.

**Comment by DarioS** [comment]
Yes, explicitly calculating VAF is not my main goal, because it would probably be factored into the QUAL score, anyway. Some retrotransposons will only have one end identified while other will have both ends, so I guess the QUAL score threshold should also be different for both situations. I might begin by looking at different events in IGV and getting some ideas about with good thresholds for breakends and breakpoints might be and use those to do a simple VCF filtering myself. I guess that there will be a germline version of GRIPSS in future but this will have to do for now.
