### ISSUE TITLE
configure.ac:9: warning: AC_CONFIG_SUBDIRS: you should use literals

### ISSUE THREAD

**Issue by woshi0655** [PapenfussLab/gridss#418]
Hi , When I try to install the gridss, I got two errors, hope anyone can help me.  And they are:
1:  $ autoconf
configure.ac:9: warning: AC_CONFIG_SUBDIRS: you should use literals
../../lib/autoconf/status.m4:1093: AC_CONFIG_SUBDIRS is expanded from...
m4/ax_with_htslib.m4:55: AX_WITH_HTSLIB is expanded from...
configure.ac:9: the top level
2:  /public1/home/stu_ll/softinstall/conda/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: htslib/libhts.a(cram_io.o):cram_io.c:(.text+0x7cbe): more undefined references to `libdeflate_crc32' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:25: gridsstools] Error 1

![image](https://user-images.githubusercontent.com/29584533/97105704-efbff500-16f7-11eb-9865-6b402e510bd7.png)
![image](https://user-images.githubusercontent.com/29584533/97105711-fa7a8a00-16f7-11eb-985f-7ac3053d4908.png)

**Comment by d-cameron** [comment]
This is a library dependency issue - specifically a transitive dependency issue with htslib.

Can you sucessfully build htslib or samtools from source? If not, I recommend fixing you system libraries so you can build htslib and/or samtools and that should also resolve this gridss dependency issue.

Currently, `gridsstools` is only required for `VIRUSBreakend` and `gridss_extract_overlapping_fragments.sh`. If you want to do GRIDSS SV calling, you don't need to compile `gridsstools` and you can get away with ignoring this (for now).

**Comment by d-cameron** [comment]
If you have a conda environment, it strongly recommend either `conda install htslib` or `conda deactivate` when building `gridsstools`. I've encountered some weird compilation errors with a conda environment enabled that has only some of the required libraries.

**Comment by woshi0655** [comment]
Hi , Thank you for you reply. Yes, I fixed the problem when I deactivate the conda!
