### ISSUE TITLE
Adding GRIDSS to homebrew science

### ISSUE THREAD

**Issue by tseemann** [PapenfussLab/gridss#42]
I've added it:

https://github.com/Homebrew/homebrew-science/pull/4556

`brew install gridss`

**Comment by d-cameron** [comment]
Thanks. Is there anything I need to do to keep it in sync when I release a new version?

**Comment by d-cameron** [comment]
Using bioconda as the easy-install option.

**Comment by tseemann** [comment]
homebrew-science doesn't exist anymore, it's moved to `brewsci-bio`
