### ISSUE TITLE
Missing reference genome

### ISSUE THREAD

**Issue by kalexiou** [PapenfussLab/gridss#425]
Hi,

I am going crazy!

I have built gridss with singularity 

`export PATH=$PATH:/usr/sbin`
`singularity pull docker://gridss/gridss>`

and then run it with the following command

`singularity run gridss_latest.sif --reference /scratch/022-fragaria.ananassa-SNPdiscovery/olive/Olea_europaea_chromosome_unplaced_scaffolds.fa -o Olea17.vcf.gz -t 3 --assembly GRIDSS/gridss.assembly.01145_10FN19_A1_1_S5.bam Olea17_genes.bam  `

and always getting a `Missing reference genome /scratch/022-fragaria.ananassa-SNPdiscovery/olive/Olea_europaea_chromosome_unplaced_scaffolds.fa. Specify reference location using the --reference command line argument`

What's going on?

Thanks in advance
Kostas

**Comment by d-cameron** [comment]
You need to mount /scratch so it's visible inside your image. In docker
it's the -v parameter, not sure of what it is for singularity.

**Comment by kalexiou** [comment]
Problem solved. Thanks
