### ISSUE TITLE
LINE1 Assembled Variants Within Reference LINE1s

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#429]
I am manually viewing the GRIDSS structural variants to gain some familiarity with them. Sometimes, a structural variant that's annotated as `INSRMRC=LINE/L1` is actually within a reference genome's LINE1 element. Looking at the reference LINE1, it's only 2009 bases long, which means that it is a truncated LINE1 because the canonical full-length LINE1 is about 6000 bases long. Perhaps the insertion identified by GRIDSS is just a little extra sequence the person has compared to hg38's genome due to population diversity.

![image](https://user-images.githubusercontent.com/631218/99869849-54507000-2c22-11eb-8c32-445ab9ccc8ab.png)

Is special care necessary with these? It is also interesting that there seem to be two regions of soft-clipping and a third potential location for the insertion indicated by the purple 37, although there are no regions of homology in the reference genome (no CIPOS field for the variant's records). Could be two different alleles, both different to hg38 but in a very similar but slightly different location. I wonder if these are handled by LINX or more filtering needs to be done to remove these to short-list completely non-reference LINE1 sequences.

**Comment by DarioS** [comment]
It turns out that this happens quite often. as demonstrated by Pacific Biosciences long read sequencing.

[Identification and characterization of occult human-specific LINE-1 insertions using long-read sequencing technology](https://academic.oup.com/nar/article/48/3/1146/5680708), _Nucleic Acids Research_, 2020

To differentiate between different alleles in the human population (which appear as short inserts relative to the reference genome) and actual LINE1 insertions, the researchers require poly-A tail and TSD, which full-length LINE1s have. Truncated LINE1s, which might or might not have poly-A tail and TSD are not dealt with, probably because it's too difficult without the landmarks.

![image](https://user-images.githubusercontent.com/631218/101234805-b034f180-3716-11eb-978b-fd6453734ce9.png)

Source: [Annual Reviews of Genetics, 2014](https://www.annualreviews.org/doi/abs/10.1146/annurev-genet-120213-092412),

**Comment by d-cameron** [comment]
That looks like it's just a 37bp insertion (with respect to the reference). My best guess is that there's a 37bp intra-LINE DEL in the reference not present in the sample. Since 37bp is way too short to unambiguously place a LINE (and if my guess is true, it doesn't actually make sense to), the inserted correctly sequence gets an `INSRMRC=LINE/L1` label.

Although not particularly useful in this instance, it appears to be working as intended.

**Comment by d-cameron** [comment]
Determining underlying biology of the sequence is outside the scope of the `INSRM*` fields. The `INS` isn't making claim of biological interpretation, it's just a classification of the unplaced sequence at the break junction.
