### ISSUE TITLE
What is "ldsv" in the help?

### ISSUE THREAD

**Issue by tseemann** [PapenfussLab/gridss#43]
```
USAGE: Idsv [options]

Calls structural variations from one or more SAM/BAM input files.
Version: 0.11.7
```

**Comment by d-cameron** [comment]
GRIDSS is technically a software suite, but currently released version includes only the IDSV (IDentification of Structural Variant) entry point. I'll update the documentation in the next release which will modularise the pipeline into independently usable components (DP identification, split read identification, assembly) using only spec-defined SAM tags in intermediate files.

Hopefully this will encourage alternate implementation of various steps (eg Pindel split read identification, or CLEVER discordant read pair identification) that can be swapped out to generate new pipelines. One can dream.

**Comment by d-cameron** [comment]
namespace is now "gridss"
