### ISSUE TITLE
Per-sample presence/absence of breakpoints in joint calling

### ISSUE THREAD

**Issue by willhooper** [PapenfussLab/gridss#432]
Hi, 

I've performed somatic joint-calling on a handful of samples. Following filtering with `gridss_somatic_filter.R`, what per-sample QUAL score threshold do you recommend for determining whether a breakpoint is present in a given sample? 350 as listed [here](https://github.com/PapenfussLab/gridss/wiki/Somatic-Filtering)?

Should the QUAL scores be summed across each breakend in a pair? 

I ask because I'm seeing passing variants that have non-zero QUAL scores in my normal sample. 

Thanks!
Will

**Comment by d-cameron** [comment]
>I ask because I'm seeing passing variants that have non-zero QUAL scores in my normal sample.

By default, the somatic filter allows for a 3% contamination of the normal. This is to handle both biological (e.g. matched normal taken from adjacent tissue) as well as experimental contamination. In our experience, we find cross-contamination between barcodes and even between lanes on a flow cell so a highly amplified tumour SV will be present at a low level in every sample run on that same flow cell.

>Should the QUAL scores be summed across each breakend in a pair?

QUAL should be the same on both sides of a breakpoint. If this is not the case, please raise an issue.

>what per-sample QUAL score threshold do you recommend for determining whether a breakpoint is present in a given sample?

This depends very much on experimental design. For example, in our PDX experiments, we are looking at tumour evolution so the presence of a subclone even at a very low level is of interest. For related samples (e.g. primary+mets) we generally use a very low per-sample threshold. A high confidence call in one sample indicates the variant is likely real so if it's poorly supported in another same then we're much more confident in calling it as a subclonal SV than if we didn't find it in another sample.

**Comment by willhooper** [comment]
> For related samples (e.g. primary+mets) we generally use a very low per-sample threshold

This is almost always the case for our joint-calling analyses. For cases like this (with 80x tumor / 40x normal coverage), what would you use as a per-sample threshold?

**Comment by d-cameron** [comment]
The defaults are tuned for 40x normal/100x tumour so you should be fine with those.

Not that with that sort of data,, you may be interesting in running the entire Hartwig pipeline (https://www.hartwigmedicalfoundation.nl/en/it-pipeline/) as your data is pretty close to what it's been optimised for.

**Comment by willhooper** [comment]
Is the per-sample default 350, anything greater than 0, or some other value? 

We actually do run CHORD from time to time. 

Thanks again for your help!

**Comment by d-cameron** [comment]
>Is the per-sample default 350, anything greater than 0, or some other value?

By default, there's no per-sample minimum. It's 350 across all samples, with max of 3% of that from non-tumour samples.

> We actually do run CHORD from time to time.

LINX is quite useful for fusion detection as well as rearrangement event classification. It has some very good visualisation capabilities as well. https://www.biorxiv.org/content/10.1101/2020.12.03.410860v1
