### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by jeongmeani** [PapenfussLab/gridss#436]
Hi,

i'm intalling gridss but have some issue.

out of conda environment, i follow the install manual.
and run final cmd './configure && make all' 

it's out like this
i attach some of this

> Found 8 distinct read name in ../../../test/resources//extractFragmentsToFastq/in.sam.readnames.txt
>Found 1 paired records without mates. Treating as unpaired.
>Could not find primay alignment records for 2 read names.
>diff ../../../test/resources//extractFragmentsToFastq/in.sam.out.u.fq testExtractFragmentsToFastq.out.u.fq > >testExtractFragmentsToFastq.u.diff
>diff ../../../test/resources//extractFragmentsToFastq/in.sam.out.1.fq testExtractFragmentsToFastq.out.1.fq > >testExtractFragmentsToFastq.1.diff
>diff ../../../test/resources//extractFragmentsToFastq/in.sam.out.2.fq testExtractFragmentsToFastq.out.2.fq > >testExtractFragmentsToFastq.2.diff
>rm testExtractFragmentsToFastq.*
>./gridsstools extractFragmentsToBam \
>        -@ 16 \
>       -o testExtractFragmentsToBam.out.sam \
>        ../../../test/resources//extractFragmentsToFastq/in.sam.readnames.txt \
>        ../../../test/resources//extractFragmentsToFastq/in.sam
> Read 8 distinct read names
>diff ../../../test/resources//extractFragmentsToFastq/out.sam testExtractFragmentsToBam.out.sam > >testExtractFragmentsToBam.diff
>rm testExtractFragmentsToBam.*

is it correct to install it?

and i try running gridss.sh in script directory.
but i can't find gridss.jar file

can you give me some guide?

Best Regards

Jeongmin

**Comment by d-cameron** [comment]
GRIDSS is mostly written in Java - just download from https://github.com/PapenfussLab/gridss/releases


`gridsstools` recompilation is:
- Only required if the supplied `gridsstools` binary crashes on your system
- You want to run VIRUSBreakend. `gridsstools` is not (yet) required if using GRIDSS for assembly/SV calling
