### ISSUE TITLE
tag in assembly.bam

### ISSUE THREAD

**Issue by hastj7373** [PapenfussLab/gridss#439]
Hello. 

Could you please tell me what tag in *assembly.bam represents?

For exmaple, 

**aa:i**:1  
**sb:f**:0  
**ec:B:i**,0,0,0,0,0,0      
**ad:A**:b  
**oe:B:i**,180,218,218,218,180,218  
**dl:i**:151        
**eq:B:f**,26.1176,19.5013,21.1187,19.5013,26.1176,26.1176  
**os:B:i**,0,99,83,99,0,0   
**at:B:i**,0,0      
**et:B:c**,1,0,0,0,1,1

I would appreciate you if you could explain these tags to me. 

Best wishes,

**Comment by d-cameron** [comment]
Additional documtnation has been added to https://github.com/PapenfussLab/gridss/blob/dev/src/main/java/au/edu/wehi/idsv/sam/SamTags.java

Note that these are GRIDSS-internal tags not intended for downstream usage and may change in future GRIDSS releases.

**Comment by hastj7373** [comment]
Thanks for your comments.! (It's really understandable).

I have one more question regarding et (evidence type). 

It appears that et tag has only 1 or 0. 

What does 1 (or 0) represent?

Thanks again for your great effort.

**Comment by d-cameron** [comment]
See https://github.com/PapenfussLab/gridss/blob/27726c5611895a8624d54ad6d4060677f215a1fd/src/main/java/au/edu/wehi/idsv/AssemblyEvidenceSupport.java

```
    public enum SupportType {
        Read(0),
        ReadPair(1);
```
