### ISSUE TITLE
Seeking advice for FFPE calling

### ISSUE THREAD

**Issue by lkhilton** [PapenfussLab/gridss#440]
I'm running GRIDSS on some FFPE whole genomes, and in total it's creating temp files just from the preprocessing stage that are sometimes more than double the footprint of the original BAM file. This is due to a high rate of [split-read artifacts](https://academic.oup.com/nar/article/47/2/e12/5173669) in FFPE genomes. I've seen several genomes go through the pipeline and extract >50% of the original reads during this step of the pipeline. 

I'm currently using the default gridss config settings. Do you have any suggestions for what I could modify in the config that might reduce the number of "SV" reads being extracted from these genomes? 

Log file from a recent pre-processing run attached. 

[gridss.full.20210122_081753.n104.20761.log](https://github.com/PapenfussLab/gridss/files/5858973/gridss.full.20210122_081753.n104.20761.log)

**Comment by d-cameron** [comment]
Can you send through metrics files in the input.bam.gridss.working directory so I can see what the breakdown of the SV-supporting reads are? The linked article seems to put an upper limit of ~15% on those split read artifact but if >50% of reads are getting extracted then clearly there's something else going on as well.

**Comment by d-cameron** [comment]
v2.11.0 changes should have improved FFPE assembly performance. 

Note that if you haven't done read trimming and aren't using one of the 5 standard illumina adapters, the short read fragment length distribution of FFPE samples will have many reads containing adapter sequence and looking like SVs. GRIDSS auto-filters soft clipped reads starting with known adapter sequence but you might have different adapters.

**Comment by lkhilton** [comment]
Hi Daniel, my apologies for not responding to this back in January, I missed the notification for your response. I will eagerly test out v2.11.0 and let you know how it works for us, thanks for your help. 

I will ask our sequencing facility about non-standard adapters. As far as I know they do trim the adapter sequences from the reads, but if I'm wrong about that our hands are tied as we don't have the resources to duplicate the data if it hasn't been done. Some of these FFPE libraries really are quite low quality (e.g. archival biopsies from remote hospitals) so we are just trying to make the best of it. Despite the large temp file size we're happy with the performance of GRIDSS on these samples. 

Thanks again!
