### ISSUE TITLE
Feature request: Index output vcf files

### ISSUE THREAD

**Issue by alexiswl** [PapenfussLab/gridss#441]
Some downstream applications require/prefer gzipped/vcf files to be indexed. Would it be too much trouble to conclude the script with `tabix -p vcf` which will create the `.tbi` file? Dockerfile will also need to have tabix installed through apt-get.

Thank you

- Alexis

**Comment by d-cameron** [comment]
The latest GRIDSS version already does this - just specify a .vcf.gz output suffix and you should have a .tbi output as well.

(NB: due to release cycles differences, gridss-purple-linx is currently a few GRIDSS versions out of date)
