### ISSUE TITLE
Feature request: Null entrypoint docker tag for workflow language engines

### ISSUE THREAD

**Issue by alexiswl** [PapenfussLab/gridss#442]
Unfortunately, CWL doesn't respect Docker's ENTRYPOINT, or `--entrypoint` parameter. Although I've [attempted to suggest this is a useful feature](https://github.com/common-workflow-language/cwltool/issues/1270), I haven't much success convincing anyone.  

As such, in order to use gridss through CWL, a separate container must be made with the following entry:

```
FROM gridss/gridss:latest

ENTRYPOINT: []
```

Is there scope to either:

1. Change the usage of gridss to be:

    ```
    docker run -v... gridss/gridss:latest /opt/gridss/gridss.sh [gridss-arguments]
    ```

2. Have an alternative dockerfile `Dockerfile-cwl` which comprises the docker recipe noted above and uses `-cwl` as the tag suffix  
    * i.e `latest-cwl` or `2.9.4-cwl`

**Comment by d-cameron** [comment]
How's this generally handled by other dockerised tools in CWL workflows? This seems like a general docker+CWL issue so it would make sense for the same approach to be used by all tools affected by this (most of them?).

**Comment by alexiswl** [comment]
They have no entrypoint (or it's set to shell). Almost all tools referred to in CWL's [bio-cwl-tools](https://github.com/common-workflow-library/bio-cwl-tools) repo have a quay.io biocontainers image.  None of them set the entrypoint as suggested in item 4 in https://f1000research.com/articles/7-742/v2.  Another option is we could submit this as a tool to the biocontainers repo.

**Comment by alexiswl** [comment]
Closing, feature already resolved with biocontainers conda recipe:

```
$ docker inspect quay.io/biocontainers/gridss:2.10.2--0 | jq -r '.[] | .ContainerConfig.Entrypoint'
null
```
