### ISSUE TITLE
Realignment fastq files are written to incorrect directory

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#45]
The intermediate files are written relative to the current directory, not the WORKING_DIRECTORY specified on the command line.
Processing is still performed correctly but there is the potential for filename collisions

**Comment by JocelynSP** [comment]
Files in sub-directories in $pwd instead of $WORKING_DIR are those that end in 
bam.realign.0.bam, bam.realign.1.bam, bam.realign.[012].fq
