### ISSUE TITLE
Docker image doesn't support gridss_extract_overlapping_fragments script

### ISSUE THREAD

**Issue by alexiswl** [PapenfussLab/gridss#457]
There are a couple of issues with the latest docker build causing the `gridss_extract_overlapping_fragments` bash script to fail:

1. The bionic apt repository has the samtools version set to v1.7 yet v1.10 or higher is required
https://github.com/PapenfussLab/gridss/blob/010e6d950ecc45f444dbc4bb89198f41438d0387/scripts/gridss_extract_overlapping_fragments.sh#L213-L217

```bash
$ docker run -v $PWD:$PWD -w $PWD --entrypoint samtools gridss/gridss:latest --version
samtools 1.7
Using htslib 1.7-2
Copyright (C) 2018 Genome Research Ltd.
```

One solution could be migrating from Ubuntu Bionic (18.04) to Ubuntu Focal (20.04) which has samtools 1.10 installed.  

2. The R version is set to v3 but v4 is needed for the latest version of Bioconductor.  Without this, `v1.2.0` of the StructuralVariantAnnotation package is installed (linked to BiocConductor release 3.10, but `StructuralVariantAnnotation::breakpointRanges`  which doesn't support the `inferMissingBreakends` keyword argument.  

```bash
$ docker run -v $PWD:$PWD -w $PWD --entrypoint Rscript gridss/gridss:latest svannot.R
Error in .breakpointRanges(x, ...) :
  unused argument (inferMissingBreakends = TRUE)
Calls: <Anonymous> -> <Anonymous>
Execution halted
```

I don't think it's particularly easy to install R4 on Bionic, so this would be another incentive to upgrade Ubuntu.

**Comment by d-cameron** [comment]
Fixed in the updated docker. Thanks for your PRs - they've been very helpful.
