### ISSUE TITLE
Q: TAF meaning in VCF file?

### ISSUE THREAD

**Issue by hansolo-bioinfo** [PapenfussLab/gridss#464]
Could someone tells me what the meaning of this tag? I couldn't find the definition in VCFv4.2 Specification.

##INFO=<ID=TAF,Number=1,Type=Float,Description="Description">

Thank you.

**Comment by d-cameron** [comment]
Not generated by `gridss.sh`.

It means `Tumour Allele Fraction` and that description is present for `gridss_somatic_filter.R` generate files.

Did you use for GRIPSS to generate the VCF with the missing description?

**Comment by hansolo-bioinfo** [comment]
Yes, we are using GRIPSS for now and planning to use Purple in the future. This seems like an oversight and has been solved.

**Comment by d-cameron** [comment]
https://github.com/hartwigmedical/hmftools/issues/160
