### ISSUE TITLE
gridds fails to output VCF (Fatal error during breakpoint identification)

### ISSUE THREAD

**Issue by nitha26** [PapenfussLab/gridss#466]
Hi,

While I am running gridss for germlineSV calling for NA12878 samples with defaults values, getting an error as   "Fatal error during breakpoint identification" 
Attaching the error details here. How can I rectify this error? 
[gridss.txt](https://github.com/PapenfussLab/gridss/files/6069685/gridss.txt)

**Comment by DarioS** [comment]
Ah! University of Sydney's Informatics Hub isn't the only group using M.H.C. contigs as part of their reference genome.

```
INFO	2021-03-02 06:01:09	VariantCaller	Complete calling maximal cliques in chunk 3663 (HLA-DRB1*16:02:01:1-11005)
INFO	2021-03-02 06:01:09	VariantCaller	Complete calling maximal cliques in chunk 3659 (HLA-DRB1*15:01:01:04:1-11056)
```

I'm sure that Daniel loves handling all those asterisks, colons and hyphens in his code.

**Comment by ohofmann** [comment]
Heh. I'd argue most cancer initiatives care about calls in HLA/MHC regions. Don't blame the users, blame the genome reference consortium ;-)

But yes: in general, it's probably worthwhile to escape any and all names/strings throughout.

**Comment by DarioS** [comment]
Actually, [HLA nomenclature](https://www.ebi.ac.uk/ipd/imgt/hla/nomenclature/index.html) was "established by the HLA Informatics Group of the Anthony Nolan Research Institute in close collaboration with the European Bioinformatics Institute" in 2010. Let's not blame Genome Reference Consortium for its syntax.

**Comment by ohofmann** [comment]
I stand corrected. I take it we can still agree that tools should be able to handle standard nomenclature?

**Comment by nitha26** [comment]
I could not understand, the above discussions.
@d-cameron  could you please help me to rectify this error. This cell-line sample NA12878  was re-sequenced in our lab (NovaSeq) and aligned (BWA-mem) with GRCh38 reference. But still, I'am  getting  this error while running gridss.

**Comment by d-cameron** [comment]
The error log indicates the root cause is:
```
Caused by: java.lang.NumberFormatException: For input string: "50Q"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at au.edu.wehi.idsv.VcfBreakendSummary.<init>(VcfBreakendSummary.java:83)
```
I've traced `VcfBreakendSummary.java:83` throwing that error to the following commit:

https://github.com/PapenfussLab/gridss/commit/ba06bf9525189dacf129b5de94e279f50f02ef30#diff-988135bcc0a0e7c4e74ca9483cc7f4dcb8a10ecd0a01b4056016b9458674a7d7

Which means you're running a version of GRIDSS from before August 2017 (before version 1.4.2 which included the fix).

Please use a more recent version.
