### ISSUE TITLE
gene fusions were missed 

### ISSUE THREAD

**Issue by helloeoh001** [PapenfussLab/gridss#467]
Dear Dr. Cameron,

GRIDDSS (v2.8.3) missed a couple of gene fusions in lymphoma data which were very noisy with unidentifiable sequences at the end of many reads.
The number of supporting read of the true fusion genes (MYC-IGH, IGH-BCL2) were about  30~40 which are good enough for GRIDSS to detect in clean data.
The noisy sequences could disturb GRIDSS to detect the variants?
Are there any ways to detect the true fusion variants across the many false soft-clipped reads?

![image](https://user-images.githubusercontent.com/16658129/110056891-ed0a9600-7da2-11eb-8460-82db824ca6d7.png)

**Comment by d-cameron** [comment]
Is this fixed in the latest version? If no, are you able to supply the BAMs and/or VCFs for the 2kbp flanking both the MYC and IGH sites?
