### ISSUE TITLE
GRIDSS 2.9.4 and 2.10.2 sometimes have vastly different results when filtered by GRIPSS 1.10 (or 1.11)

### ISSUE THREAD

**Issue by toddajohnson** [PapenfussLab/gridss#469]
I processed 18 paired tumor/normal samples with both GRIDSS 2.9.4 and 2.10.2, followed by GRIPSS (and other components of the PURPLE-GRIDSS-LINX pipeline; using latest versions).  Most of the tumors had very few SVs, but PURPLE Circos plots for one tumor sample after GRIDSS 2.9.4 processing and displayed in LINX output numerous inter- and intra-chromosomal SVs and a CN>6 region on chr6 with an interesting pattern of complex events.
However, while the other tumors with small numbers of SVs looked the same in PURPLE Circos plots after GRIDSS 2.10.2 (and implementing the newer scripts for annotating with RM and VIRUSBreakend), that interesting tumor had no SVs that PASSed the GRIPSS filters. 

Below are row counts from the various VCFs for that tumor:
GRIDSS 2.9.4 unfiltered VCF | 607222
GRIDSS 2.10.2 unfiltered VCF | 608255
GRIDSS 2.9.4: GRIPPS somatic VCF | 32223
GRIDSS 2.10.2: GRIPPS somatic VCF | 668
GRIDSS 2.9.4: GRIPPS somatic filtered VCF | 226
GRIDSS 2.10.2: GRIPPS somatic filtered VCF | 0

GRIPSS filtering of that tumor's GRIDSS 2.9.4 VCF yielded 226 rows but 0 from the 2.10.2 VCF.  Also, notably, none of the 221 events that GRIDSS 2.9.4 labeled as PASS even made it into the GRIPPS 2.10.2 somatic VCF.

The only difference that I could see between the VCFs (besides additional "INSRM" and "INSTAXID" fields) was that the VF field had differing values for the 226 events that GRIPSS passed in the 2.9.4 run.  For those 226 events, the mean/max VF values were 48.29/118 and 89.96/221 in the unfiltered GRIDSS 2.9.4 and 2.10.2 VCFs, respectively. 

I am wondering if GRIDSS' calculation of the number of supporting fragments changed, and if that may now exceed some built-in VF filter in GRIPSS?  I searched through the GRIPSS code but did not see where it would filter on VF.

Thanks for any help that you could provide!
Todd

**Comment by d-cameron** [comment]
There's a known issue (fixed in dev) with 2.10.x filter out shorter soft clipped support. This will change `VF` but the change shouldn't be as extreme as you've found. I'm doing final regression testing on v2.11.0 in preparation for a release so the fix for this should be available within a few days.

The release notes don't include any changes that will directly change GRIPSS results (e.g. field renaming) but we haven't done internal regression/validation of GRIPSS with 2.10.x. What's the sample filtering difference if you use `gridss_somatic_filter.R` for somatic filtering instead of GRIPSS?

>the VF field had differing values for the 226 events that GRIPSS passed in the 2.9.4 run

What's the VF difference being driven by? Are SR, ASSR, ASRP, & RP also very different or only a subset of those fields? 

> For those 226 events, the mean/max VF values were 48.29/118 and 89.96/221

Could you sanity check that GRIDSS was using appropriate inputs? Did you change the sample ordering between the two runs? Were they run in different working directories (GRIDSS will reuse intermediate results in the .gridss.working directories if it finds them). Are REF and REFPAIR consistent between the two VCF?

**Comment by d-cameron** [comment]
>besides additional "INSRM" and "INSTAXID" fields

Actually populated fields, or just the presence of a header? These fields are written directly by `gridss.sh` but instead by the VCF post-processing tools `gridss_annotate_*.R`. If fields are populated in one and not the other that means that the steps between `gridss.sh` and GRIPSS are different in the two runs.

**Comment by toddajohnson** [comment]
> > besides additional "INSRM" and "INSTAXID" fields

For the GRIDSS 2.9.4 runs, the annotation of events that mapped to mobile elements and viral sequences was done with  the standalone PURPLE-GRIDSS-LINX 1.3.2 script, so RepeatMasker annotation was performed within gridss.sh with the passed argument for --repeatmaskerbed, and then viral annotation with the call to gridss.AnnotateInsertedSequence.
For GRIDSS 2.10.2 run, --repeatmaskerbed is no longer an allowed argument, so I modified the standalone PGL by removing that --repeatmaskerbed line from the gridss.sh call and and then performed the RM and viral annotation with:
`if [[ ! -f $gridss_kraken2_vcf ]] ; then
	write_status "Running GRIDSS VIRUSBreakend Annotation"
	
	$install_dir/gridss/gridss_annotate_vcf_kraken2.sh \
		-o ${gridss_kraken2_vcf} \
		-j ${gridss_jar} \
		-t $threads \
		--kraken2db ${virusbreakenddb} \
		${gridss_driver_vcf}
	if [[ ! -f $gridss_kraken2_vcf ]] ; then
		write_status "Error creating $gridss_kraken2_vcf. Aborting" 1>&2
		exit 1
	fi
else
	write_status "Skipping GRIDSS Kraken2 Viral Annotation = ${gridss_kraken2_vcf} exists"
fi

if [[ ! -f $gridss_unfiltered_vcf ]] ; then
	write_status "Running GRIDSS RepeatMasker Annotation"
	
	$install_dir/gridss/gridss_annotate_vcf_repeatmasker.sh \
		-o ${gridss_unfiltered_vcf} \
		-w ${gridss_dir} \
		-j ${gridss_jar} \
		-t $threads \
		${gridss_kraken2_vcf}
	if [[ ! -f $gridss_unfiltered_vcf ]] ; then
		write_status "Error creating $gridss_unfiltered_vcf. Aborting" 1>&2
		exit 1
	fi
else
	write_status "Skipping GRIDSS RepeatMasker Annotations = ${gridss_unfiltered_vcf} exists"
fi`

**Comment by toddajohnson** [comment]
>  The release notes don't include any changes that will directly change GRIPSS results (e.g. field renaming) but we haven't done internal regression/validation of GRIPSS with 2.10.x. What's the sample filtering difference if you use `gridss_somatic_filter.R` for somatic filtering instead of GRIPSS?

I ran gridss_somatic_filter.R, but it failed with the following:

2021-03-11 17:22:21 Loading from cache  /home/tjohnson/reference/HMF_GRCh38/dbs/gridss_pon//gridss_pon_breakpoint.bedpe.cached.parsed.rds
Warning message:
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr1_GL383518v1_alt, chr1_GL383519v1_alt, chr1_GL383520v2_alt, chr1_KI270759v1_alt, chr1_KI270760v1_alt, chr1_KI270761v1_alt, chr1_KI270762v1_alt, chr1_KI270763v1_alt, chr1_KI270764v1_alt, chr1_KI270765v1_alt, chr1_KI270766v1_alt, chr1_KI270892v1_alt, chr2_GL383521v1_alt, chr2_GL383522v1_alt, chr2_GL582966v2_alt, chr2_KI270767v1_alt, chr2_KI270768v1_alt, chr2_KI270769v1_alt, chr2_KI270770v1_alt, chr2_KI270771v1_alt, chr2_KI270772v1_alt, chr2_KI270773v1_alt, chr2_KI270774v1_alt, chr2_KI270775v1_alt, chr2_KI270776v1_alt, chr2_KI270893v1_alt, chr2_KI270894v1_alt, chr3_GL383526v1_alt, chr3_JH636055v2_alt, chr3_KI270777v1_alt, chr3_KI270778v1_alt, chr3_KI270779v1_alt, chr3_KI270780v1_alt, chr3_KI270781v1_alt, chr3_KI270782v1_alt, chr3_KI270783v1_alt, chr3_KI270784v1_alt, chr3_KI270895v1_alt, chr3_KI270924v1_alt, chr3_KI270934v1_alt, chr3_KI270935v1_alt, chr3_KI270936v1_alt, chr3_KI270937v1_alt, chr4_GL000257v2_ [... truncated]
2021-03-11 17:23:04 Calculating transitive links /home/tjohnson/workspace/runs/BHD_WGS_HMF_20210201/result/GRIDSS/D-BHD-F107-T1/gridss/D-BHD-F107T.gridss.unfiltered.vcf.gz
Error: Faceting variables must have at least one value
Backtrace:
     █
  1. └─ggplot2::ggsave(...)
  2.   ├─grid::grid.draw(plot)
  3.   └─ggplot2:::grid.draw.ggplot(plot)
  4.     ├─base::print(x)
  5.     └─ggplot2:::print.ggplot(x)
  6.       ├─ggplot2::ggplot_build(x)
  7.       └─ggplot2:::ggplot_build.ggplot(x)
  8.         └─layout$setup(data, plot$data, plot$plot_env)
  9.           └─ggplot2:::f(..., self = self)
 10.             └─self$facet$compute_layout(data, self$facet_params)
 11.               └─ggplot2:::f(...)
 12.                 ├─ggplot2:::unrowname(...)
 13.                 │ └─base::is.data.frame(x)
 14.                 └─ggplot2::combine_vars(data, params$plot_env, vars, drop = params$drop)

**Comment by toddajohnson** [comment]
> What's the VF difference being driven by? Are SR, ASSR, ASRP, & RP also very different or only a subset of those fields?
That was my question to you...  In those 226 rows, there were no differences for SR, ASSR, ASRP, or RP value.  If you look across the unfiltered GRIDSS VCFs, most match across all of those fields as well as for VF, but about 10% match those fields, but not the VF field, and a very few mismatch across various field.
I plotted the VF values from the GRIDSS 2.9.4 and 2.10.2 unfiltered VCFs (post RM and viral annotations) for those 226 GRIPPS passed events:
![gridss 2 9 vs 2 10 VF PASSED](https://user-images.githubusercontent.com/17885404/110770223-6a02a780-829c-11eb-9fbb-ef8cc729588d.png)

Then, I plotted values for all 580079 unfiltered events (matching on CHROM, POS, REF, ALT, EVENT).  It looks like a straight unit line without restricting x and y axes, but setting the max values to 500 on the x-axis shows that some points (n=52543) lie above the unit line.  Plotting the values from the driver.vcf files (before annotation) looks the same. Also, the GRIDSS 2.9.4 run was done in a separate directory from the 2.10.2 run.
![gridss 2 9 vs 2 10 VF unfilt](https://user-images.githubusercontent.com/17885404/110770255-75ee6980-829c-11eb-879c-41d0a5fef67e.png)

**Comment by toddajohnson** [comment]
Daniel,
gridss_somatic_filter.R ran fine on the GRIDSS 2.9.4 processed file, so I then went through the R code interactively with both VCF files to see where they diverged.  The change came after:
full_vcf = raw_vcf[geno(raw_vcf)$QUAL[,normalordinal] / VariantAnnotation::fixed(raw_vcf)$QUAL < 4 * gridss.allowable_normal_contamination]

So, I then pulled one of the EVENTS that had PASSED in the high CN chr6 region and printed out the geno information.  While the 2.9.4 version had no VF or QUAL values for the reference sample, the 2.10.2 version actually had higher values for the reference than for the tumor. In the attached image, the 2.9.4 data is on the left:

![Example_EVENT_vcf_geno](https://user-images.githubusercontent.com/17885404/110902502-55301d80-8349-11eb-924d-797cae7d74de.png)

**Comment by toddajohnson** [comment]
Hi Daniel,
Today, I ran that tumor/normal pair with GRIDSS 2.10.0, 2.10.1, and once again with 2.10.2, and the problem that I reported above did not reoccur in any of the runs.  I can only surmise that something happened in the previous GRIDSS 2.10.2 run that is more sporadic in nature; perhaps I/O problem running on our cluster with multiple GRIDSS jobs running?  Out of ten samples that were running simultaneously, a couple of the others did not make it through the whole run and only finished after I reran after the others had finished.  If there's anything from the logs that might help decipher the situation, please let me know.

Todd
