### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by JocelynSP** [PapenfussLab/gridss#47]
Running CallVariants with 2 input files generates these warning messages:
ByReadNameSinglePassSamProgram	File reports sort order 'coordinate', assuming it's queryname sorted anyway.
(2 times)
AssemblyFactory	Negative deletions not supported by SAM specs. Breakpoint assembly has been converted to breakend. Sanity check failure: this should not be possible for positional assembly.
(4 times)
CollectInsertSizeMetrics	All data categories were discarded because they contained < 0.05 of the total aligned paired data.
CollectInsertSizeMetrics	Total mapped pairs in all categories: 0.0

**Comment by d-cameron** [comment]
Needs documentation

**Comment by d-cameron** [comment]
Can you retest and see what's left in 1.3.0?
