### ISSUE TITLE
Docker image for 2.11.0 not available

### ISSUE THREAD

**Issue by keiranmraine** [PapenfussLab/gridss#471]
At time of writing the Docker image for the latest version isn't available on dockerhub:

https://hub.docker.com/r/gridss/gridss/tags?page=1&ordering=last_updated

**Comment by alexiswl** [comment]
You can give this a go if you are able to build the docker container locally and want to test it out in the interim.   
https://github.com/alexiswl/gridss/tree/dockerfile-upgrade#building-gridss

**Comment by keiranmraine** [comment]
I did:

```bash
curl -sSL https://github.com/PapenfussLab/gridss/archive/v2.11.0.tar.gz | tar zx
cd gridss-2.11.0
# corrected version in Dockerfile
docker build -t gridss:2.11.0 .
```

**Comment by d-cameron** [comment]
Release packaging is now via the docker builds. 2.12.0 just released and docker images are being uploaded to docker hub.

Now working on fixing the conda package
