### ISSUE TITLE
Dockerfile - wrong version pulled

### ISSUE THREAD

**Issue by keiranmraine** [PapenfussLab/gridss#472]
The new docker file points to the old version of GRIDSS as it downloads from GitHub release files:

https://github.com/PapenfussLab/gridss/blob/v2.11.0/Dockerfile#L47

https://github.com/PapenfussLab/gridss/blob/v2.11.0/Dockerfile#L59-L60

The docker build could avoid the "local environment" issue by using a build stage to complete the build of the resources, without the build environment being required in the final image:

```dockerfile
FROM ubuntu:20.04 as builder
# ... apt etc
WORKDIR /tmp/build
COPY . .
WORKDIR /tmp/build/scripts/dev
RUN bash create_release.sh

FROM ubuntu:20.04
# copy the built jars etc from builder
COPY --from=builder $OPT $OPT
# the rest of your current build
```

Happy to help get this cleaned up.

**Comment by d-cameron** [comment]
Now using a multi-stage docker image
