### ISSUE TITLE
Missing entrez-direct dependency 

### ISSUE THREAD

**Issue by toddajohnson** [PapenfussLab/gridss#473]
I just tried building the VIRUSBreakend database for GRIDSS 2.11.0, and the build process exited without finishing with:

/home/tjohnson/tools/gridss-2.11.0-purple-linx/gridss/virusbreakend-build.sh: line 105: esearch: command not found
/home/tjohnson/tools/gridss-2.11.0-purple-linx/gridss/virusbreakend-build.sh: line 106: efetch: command not found
"efetch -format fasta > $dbname/neighbour.fa" command completed with exit code 127.

I searched around for esearch and efetch  and found them in the EDirect utilities available at https://dataguide.nlm.nih.gov/edirect/install.html

FYI: After installing edirect, I commented out the four kraken2-build lines before the esearch call in virusbreakend-build.sh and reran the script (so as not to re-download files), but an empty neighbour.fa file had already been created during the first run in the VIRUSBREAKENDDB directory, and the script did not permit overwriting that empty file.  I removed neighbour.fa and it is now rerunning.

I would suggest adding the edirect dependency to the VIRUSBreakend README page.

**Comment by alexiswl** [comment]
These are also not present in the dockerfile:

```
$ docker run --rm -it --entrypoint /bin/bash gridss/gridss:latest
root@2805bdf426e6:/data# esearch
bash: esearch: command not found
root@2805bdf426e6:/data# efetch
bash: efetch: command not found
```

**Comment by d-cameron** [comment]
Updated Docker and bioconda packages are on my TODO list (as well as other tasks such as migrating to a new CI engine). Relabelling issue and leaving open until the packages dependencies are correct.
