### ISSUE TITLE
Transport Endpoint Shutdown

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#479]
It's a mystery what to do about it. It happened to only one sample in the data set and only after two hours' processing. [Log.](https://github.com/PapenfussLab/gridss/files/6216205/gridss.full.20210324_152638.gadi-cpu-clx-0360.gadi.nci.org.au.671167.log)

**Comment by d-cameron** [comment]
Looks like a Lustre issue (maybe `obd_timeout` too small for your cluster?), not a GRIDSS issue. You'll have to raise it to your HPC administrators.
