### ISSUE TITLE
Unmapped mate / unpaired read flag conflict

### ISSUE THREAD

**Issue by l-d-s** [PapenfussLab/gridss#48]
```htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 62684, Read name NB500916:139:HJWVMBGXY:1:11105:18088:15085, Mate unmapped flag should not be set for unpaired read.```

**Comment by d-cameron** [comment]
Fixed by b03f5a096a38a81cba907ca98aaff200f576a52b

**Comment by d-cameron** [comment]
Fix  included in 1.1.2
