### ISSUE TITLE
gridss.sh error: "Reference genome does not have an index" 

### ISSUE THREAD

**Issue by abberclark-diamondage** [PapenfussLab/gridss#488]
I am getting the following error: `Reference genome does not have an index. Create using samtools faidx`. However, the index file that I generated with `samtools faidx` is in the same directory as the reference genome. 

I am using a custom reference genome in which a transgene has been added to the mouse genome (specifically, GRCm39.primary_assembly.genome.fa).

I get the error using gridss installed via the docker image (gridss/gridss:latest) and using the precompiled version of gridsstools (v2.11.1). I am using an m5.4xlarge EC2 instance (16 vCPU, 64 GiB memory).
  
This is the command I am running with the precompiled version of gridsstools:
`bash gridss.sh --reference /home/ubuntu/Data/GRCm39.primary_assembly.genome_pHM3.fa \
--output /home/ubuntu/Data/SH5588_SA42196.vcf.gz \
--assembly /home/ubuntu/Data/SH5588_SA42196_gridss_assembly.bam \
--threads 8 \
--jar gridss-2.11.1-gridss-jar-with-dependencies.jar \
--workingdir /home/ubuntu/Data/ \
/home/ubuntu/Data/SH5588_SA42196.bam `

Here is the [full error log.](https://github.com/PapenfussLab/gridss/files/6321657/gridss.full.20210415_190908.ip-172-31-72-132.32643.log)

Please let me know what other information I can provide to help debug the issue. 

Thank you!

**Comment by d-cameron** [comment]
I've been getting a few issues related to this recently and I haven't been able to reproduce locally. Can you post a list of all files in `/home/ubuntu/Data/` both before and after the failing GRIDSS run (`ls -l /home/ubuntu/Data/`)?

**Comment by abberclark-diamondage** [comment]
Before: 

<img width="368" alt="Screen Shot 2021-04-27 at 9 50 01 AM" src="https://user-images.githubusercontent.com/82407451/116253650-a56b0f80-a73e-11eb-8557-4d2d6bd6b1b7.png">

After: 

<img width="461" alt="Screen Shot 2021-04-27 at 9 53 40 AM" src="https://user-images.githubusercontent.com/82407451/116253685-aac85a00-a73e-11eb-91dc-569641abbd16.png">

**Comment by d-cameron** [comment]
Did you manage to resolve this issue? I have only been able to reproduce this locally if the samtools faidx index creation crashes/is killed and the `.fai` file is empty. Deleting the empty files fixes this issue.
