### ISSUE TITLE
GRIDSS doesn't work

### ISSUE THREAD

**Issue by kvn95ss** [PapenfussLab/gridss#493]
Hello,

I'm using the latest release and the jar which has all dependencies. When running my sample using the following command - 

```
./gridss.sh -r $ref_hg38 -o test.vcf -a test.bam -j gridss-2.11.1-gridss-jar-with-dependencies.jar --otherjvmheap 10g
```

The log presents the following error

```

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    AssembleBreakends -JOB_INDEX 0 -JOB_NODES 1 -TMP_DIR . -WORKING_DIR . -REFERENCE_SEQUENCE /mnt/exome/Softwares/GRCh38/REF/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta -WORKER_THREADS 8 -READ_PAIR_CONCORDANT_PERCENT 0.995 -O  /mnt/ngs/WGS_GRCh38/569431/Punya_Veeresh/Punya_Veeresh_recal.bam
**********
```

Would it be possible to use a different version of Picard? I'm not sure how I would go about it.

**Comment by d-cameron** [comment]
That message is a warning message. It is expected and not indicate of an error. GRIDSS packages it's own version of picard tools so it doesn't matter which picard version you have installed on your system.

What's the actually error message causing GRIDSS not to run? Please post the command line output and the full log file.

**Comment by d-cameron** [comment]
>./gridss.sh -r $ref_hg38 -o test.vcf -a test.bam -j gridss-2.11.1-gridss-jar-with-dependencies.jar --otherjvmheap 10g

FYI: If that's your command line, you haven't actually specified an input file. You command line should be:
```
./gridss.sh -r $ref_hg38 -o test.vcf -j gridss-2.11.1-gridss-jar-with-dependencies.jar --otherjvmheap 10g test.bam 
```

It is indeed a bug that GRIDSS doesn't give a meaningful error message. I fixed that last week on the dev branch so the fix will be in the next release.
