### ISSUE TITLE
Most of SVTYPE = BND

### ISSUE THREAD

**Issue by YULEITSINGTAO** [PapenfussLab/gridss#495]
Hello there, 

I run the GRIDSS and got the vcf result but I find most of the results are BND and barely find other SV types. Therefore, I am wondering if there are any suggestions to help. I appreciate it a lot for your time and help. For your convenience, I attached one log file with this message. 
[gridss.full.20210507_113624.i18.31506.log](https://github.com/PapenfussLab/gridss/files/6496483/gridss.full.20210507_113624.i18.31506.log)
Thanks
Lei

**Comment by d-cameron** [comment]
GRIDSS reports everything in BND notation.

I have added an explanation to the FAQ https://github.com/PapenfussLab/gridss/blob/master/Readme.md#why-are-all-calls-bnd

**Comment by d-cameron** [comment]
I notice you have a recently created https://github.com/YULEITSINGTAO/VCFComparison project.

You may find my [StructuralVariantAnnotation](https://www.bioconductor.org/packages/release/bioc/html/StructuralVariantAnnotation.html) BioConductor to be extremely useful for comparing/matching SV calls. It converts SV calls from most popular callers^ into a "paired GRanges" notation which then allows for easy comparison of SV calls. It supports all 3 VCF SV notations: direct (`REF`=`ACGT`, `ALT`=`A`), symbolic (`ALT`=`<DEL>`), and breakpoint (`ALT`=`A[[chr:100[[`) which are converted to a common representation. This greatly simplifies downstream analysis as you don't need to add special case logic for every caller.

For example:
```
library(StructuralVariantAnnotation)
gridss_vcf = readVcf("truth.vcf")
manta_vcf = readVcf("manta.vcf")
# get breakpoint calls in paired GRanges notation
# Note that this filters out SNV and single breakend calls. Use breakendRange() for single breakends.
gridss_bpgr = breakpointRanges(gridss_vcf)
manta_bpgr = breakpointRanges(manta_vcf)

# finds calls common to both gridss and manta.
# The matching criteria are:
# start positions are 100bp of each other (maxgap=100)
# end positions are 100bp of each other (maxgap=100)
# inferred size of the events are within 150bp of each other (sizemargin=50) (so we don't match a 70bp DEL with a 150bp DEL)
# inferred size of the events are within 50% of each other (restrictMarginToSizeMultiple=0.5) (so we don't match a 5bp DEL with a 49bp DEL)
hits = findBreakpointOverlaps(gridss_bpgr, manta_bpgr, maxgap=100, sizemargin=50, restrictMarginToSizeMultiple=0.5)
```

I've used it for all my SV call set comparisons including those in https://www.nature.com/articles/s41467-019-11146-4.


^ StructuralVariantAnnotation supports VCF-compliant calls as well as the non-compliant VCFs written by Delly, manta, Pindel, TIGRA, and others.

**Comment by YULEITSINGTAO** [comment]
Hello Dr. Cameron,

Thanks for answering my questions and recommendation for the StructuralVariantAnnotation. That helps a lot.

Thanks
Lei
