### ISSUE TITLE
VIRUSBreakend installation issues

### ISSUE THREAD

**Issue by suhrig** [PapenfussLab/gridss#499]
Hi Daniel,

I am very curious to try out your tool, but I am having some issues with the installation. I used the current Docker image v2.12.0. First, the script `virusbreakend-build` did not complete successfully, because the utility `xtract.Linux` is not installed in the Docker image (only `xtract` is installed, which in turn calls `xtract.Linux`). Next, I ran into issue #480, which could possibly affect many users (see my comment over there). My first attempt to run `virusbreakend` failed, because `bcftools` is missing in the Docker image. After installing it manually, the script failed at the step `Annotating host genome integrations`, because of `Exception in thread "main" org.broadinstitute.hellbender.utils.bwa.CouldNotReadImageException: cannot read the image file '/data/VIRUSbreakend/hs37d5_PhiX.fa.img': is empty or is not readable`. Apparently, the workflow not only needs the assembly in FastA format, it also requires a BWA index, which has been created using the command `gatk BwaMemIndexImageCreator -I reference.fasta -O reference.fasta.img`. Maybe, it would be a good idea to put this into the `virusbreakend-build` script, because not all users can be expected to have such an index image preinstalled. I created an index image file myself with the GATK version that I happened to have installed (4.2.0.0), but it seems incompatible, because the workflow now fails with the following error. I suspect that I need to use a different version. This is where I am stuck. Can you please comment how the index image should be created?

```
Sat Jun  5 18:36:37 CEST 2021: Annotating host genome integrations
16:36:38.456 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gridss/gridss-2.12.0-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Jun 05 16:36:38 UTC 2021] AnnotateInsertedSequence --WORKER_THREADS 8 --INPUT ./sample.virusbreakend.vcf.virusbreakend.working/adjusted/sample.virusbreakend.vcf.gridss.vcf --OUTPUT ./sample.virusbreakend.vcf.virusbreakend.working/adjusted/sample.virusbreakend.vcf.gridss.bealn.vcf --WORKING_DIR ./sample.virusbreakend.vcf.virusbreakend.working --TMP_DIR ./sample.virusbreakend.vcf.virusbreakend.working --REFERENCE_SEQUENCE /data/VIRUSbreakend/hs37d5_PhiX.fa --MIN_SEQUENCE_LENGTH 20 --ALIGNER_BATCH_SIZE 500000 --ALIGNMENT REPLACE --IGNORE_DUPLICATES true --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Sat Jun 05 16:36:38 UTC 2021] Executing as centos@vm-154 on Linux 3.10.0-693.21.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04; Deflater: Intel; Inflater: Intel; Provider
 GCS is not available; Picard version: Version:2.12.0-gridss
INFO    2021-06-05 16:36:38     AnnotateInsertedSequence        Annotating inserted sequences in ./sample.virusbreakend.vcf.virusbreakend.working/adjusted/sample.virusbreakend.vcf.gridss.vcf
INFO    2021-06-05 16:36:38     AnnotateInsertedSequence        Using in-process bwa alignment
INFO    2021-06-05 16:36:38     BwaAligner      Loading bwa mem index image from /data/VIRUSbreakend/hs37d5_PhiX.fa.img
[Sat Jun 05 16:36:38 UTC 2021] gridss.AnnotateInsertedSequence done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2149580800
Exception in thread "main" java.lang.NullPointerException
        at au.edu.wehi.idsv.alignment.BwaAligner.getMinimalHeader(BwaAligner.java:102)
        at au.edu.wehi.idsv.alignment.BwaAligner.<init>(BwaAligner.java:43)
        at au.edu.wehi.idsv.alignment.BwaStreamingAligner.<init>(BwaStreamingAligner.java:68)
        at gridss.AnnotateInsertedSequence.doWork(AnnotateInsertedSequence.java:109)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.AnnotateInsertedSequence.main(AnnotateInsertedSequence.java:66)
```

Many thanks,
Sebastian

**Comment by d-cameron** [comment]
Thanks for the helpful feedback. Your experience running VIRUSBreakend has be nowhere near as clean as it should be.

>Can you please comment how the index image should be created?

The required reference genome files are created by the `gridss` `setupreference` step.
```
gridss \
    -s setupreference \
    -o placeholder_that_is_ignored_since_you_are_only_running_setup_reference.vcf \
    -r /data/VIRUSbreakend/hs37d5_PhiX.fa \
    -j /opt/gridss/gridss-2.12.0-gridss-jar-with-dependencies.jar \
    sample.bam
```

The file generate may or may not be compatible with the GATK `.img` file. We're using the same library for bwa Java integration, but I don't know which version of the library is used by GATK4.

**Comment by d-cameron** [comment]
Keeping this issue open while I work out where a good place to host a prebuilt database is.

**Comment by suhrig** [comment]
Thank you for the quick help (and the immediate fixes)! After getting two more obstacles out of the way I was able to run the pipeline successfully:

1. At one point the pipeline tries to call `/opt/rmblast/makeblastdb`, which does not exist. There is a `makeblastdb` in `/opt/blast`. At first, I wanted to make use of that, but I think it is the wrong version (results in incompatible database). So I downloaded a version that matches `rmblast` (2.2.27). That worked. On a related note: The RepeatMasker cache is created in the user's home directory. If this is a one-off setup, then these files probably should also go into the prebuilt database - provided that `rmblast` can be configured to use a directory other than the home directory. If the files are unique for each run, then they should probably go into a temp folder, because a user's home directory could fill up over time, otherwise.
2. Close to completion of the pipeline, the utility `bc` is called. It is missing in the Docker image.

> The required reference genome files are created by the `gridss setupreference` step.

I must have overlooked that, thanks. I guess main users of gridss would already know this or even have the files already.

> Keeping this issue open while I work out where a good place to host a prebuilt database is.

That would be very convenient! A single build took 2-3 days on my cluster. Due to some download errors I had to start over, so it took me well over a week to get a working build.

Thanks again for your help. Very much appreciated!

**Comment by d-cameron** [comment]
A prebuilt database is now available at https://melbourne.figshare.com/articles/dataset/virusbreakenddb_20210401_tar_gz/14782299

**Comment by suhrig** [comment]
I'm not sure if you have fixed these already. Maybe you overlooked them in my last post:

1. `/opt/rmblast/makeblastdb` is missing in the Docker image.
2. `bc` is missing in the Docker image.

Moreover, I have two additions:

3. `bc` is also missing when installing via Conda.
4. `bcftools` is also missing in the Conda recipe.

You could use `awk` instead of `bc`. `awk` is installed pretty much everywhere and could easily replace `bc`, since the latter is only used in two places to compute trivial arithmetic terms.

**Comment by brownmp** [comment]
I'm still having the issue `/opt/gridss/virusbreakend: line 871: bc: command not found`. 
Seems like this issue hasn't been addressed yet.

**Comment by d-cameron** [comment]
Docker or bioconda?

**Comment by brownmp** [comment]
Docker image.
