### ISSUE TITLE
Easy per-input category quality scores

### ISSUE THREAD

**Issue by l-d-s** [PapenfussLab/gridss#50]
Including weighting the categories by read quality as well as number of reads.

**Comment by d-cameron** [comment]
Add ASSRQ and ASRPQ based on actual contribution to assembly. Need to:
- refactor model interface to expose per-read assembly contributions
- write ASSRQ & ASRPQ to VCF
- either write SAM Tags equivalent of ASSRQ & ASRPQ, or perform read-to-assembly rehydration when annotating. The former would be simpler to do.

**Comment by d-cameron** [comment]
Added in commit afa4db8f325fc2f60e07fad6c13bfbfd00e5ac41
