### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Duplicate key 9606

### ISSUE THREAD

**Issue by wangc1106** [PapenfussLab/gridss#507]
Dear cameron,

i have some question about the VIRUSBreakend. 

1  ####################################### my virusbreakend-build step seems already done successfully######
[Thu Jun 24 01:43:50 CST 2021] Executing as hjb_usr04@localhost.localdomain on Linux 3.10.0-1127.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.8.0-gridss
[Thu Jun 24 01:44:04 CST 2021] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.25 minutes.
Runtime.totalMemory()=3593469952
virusbreakenddb/hash.k2d
virusbreakenddb/opts.k2d
virusbreakenddb/taxo.k2d
virusbreakenddb/taxonomy/nodes.dmp
virusbreakenddb/taxonomy/names.dmp
virusbreakenddb/library/viral/library.fna
virusbreakenddb/library/viral/library.fna.dict
virusbreakenddb/library/viral/library.fna.fai
virusbreakenddb/library/viral/library.fna.masked
virusbreakenddb/library/added/3HdiMSXQTC.fna
virusbreakenddb/library/added/3HdiMSXQTC.fna.dict
virusbreakenddb/library/added/3HdiMSXQTC.fna.fai
virusbreakenddb/library/added/3HdiMSXQTC.fna.masked
virusbreakenddb/library/added/SIvrucSH2V.fna
virusbreakenddb/library/added/SIvrucSH2V.fna.dict
virusbreakenddb/library/added/SIvrucSH2V.fna.fai
virusbreakenddb/library/added/SIvrucSH2V.fna.masked
virusbreakenddb/library/added/_FJ7DJSp5x.fna
virusbreakenddb/library/added/_FJ7DJSp5x.fna.dict
virusbreakenddb/library/added/_FJ7DJSp5x.fna.fai
virusbreakenddb/library/added/_FJ7DJSp5x.fna.tmp
virusbreakenddb/taxid10239.nbr
virusbreakenddb/seqid2taxid.map
Thu Jun 24 02:58:20 CST 2021: VIRUSBreakend build successful
Thu Jun 24 02:58:20 CST 2021: The full build (including intermediate files) can be found in virusbreakenddb
Thu Jun 24 02:58:20 CST 2021: An archive containing only the files required by VIRUSBreakend can be found at /home/hjb_usr04/VIRUSBreakend/virusbreakend.db.virusbreakenddb.tar.gz
#############################################################################################

2  Next，i run
```
/home/hjb_usr04/gridss-2.12.0/scripts/virusbreakend \
--jar /home/hjb_usr04/gridss-2.12.0/scripts/gridss-2.12.0-gridss-jar-with-dependencies.jar \
--kraken2db virusbreakenddb \
--output S1_T.virusbreakend.vcf \
-w ./VBtmp \
-t 16 \
--host human \
--reference /NAS/Database/genome/hg19/ucsc.hg19.fa \
/NAS/dbGaP_CGCI_HIV/T_N_c1/S1_T_SRR1273943.sortedByName.bam

```

and i got some errors.

Thu Jun 24 23:19:35 CST 2021: Found /home/hjb_usr04/anaconda3/bin/Rscript
Thu Jun 24 23:19:35 CST 2021: Found /home/hjb_usr04/RepeatMasker/RepeatMasker
Thu Jun 24 23:19:35 CST 2021: Found /home/hjb_usr04/gridss/src/main/c/gridsstools/gridsstools
Thu Jun 24 23:19:35 CST 2021: gridsstools version: gridsstools 1.0
Thu Jun 24 23:19:35 CST 2021: samtools version: 1.7+htslib-1.7
Thu Jun 24 23:19:35 CST 2021: R version: R scripting front-end version 3.2.2 (2015-08-14)
Thu Jun 24 23:19:35 CST 2021: bwa Version: 0.7.17-r1188
Thu Jun 24 23:19:35 CST 2021: Kraken version 2.1.2
which: no time in (/usr/bin)
Thu Jun 24 23:19:35 CST 2021: bash version: GNU bash, version 4.4.18(1)-release (x86_64-unknown-linux-gnu)
Thu Jun 24 23:19:36 CST 2021: java version: openjdk version "1.8.0_152-release" OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)  OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
Thu Jun 24 23:19:37 CST 2021: Identifying viral sequences
Thu Jun 24 23:19:37 CST 2021: Treating 0 reference sequences as viral sequences.
Thu Jun 24 23:28:40 CST 2021: Identifying viral taxa in sample based on kraken2 summary report
Thu Jun 24 23:28:53 CST 2021: Exit status 0 for $timecmd java -Xmx8g $jvm_args -cp $gridss_jar gridss.kraken.IdentifyViralTaxa --INPUT_KRAKEN2_REPORT $file_report --OUTPUT $file_summary_taxa_tsv --REPORT_OUTPUT $file_viral_report --SUMMARY_REPORT_OUTPUT $file_extracted_report --NCBI_NODES_DMP $nodesdmp --SEQID2TAXID_MAP $seqidtaxidmap --MIN_SUPPORTING_READS $minreads --TAXONOMIC_DEDUPLICATION_LEVEL Genus $taxid_args 1>&2 2>> $logfile
*****
*****
See log file ./VBtmp/S1_T.virusbreakend.vcf.virusbreakend.working/virusbreakend.20210624_231935.localhost.localdomain.189507.log for underlying error
*****
*****

[Thu Jun 24 23:28:41 CST 2021] Executing as hjb_usr04@localhost.localdomain on Linux 3.10.0-1127.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.12.0-gridss
INFO    2021-06-24 23:28:52     IdentifyViralTaxa       Loading taxonomy IDs of interest from ./VBtmp/S1_T.virusbreakend.vcf.virusbreakend.working/S1_T.virusbreakend.vcf.host_taxids.txt
INFO    2021-06-24 23:28:52     IdentifyViralTaxa       Loaded 499 taxonomy IDs
INFO    2021-06-24 23:28:52     IdentifyViralTaxa       Loading seqid2taxid.map from virusbreakenddb/seqid2taxid.map
[Thu Jun 24 23:28:52 CST 2021] gridss.kraken.IdentifyViralTaxa done. Elapsed time: 0.18 minutes.
Runtime.totalMemory()=3933208576
Exception in thread "main" java.lang.IllegalStateException: Duplicate key 9606
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1253)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at au.edu.wehi.idsv.kraken.SeqIdToTaxIdMap.createLookup(SeqIdToTaxIdMap.java:18)
        at gridss.kraken.IdentifyViralTaxa.doWork(IdentifyViralTaxa.java:124)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.kraken.IdentifyViralTaxa.main(IdentifyViralTaxa.java:230)

I tried to solve the[ "main" java.lang.IllegalStateException: Duplicate key 9606 ] error, I tried to edit the gridss-2.12.0-gridss-jar-with-dependencies.jar file，but i failed in editing the  gridss/kraken/IdentifyViralTaxa.class file. 

Could you give me some advice, thank you very much

**Comment by wangc1106** [comment]
Please give me some advice 

![(_0 6OCZC989EI6PBNMT F2](https://user-images.githubusercontent.com/48993820/124737048-20069700-df07-11eb-97bd-a5ab9ca00b22.png)

![WKF47$ ~8%Y0~BI%07 }K)Y](https://user-images.githubusercontent.com/48993820/124737082-285ed200-df07-11eb-8bc4-8e2e9b98656c.png)

```Map<Integer, KrakenReportLine> lookup = (Map<Integer, KrakenReportLine>)fullReport.stream().collect(Collectors.toMap(x -> Integer.valueOf(x.taxonomyId), x -> x, (x1, x2) -> x2));```

```Map<Integer, KrakenReportLine> reportLookup = (Map<Integer, KrakenReportLine>)fullReport.stream().collect(Collectors.toMap(krl -> Integer.valueOf(krl.taxonomyId), krl -> krl, (krl1, krl2) -> krl2));```

i tried to add  (x1, x2) -> x2 and (krl1, krl2) -> krl2, but i failed when i transformed .java file to .class file

**Comment by alexiswl** [comment]
Looks like this file `virusbreakenddb/seqid2taxid.map` has a duplicate key?

**Comment by wangc1106** [comment]
> Looks like this file `virusbreakenddb/seqid2taxid.map` has a duplicate key?

thank u very much. I have deleted the duplicate key in that file, and it works.
