### ISSUE TITLE
SR empty on my vcf

### ISSUE THREAD

**Issue by JocelynSP** [PapenfussLab/gridss#51]
No split reads are being written to my vcf.
Same file as in previous issue, hope that's OK

**Comment by papenfuss** [comment]
Hi Jocelyn,

Nice and important catch! Thank you.

Cheers,
Tony


On 1 Feb 2017, at 5:49 pm, JocelynSP <notifications@github.com<mailto:notifications@github.com>> wrote:


No split reads are being written to my vcf.
Same file as in previous issue, hope that's OK
