### ISSUE TITLE
Problem using snakemake

### ISSUE THREAD

**Issue by NicoleTabarini** [PapenfussLab/gridss#512]
Hi,

First of all, thank you for the tool!
We are encountering a problem when trying to use GRIDSS through snakemake. If I am not mistaken, I understood that the initial FASTA processing can’t be done in parallel, so I was thinking to first create the files necessary, then run GRIDSS.
In order to do so, I tried:
gridss -s setupreference  --reference file.fasta  --output file.vcf.gz  --assembly file.bam   sample1.cram

But I get this error:

_Mon Jul 12 17:24:25 CEST 2021: Full log file is: ./gridss.full.20210712_172425.energon01.15209.log
Mon Jul 12 17:24:25 CEST 2021: Found /usr/bin/time
Mon Jul 12 17:24:25 CEST 2021: Using GRIDSS jar /home2/igg_jlab/wgs_sv/2021-06-09/.snakemake/conda/712cfe5a/share/gridss-2.12.0-1/gridss.jar
Mon Jul 12 17:24:25 CEST 2021: Using reference genome "/home/datasets_references/gatk/Hg38/Homo_sapiens_assembly38.fasta"
Mon Jul 12 17:24:25 CEST 2021: Using 8 worker threads.
Mon Jul 12 17:24:25 CEST 2021: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Mon Jul 12 17:24:25 CEST 2021: Using JVM maximum heap size of 30g for assembly and variant calling.
Mon Jul 12 17:24:25 CEST 2021: Using input file reads/recalibrated/T-NGS_347.dedup.recal.cram
Mon Jul 12 17:24:25 CEST 2021: Found /home2/igg_jlab/wgs_sv/2021-06-09/.snakemake/conda/712cfe5a/bin/Rscript
Mon Jul 12 17:24:25 CEST 2021: Found /home2/igg_jlab/wgs_sv/2021-06-09/.snakemake/conda/712cfe5a/bin/samtools
Mon Jul 12 17:24:25 CEST 2021: Found /home2/igg_jlab/wgs_sv/2021-06-09/.snakemake/conda/712cfe5a/bin/java
Mon Jul 12 17:24:25 CEST 2021: Found /home2/igg_jlab/wgs_sv/2021-06-09/.snakemake/conda/712cfe5a/bin/bwa
Mon Jul 12 17:24:25 CEST 2021: samtools version: 1.12+htslib-1.12
Mon Jul 12 17:24:25 CEST 2021: R version: R scripting front-end version 4.1.0 (2021-05-18)
Mon Jul 12 17:24:25 CEST 2021: bwa Version: 0.7.17-r1188
Mon Jul 12 17:24:25 CEST 2021: time version: GNU time 1.7
Mon Jul 12 17:24:25 CEST 2021: bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Mon Jul 12 17:24:26 CEST 2021: java version: openjdk version "11.0.9.1-internal" 2020-11-04 OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src) OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)
Mon Jul 12 17:24:26 CEST 2021: Max file handles: 4096
Mon Jul 12 17:24:26 CEST 2021: Running GRIDSS steps: setupreference,
mkdir: cannot create directory '/home/datasets_references/gatk/Hg38/Homo_sapiens_assembly38.fasta.tmp.gridsslock': Permission denied
Mon Jul 12 17:24:26 CEST 2021: Multiple instances of setupreference cannot be run concurrently. Aborting due to existence of /home/datasets_references/gatk/Hg38/Homo_sapiens_assembly38.fasta.tmp.gridsslock
"exit $EX_CANTCREAT" command completed with exit code 73_

Do you have an idea on how to solve it? 
In addition, does this step depend on the bam(or cram) file given? If the reference is the same, but the samples I want to analyze are different, should I re-process the fasta file or doing it once is enough?

Thank you in advance,
Nicole

**Comment by d-cameron** [comment]
> Multiple instances of setupreference cannot be run concurrently. Aborting due to existence of /home/datasets_references/gatk/Hg38/Homo_sapiens_assembly38.fasta.tmp.gridsslock

Is the root cause.

>Do you have an idea on how to solve it?

Wait for the previous setupreference to finish.

If the process was kill, or otherwise unable to complete, delete the partially written reference cache/ndex files and rerun setupreference.

> In addition, does this step depend on the bam(or cram) file given? If the reference is the same, but the samples I want to analyze are different, should I re-process the fasta file or doing it once is enough?

No it's a once-off setup step. The lock file is create to prevent the files generated by setupreference being run by mulitple instances of GRIDSS at the same time. Once they exist, any number of gridss instances can be run off the same reference.

**Comment by d-cameron** [comment]
My guess is that you started and killed a job during the setupreference step so the lock file never got deleted.

**Comment by NicoleTabarini** [comment]
Hi Daniel,
Thank you for answering me!
I believe you're right, that is what happened for sure. However, I just looked and I don't have any partial file to delete (there are no reference cache/ndex files).. do you have any advice?

**Comment by d-cameron** [comment]
If you know you don't have any running GRIDSS processes, you're safe to delete the lock (`/home/datasets_references/gatk/Hg38/Homo_sapiens_assembly38.fasta.tmp.gridsslock`) and rerun.
