### ISSUE TITLE
Virusbreakend-build error

### ISSUE THREAD

**Issue by xiaoyunguo** [PapenfussLab/gridss#516]
Hi, 
I tried to build the virus reference library, and the see the following error at the end about rsync. It seems to be a script inside the package. Any suggestion to fix it?

Thanks

    -----------------------------
    (base):gridss$ ./virusbreakend-build --db virusbreakenddb --jar ./gridss-2.12.0-gridss-jar-with-dependencies.jar
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/kraken2-build
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/samtools
    Mon Aug  9 22:07:08 UTC 2021: Found /usr/bin/gunzip
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/tar
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/dustmasker
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/rsync
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/java
    Mon Aug  9 22:07:08 UTC 2021: Found /home/xiaoyun/miniconda3/bin/wget
    Mon Aug  9 22:07:08 UTC 2021: Using GRIDSS jar ./gridss-2.12.0-gridss-jar-with-dependencies.jar
    Downloading nucleotide gb accession to taxon map... done.
    Downloading nucleotide wgs accession to taxon map... done.
    Downloaded accession to taxon map(s)
    Downloading taxonomy tree data... done.
    Uncompressing taxonomy data... done.
    Untarring taxonomy tree data... done.
    mv: replace 'assembly_summary.txt', overriding mode 0444 (r--r--r--)? y
    Step 1/2: Performing rsync file transfer of requested files
    Rsync file transfer complete.
    Step 2/2: Assigning taxonomic IDs to sequences
    Processed 1 project (639 sequences, 3.27 Gbp)... done.
    All files processed, cleaning up extra sequence files... done, library complete.
    Masking low-complexity regions of downloaded library... done.
    Step 1/2: Performing rsync file transfer of requested files
    rsync: link_stat "/all/GCF/003/034/835/GCF_003034835.1_ASM303483v1/GCF_003034835.1_ASM303483v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
    rsync: link_stat "/all/GCF/001/611/645/GCF_001611645.5_ASM161164v5/GCF_001611645.5_ASM161164v5_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
    rsync: link_stat "/all/GCF/002/957/295/GCF_002957295.1_ASM295729v1/GCF_002957295.1_ASM295729v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
    rsync: link_stat "/all/GCF/002/833/545/GCF_002833545.1_ASM283354v1/GCF_002833545.1_ASM283354v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1816) [generator=3.2.3]
    rsync_from_ncbi.pl: rsync error, exiting: 5888
    "kraken2-build $kraken2buildargs --download-library viral --db $dbname" command completed with exit code 25.
    --------------------

**Comment by d-cameron** [comment]
Keep trying until NCBI doesn't error out. It's a really annoying problem hence why I've added a prebuilt database download (https://github.com/PapenfussLab/gridss/blob/master/VIRUSBreakend_Readme.md#reference-data). I'll have a AWS mirror up as well (as soon as the paperwork is done)

**Comment by d-cameron** [comment]
I had to keep manually rerun the failing (kraken2) build step repeatedly until it finally worked.
