### ISSUE TITLE
VIRUSBreakend support for non human species

### ISSUE THREAD

**Issue by xiaoyunguo** [PapenfussLab/gridss#518]
Hi, 
I am running virus annotation on non-human species. I noticed that the default species in  virusbreakend is human
--rmargs: additional RepeatMasker arguments (Default: --species human)

How can I remove that or set it to a different species? I tried assign null to the --rmargs options but doesn't work. 

Thanks

Xiaoyun

**Comment by d-cameron** [comment]
Viral or repeat annotations?

`gridss_annotate_vcf_repeatmasker` performs RepeatMasker annotations. `--rmargs` is used to set to species but be aware that your repeatmasker database needs to have the repeats for your species in it's database. Consult the repeatmasker documentation for the contents of the default database.

`gridss_annotate_vcf_kraken2` performs Kraken2 classification which will perform viral classification when a kraken2 database that contains viral sequences (both the standard Kraken2 database and the VIRUSBreakend database will work for this purpose). This command does not have a `--rmargs` argument.

**Comment by d-cameron** [comment]
Wait, I

**Comment by d-cameron** [comment]
Workaround for non -human species that'll work with the current VIRUSBreakend version:
- Run `virusbreakend-build` up to line 122
- Augment VIRUSBreakend database with host species with taxid=9606
  - kraken2-build --add-to-library host.fa --db $dbname
  - Add host contigs -> taxid mappings to $dbname/seqid2taxid.map
     - Use 9606 (human) as the taxid mapping
- Run `virusbreakend-build` from line 123 (`kraken2-build`) onwards
- run `virusbreakend` as normal with `--reference` of your host genome

The kraken2 annotations will be misallocated 9606 (human) and in theory the RM annotations could include human-specific repeat annotation (although why would you have human repeats in your non-human host), but the integration positions with be w.r.t your host genome.

**Comment by d-cameron** [comment]
Development changes for full support of non human VIRUSBreakend hosts:

- Update `virusbreakend`
   - line 813: add command-line option to set the hosttaxid for non-human hosts
- Extend `virusbreakend-build` with support for other hosts
  - command-line option to specify host genome and taxid
    - kraken2-build --add-to-library ref.fa --db $dbname
   - Add host contigs -> taxid mappings to $dbname/seqid2taxid.map
   - Remove human sequences from the kraken2 database
 - Update `--rmargs` for host
   - Doesn't really matter as VIRUSBreakend only really cares about exclude simple/low complexity repeats and they're not in the species-specific RM database.

**Comment by xiaoyunguo** [comment]
Thanks for the replies. One more question, after calling virus breakend. The summary .tsv file shows 60 viral integration, but the vcf file is empty. Wonder why, I would also like to know the integration site.

**Comment by d-cameron** [comment]
Two possibilities:

- Are the integrations into viral contigs/genomes that were filtered?
- You're looking at the mapping quality, not number of insertions due to headers not lining https://github.com/PapenfussLab/gridss/issues/504 ?



I've added instructions for this into the the quickstart guide: https://github.com/PapenfussLab/gridss/blob/master/QuickStart.md#find-viral-integration-sites-in-a-non-human-genome
