### ISSUE TITLE
Error using gridss_somatic_filter from docker image

### ISSUE THREAD

**Issue by tea-kostic** [PapenfussLab/gridss#533]
Hi,

I am trying to run gridss_somatic_filter from gridss/gridss:2.12.1 docker image.
When executing gridss_somatic_filter, I get the following error: `/usr/bin/env: 'Rscript\r': No such file or directory`.
All the other gridss programs work fine, except this one.

How can I solve this issue?

Thanks,
Tea

**Comment by d-cameron** [comment]
Pretty sure it's my fault and is an issue with the (win10) build machine for the docker image.

I'll fix it for the next GRIDSS release.

**Comment by d-cameron** [comment]
New release is up.
