### ISSUE TITLE
gridsstools Makefile does not autodetect if libdeflate is available

### ISSUE THREAD

**Issue by astulaaa** [PapenfussLab/gridss#538]
I followed github instalation guide:

git clone http://github.com/PapenfussLab/gridss/
cd gridss
git submodule init
git submodule update
cd src/main/c/gridsstools/htslib/
autoheader
autoconf
./configure && make
cd ..
autoheader
autoconf
./configure && make all

and got this error at the last step:

/usr/bin/ld: cannot find -ldeflate
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'gridsstools' failed
make: *** [gridsstools] Error 1

What happened and how can I fix it?

Thank you,
Asta

**Comment by d-cameron** [comment]
Your options are:

- Install `libdeflate` on your system
- Edit the `src/main/c/gridsstools/Makefile` and remove `-ldeflate`
- Use conda to install gridss
- Run gridss from the gridss/gridss:latest docker image
- Use the pre-compiled binary from the github releases page
