### ISSUE TITLE
conda gridss missing gridsstools from path?

### ISSUE THREAD

**Issue by MjelleLab** [PapenfussLab/gridss#541]
I have tried install grids both using conda and git clone https://github.com/PapenfussLab/gridss.git, however, grids stools file to be installed it seems. Any suggestions?

./virusbreakend --kraken2db virusbreakenddb_20210401 --output sample.virusbreakend.vcf --reference ref_genome_37.gz --jar gridss-2.12.2-gridss-jar-with-dependencies.jar CPCT02020337T_dedup.realigned.cram.unmapped.bam 
Fri Nov  5 13:19:42 MET 2021: Using working directory "."
Fri Nov  5 13:19:42 MET 2021: Full log file is: ./sample.virusbreakend.vcf.virusbreakend.working/virusbreakend.20211105_131942.mh-ikom01.29865.log
Fri Nov  5 13:19:42 MET 2021: Found /usr/bin/time
Fri Nov  5 13:19:42 MET 2021: Using GRIDSS jar gridss-2.12.2-gridss-jar-with-dependencies.jar
Fri Nov  5 13:19:42 MET 2021: Using reference genome "ref_genome_37.gz"
Fri Nov  5 13:19:42 MET 2021: Using output VCF sample.virusbreakend.vcf
Fri Nov  5 13:19:42 MET 2021: Using 8 worker threads.
Fri Nov  5 13:19:42 MET 2021: Using input file CPCT02020337T_dedup.realigned.cram.unmapped.bam
Fri Nov  5 13:19:42 MET 2021: Found /mnt/scratch/home/local/robinm/software/VIRUSBreakend/kraken2/kraken2
Fri Nov  5 13:19:42 MET 2021: Found /home/local/robinm/anaconda3/bin/gridss
Fri Nov  5 13:19:42 MET 2021: Found /mnt/scratch/home/local/robinm/software/VIRUSBreakend/gridss/scripts/gridss_annotate_vcf_kraken2
Fri Nov  5 13:19:42 MET 2021: Found /mnt/scratch/home/local/robinm/software/VIRUSBreakend/gridss/scripts/gridss_annotate_vcf_repeatmasker
Fri Nov  5 13:19:42 MET 2021: Found /home/local/robinm/anaconda3/bin/samtools
Fri Nov  5 13:19:42 MET 2021: Found /home/local/robinm/anaconda3/bin/bcftools
Fri Nov  5 13:19:43 MET 2021: Found /home/local/robinm/anaconda3/bin/java
Fri Nov  5 13:19:43 MET 2021: Found /home/local/robinm/anaconda3/bin/bwa
Fri Nov  5 13:19:43 MET 2021: Found /home/local/robinm/anaconda3/bin/Rscript
Fri Nov  5 13:19:43 MET 2021: Found /home/local/robinm/anaconda3/bin/RepeatMasker
Fri Nov  5 13:19:43 MET 2021: MISSING gridsstools.
Fri Nov  5 13:19:43 MET 2021: Exit status 0 for exit $EX_CONFIG
*****
*****
See log file ./sample.virusbreakend.vcf.virusbreakend.working/virusbreakend.20211105_131942.mh-ikom01.29865.log for underlying error
*****
*****

**Comment by MjelleLab** [comment]
Solved by installing manually

**Comment by d-cameron** [comment]
Which conda gridss version was failing? gridsstools should be included as part of the conda install

**Comment by d-cameron** [comment]
Should be good in the new conda package
