### ISSUE TITLE
SV present or absent in a specific sample?

### ISSUE THREAD

**Issue by astulaaa** [PapenfussLab/gridss#543]
Hello, I understand your position on not wanting to label if the SV is homozygous or heterozygous,
but could you suggest some kind of way to tell if the SV is present or absent in the sample in the first place? 
In my case I have 4 samples genotyped in the same VCF file. While I don't mind the genotype would be 1/0 or 1/1, I would like to be able to tell if it is 0/0 (no SV) or either of the (1/0 or 1/1).
Do you have any suggestions?

Thank you!
Asta

**Comment by d-cameron** [comment]
The VCF `FORMAT` fields provide a full breakdown of the per-sample support. Of particular note are:
- `AF`: allele fraction. 1.0 indicate homozygous, 0.0 indicates not present in sample


`AF` is calculated from
- `VF`: number of unique fragments supporting a breakpoint (correctly handle fragments that are both a split read and discordant read pair)
- `BVF`: single breakend equivalent of `VF`
- `REF`: number of reference-supporting reads aligning across the breakend
- `REFPAIR`: number of reference-supporting reads aligning across the breakend


Note that breakpoints can and do different `AF`/`REF`/`REFPAIR` at the two breakends. For example, a breakpoint can be heterozygous on one side but homozygous at the other (e.g. a chr1-chr2 breakpoint with a loss of the other copy of chr2).

**Comment by d-cameron** [comment]
No genotype information is written as GRIDSS does not make any assumptions about the ploidy or subclonality of a sample. It should be relatively straightforward to work from your ploidy/copy number assumptions/calls to a genotype. Again, a reminder that they genotype can be different on each side of a breakend (e.g. CN=3 genotype of 0/0/1 on ine side and CN=1 genotype of 1 on the other side).

Unfortunately, VCF doesn't really support genotyping in the presence of subclonality and it's genotyping model make integer copy number assumptions.
