### ISSUE TITLE
question about SV size cutoff

### ISSUE THREAD

**Issue by tgong1** [PapenfussLab/gridss#545]
Hi Daniel,

Is there a size cutoff applied by GRIDSS? I ran GRIDSS on HCC1395 cancer cell line and got some very small size SVs. I usually use the cutoff of 50bp for small indels and SVs. So, not very sure if I should exclude them in my SV set. Hope you can give me some suggestions.

Please see the following examples.

(1) To me, the following pair of BND is a small insertion.  So not sure if I should include this into set of small indels or leave it as a SV?
chr6	40305503	gridss110fb_3894o	C	CTGCATGCAGATAAAGT[chr6:40305504[	5025.93	PASS	AS=1;ASC=1X;ASQ=1870.76;ASRP=0;ASSR=104;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm110-18417,asm110-91299;BEIDH=0,0;BEIDL=0,0;BQ=0;BSC=0;BSCQ=0;BUM=0;BUMQ=0;BVF=0;CAS=0;CASQ=0;CQ=4918.23;EVENT=gridss110fb_3894;IC=31;IQ=1292.87;MATEID=gridss110fb_3894h;MQ=59.84;MQN=49;MQX=60;RAS=1;RASQ=1754.6;REF=179;REFPAIR=80;RP=0;RPQ=0;SB=0.5971223;SC=99M1X;SR=4;SRQ=107.7;SVTYPE=BND;VF=71;TAF=0.35678,0.35678;LOCAL_LINKED_BY=;REMOTE_LINKED_BY=	GT:AF:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:51:29:0:0:0:0:0	.:0.357:1870.76:0:104:0:0:0:0:0:0:0:0:0:0:0:0:0:0:31:1292.87:5025.93:1754.6:128:51:0:0:4:107.7:71
chr6	40305504	gridss110fb_3894h	T	]chr6:40305503]TGCATGCAGATAAAGTT	5025.93	PASS	AS=1;ASC=1X;ASQ=1754.6;ASRP=0;ASSR=104;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm110-18417,asm110-91299;BEIDH=0,0;BEIDL=0,0;BQ=0;BSC=0;BSCQ=0;BUM=0;BUMQ=0;BVF=0;CAS=0;CASQ=0;CQ=4918.23;EVENT=gridss110fb_3894;IC=31;IQ=1292.87;MATEID=gridss110fb_3894o;MQ=59.84;MQN=49;MQX=60;RAS=1;RASQ=1870.76;REF=179;REFPAIR=80;RP=0;RPQ=0;SB=0.5971223;SC=1X95M;SR=4;SRQ=107.7;SVTYPE=BND;VF=71;TAF=0.35678,0.35678;LOCAL_LINKED_BY=;REMOTE_LINKED_BY=	GT:AF:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:51:29:0:0:0:0:0	.:0.357:1754.6:0:104:0:0:0:0:0:0:0:0:0:0:0:0:0:0:31:1292.87:5025.93:1870.76:128:51:0:0:4:107.7:71

(2) Again, to me, this pair of BND is a small deletion with size of 12bp. 
chr6	20824941	gridss108fb_5212o	A	A[chr6:20824953[	7180.49	PASS	AS=2;ASC=2X;ASQ=3119.04;ASRP=0;ASSR=170;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm108-106046,asm108-106047,asm108-25514,asm108-25515;BEIDH=0,0,0,0;BEIDL=0,0,0,0;BQ=0;BSC=0;BSCQ=0;BUM=0;BUMQ=0;BVF=0;CAS=0;CASQ=0;CIPOS=0,1;CQ=5399.48;EVENT=gridss108fb_5212;HOMLEN=1;HOMSEQ=T;IC=32;IHOMPOS=0,1;IQ=1085.91;MATEID=gridss108fb_5212h;MQ=60;MQN=60;MQX=60;RAS=2;RASQ=2793.03;REF=160;REFPAIR=114;RP=0;RPQ=0;SB=0.44052863;SC=91M2X;SR=5;SRQ=182.51;SVTYPE=BND;VF=68;TAF=0.5037,0.5;LOCAL_LINKED_BY=;REMOTE_LINKED_BY=	GT:AF:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:93:32:0:0:0:0:0	.:0.504:3119.04:0:170:0:0:0:0:0:0:0:0:0:0:0:0:0:0:32:1085.91:7180.49:2793.03:67:82:0:0:5:182.51:68
chr6	20824953	gridss108fb_5212h	T	]chr6:20824941]T	7180.49	PASS	AS=2;ASC=2X;ASQ=2793.03;ASRP=0;ASSR=170;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm108-106046,asm108-106047,asm108-25514,asm108-25515;BEIDH=0,0,0,0;BEIDL=0,0,0,0;BMQ=59.92;BMQN=58;BMQX=60;BQ=670.35;BSC=25;BSCQ=670.35;BUM=0;BUMQ=0;BVF=14;CAS=0;CASQ=0;CIPOS=0,1;CQ=5399.48;EVENT=gridss108fb_5212;HOMLEN=1;HOMSEQ=T;IC=32;IHOMPOS=0,1;IQ=1085.91;MATEID=gridss108fb_5212o;MQ=60;MQN=60;MQX=60;RAS=2;RASQ=3119.04;REF=162;REFPAIR=115;RP=0;RPQ=0;SB=0.4484127;SC=2X94M;SR=5;SRQ=182.51;SVTYPE=BND;VF=68;TAF=0.5,0.5037;LOCAL_LINKED_BY=;REMOTE_LINKED_BY=	GT:AF:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:94:33:0:0:0:0:0	.:0.5:2793.03:0:170:0:0:0:0:0:0:0:670.35:25:670.35:0:0:14:0:32:1085.91:7180.49:3119.04:68:82:0:0:5:182.51:68

Thank you,
Tingting

**Comment by d-cameron** [comment]
The threshold between indel and SV is completely arbitrary. GRIDSS defaults to 10bp because the commonly accepted threshold of 50bp is problematic since it overlaps a somatic small dup mutational signature (https://www.biorxiv.org/content/10.1101/2020.12.03.410860v1).

Having said that, GRIDSS does get noisier for these small event as it doesn't explicitly handing microsatellites so the assembly isn't as good due to the combination of low complexity sequence and PCR stutter.

**Comment by tgong1** [comment]
Thank you Daniel for the clarification. I'll be careful when I report and/or analyse indels and SVs.
