### ISSUE TITLE
v2.13.0 - clean docker build fails

### ISSUE THREAD

**Issue by keiranmraine** [PapenfussLab/gridss#548]
Hi,

We appreciate the work on this to resolve the issue we were seeing, however it still isn't possible to get a clean build based on the tag:

```
$ git status
HEAD detached at v2.13.0
nothing to commit, working tree clean
$ docker build --no-cache .
Sending build context to Docker daemon  32.44MB
Step 1/69 : ARG UBUNTU_VERSION=20.04
...
Step 11/69 : RUN cd /opt/gridss/src/main/c/gridsstools/htslib && 	autoreconf -i && ./configure && make -j 8 && 	cd .. && 	autoreconf -i && ./configure && make -j 8 && 	cp gridsstools /opt/gridss/
 ---> Running in c95241df0c66
autoreconf: 'configure.ac' or 'configure.in' is required
The command '/bin/sh -c cd /opt/gridss/src/main/c/gridsstools/htslib && 	autoreconf -i && ./configure && make -j 8 && 	cd .. && 	autoreconf -i && ./configure && make -j 8 && 	cp gridsstools /opt/gridss/' returned a non-zero code: 1
```

**Comment by d-cameron** [comment]
How clean? There's a couple of additional steps needed after doing a git clone to get the working directory into a state buildable by docker. Specifically, these lines of https://github.com/PapenfussLab/gridss/blob/master/scripts/dev/create_release.sh:

```
(cd src/main/c/gridsstools && make clean)
(cd src/main/c/gridsstools/htslib && make clean)
(cd src/main/c/gridsstools && git submodule update --init --recursive) # htscodecs gets deleted by the clean - we need 
```

**Comment by keiranmraine** [comment]
Ah, okay thanks.  It would be really good if at some point this could be made to work entirely within the dockerfile.

The following appears to work cleanly as docker only affects the "imported" data, so you can re-copy the repo version of the htslib even if it is deleted during the image building.

Update docker file (cleans included, but first one fails so commented):

```diff
diff --git a/Dockerfile b/Dockerfile
index debef817..24855f42 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -25,6 +25,9 @@ RUN mkdir /opt/gridss/
 ARG GRIDSS_VERSION
 COPY src/main/c /opt/gridss/src/main/c
 COPY src/test/resources /opt/gridss/src/test/resources
+# RUN cd /opt/gridss/src/main/c/gridsstools && make clean # fails: make: *** No rule to make target 'clean'.  Stop.
+RUN cd /opt/gridss/src/main/c/gridsstools/htslib && make clean
+COPY src/main/c/gridsstools/htslib /opt/gridss/src/main/c/gridsstools/htslib
 RUN cd /opt/gridss/src/main/c/gridsstools/htslib && \
        autoreconf -i && ./configure && make -j 8 && \
        cd .. && \
```

```bash
$ git clone --recurse-submodules --branch v2.13.0 git@github.com:PapenfussLab/gridss.git
$ cd gridss
$ docker build --no-cache .
```

All tests successful:

```
Results :

Tests run: 1542, Failures: 0, Errors: 0, Skipped: 29
...
Step 71/71 : COPY --from=gridss /opt/gridss/* /
 ---> fa6c0480dddc
Successfully built fa6c0480dddc
```

With this in place you can have CI (setup to recurse-submodules) automatically push the images on tagging.

**Comment by d-cameron** [comment]
Would it make sense to refactor the docker to run entirely off github and ignore the local environment?

**Comment by keiranmraine** [comment]
The Dockerfile should run ideally from a clean checkout (recursive in this case), this is the best way to allow integration with CI platforms to auto build on PR or tagging (which can auto push to dockerhub).  Example [here](https://github.com/cancerit/pycroquet/blob/develop/.circleci/config.yml), I'm sure this can be achieved with github actions too.  This way you always have the assurance that a clean/uncached build is validated before you release.

You can change the dockerfile to curl the code bundle, but you won't get the submodules and it's rife with issues of missing version updates (at a minimum ensure you've an `ARG` that can accept tag or commit-sha).

**Comment by d-cameron** [comment]
>The Dockerfile should run ideally from a clean checkout

It already does (as long as the checkout is recursive). The `make clean` and `git submodule update --init --recursive` steps are only needed in `create_release.sh` to ensure that no local development build artifacts are present when building.

**Comment by d-cameron** [comment]
Docker image creation is now part of the CI.
