### ISSUE TITLE
Fail to run virusbreakend and gridss from v2.13.0 dockerhub image

### ISSUE THREAD

**Issue by YingYa** [PapenfussLab/gridss#550]
The lasted version could not run neither with internal samtools (v1.10) nor with external samtool (v1.14).

Tue Dec  7 00:15:09 CST 2021: Full log file is: /workingdir/test.virusbreakend.vcf.gz.virusbreakend.working/virusbreakend.20211207_001509.cngb-compute-f8-17.cngb.sz.hpc.4648.log
Tue Dec  7 00:15:09 CST 2021: Found /usr/bin/time
Tue Dec  7 00:15:09 CST 2021: Using GRIDSS jar /opt/gridss/gridss-2.13.0-gridss-jar-with-dependencies.jar
Tue Dec  7 00:15:09 CST 2021: Using reference genome "/referencedir/Homo_sapiens_assembly38.fasta"
Tue Dec  7 00:15:09 CST 2021: Using output VCF /workingdir/test.virusbreakend.vcf.gz
Tue Dec  7 00:15:09 CST 2021: Using 4 worker threads.
Tue Dec  7 00:15:09 CST 2021: Using input file /indir/test.cram
Tue Dec  7 00:15:09 CST 2021: Found /opt/kraken2/kraken2
Tue Dec  7 00:15:09 CST 2021: Found /opt/gridss//gridss
Tue Dec  7 00:15:09 CST 2021: Found /opt/gridss//gridss_annotate_vcf_kraken2
Tue Dec  7 00:15:09 CST 2021: Found /opt/gridss//gridss_annotate_vcf_repeatmasker
Tue Dec  7 00:15:09 CST 2021: Found /share/app/samtools/v1.14/bin/samtools
Tue Dec  7 00:15:09 CST 2021: Found /share/app/samtools/v1.14/bin/bcftools
Tue Dec  7 00:15:09 CST 2021: Found /usr/bin/java
Tue Dec  7 00:15:09 CST 2021: Found /usr/bin/bwa
Tue Dec  7 00:15:09 CST 2021: Found /usr/bin/Rscript
Tue Dec  7 00:15:09 CST 2021: Found /opt/RepeatMasker/RepeatMasker
Tue Dec  7 00:15:09 CST 2021: Found /opt/gridss//gridsstools
Tue Dec  7 00:15:09 CST 2021: gridsstools version: gridsstools 1.0
Tue Dec  7 00:15:09 CST 2021: Your samtools version is so old it does not support --version-only. Update samtools.

Tue Dec  7 06:32:17 CST 2021: Full log file is: /workingdir/gridss.full.20211207_063217.cngb-compute-f23-9.cngb.sz.hpc.78471.log
Tue Dec  7 06:32:17 CST 2021: Found /usr/bin/time
Tue Dec  7 06:32:17 CST 2021: Using GRIDSS jar /opt/gridss/gridss-2.13.0-gridss-jar-with-dependencies.jar
Tue Dec  7 06:32:17 CST 2021: Using reference genome "/referencedir/Homo_sapiens_assembly38.fasta"
Tue Dec  7 06:32:17 CST 2021: Using output VCF /workingdir/test-T.gridss.driver.vcf.gz
Tue Dec  7 06:32:17 CST 2021: Using assembly bam /workingdir/test-N-VS-test-T.assembly.bam
Tue Dec  7 06:32:17 CST 2021: Using 8 worker threads.
Tue Dec  7 06:32:17 CST 2021: Using blacklist /database/ENCFF001TDO.bed
Tue Dec  7 06:32:18 CST 2021: Using JVM maximum heap size of 30g for assembly and variant calling.
Tue Dec  7 06:32:18 CST 2021: Using input file /indir/test-N.realn.cram
Tue Dec  7 06:32:18 CST 2021: Using input file /indir/test-T.realn.cram
Tue Dec  7 06:32:18 CST 2021: Found /usr/bin/Rscript
Tue Dec  7 06:32:18 CST 2021: Found /share/app/samtools/v1.14/bin/samtools
Tue Dec  7 06:32:18 CST 2021: Found /usr/bin/java
Tue Dec  7 06:32:18 CST 2021: Found /share/app/bwa/0.7.17/bwa
Tue Dec  7 06:32:18 CST 2021: Your samtools version is so old it does not support --version-only. Update samtools.

**Comment by keiranmraine** [comment]
Same as #549
