### ISSUE TITLE
AnnotateInsertedSequence cannot complete

### ISSUE THREAD

**Issue by vragkousis** [PapenfussLab/gridss#554]
Hello!

I am using virusbreakend with the default bwa aligner and I can't get past the AnnotateInsertedSequence step. Please let me know what this log file suggests the problem is.

[virusbreakend.20211219_193215.OGpowerhouse.62447.log](https://github.com/PapenfussLab/gridss/files/7741271/virusbreakend.20211219_193215.OGpowerhouse.62447.log)

**Comment by d-cameron** [comment]
Looks like you're missing `/home/vragkousis/Desktop/Tools/Genomes/hg38.fa.dict`. Running `gridss -s setupreference -r /home/vragkousis/Desktop/Tools/Genomes/hg38.fa` should create it.
