### ISSUE TITLE
SVlen

### ISSUE THREAD

**Issue by pengyan19** [PapenfussLab/gridss#558]
hello,when i use the binary gridss, software,i find that this did't have SVlen label in vcf when i annotation the vcf . so i remove the code as follows .it's right ?
"info(vcf[gr$sourceId])$SVLEN <- gr$svLen"

<img width="788" alt="1643118528(1)" src="https://user-images.githubusercontent.com/57850987/150989039-5873ea6a-cc19-4c1e-ae66-79d303f56d4b.png">

**Comment by d-cameron** [comment]
That's fine.

`breakpointRanges()` from the `StructuralVariantAnnotation` package adds a `svLen` field to the breakpoint `GRanges` object. The likely issue is that GRIDSS no longer writes a `SVLEN` VCF header so you'd have to add that in before writing the annotated vcf.
