### ISSUE TITLE
CollectMultipleSequenceMetrics

### ISSUE THREAD

**Issue by brentp** [PapenfussLab/gridss#562]
Hi Daniel, I arrived here from https://github.com/broadinstitute/picard/issues/1277

 I'd like to get the speedup on CollectMultipleSequenceMetrics. Is there anything I should be aware of before relying on your fork? Differences?

thanks,
-Brent

**Comment by d-cameron** [comment]
Should be a simple drop-in replacement. Only difference is that you'll need to explicitly state the jar main entry point that you want to use when using the GRIDSS jar. The only differences to the picard codepaths are the performance optimisations I've added. The gridss.CollectGridsssMetrics class used in the gridss preprocessing step is literally a subclass of picard.analysis.CollectMultipleMetrics.
