### ISSUE TITLE
Does gridss use log4j

### ISSUE THREAD

**Issue by JenniferShelton** [PapenfussLab/gridss#564]
Hi,

I was wondering if gridss uses [log4j or a gatk version that uses log4j](https://gatk.broadinstitute.org/hc/en-us/articles/4412955012379-Important-GATK-version-update-required-to-address-Log4j-security-vulnerability)? Could a release be created without log4j to get around the security issue?

Thanks,
Jennifer

**Comment by d-cameron** [comment]
See https://github.com/PapenfussLab/gridss/releases/tag/v2.13.2 release notes.
