### ISSUE TITLE
Can I split individual fastq files based on lane ID? 

### ISSUE THREAD

**Issue by YiBenqiu** [PapenfussLab/gridss#568]
> Hello！

>  I am preparing to use GRIDSS for SV detection, but there is a place in the documentation that makes me a little confused.

> "Input files containing read groups from multiple different libraries should be split into an input file per-library"

>  If an individual's fastq file has the same run ID and flowcell ID but different lane IDs, do I need to split the individual according to the lane ID? Sorry, I'm not very clear about the term "library".
![image](https://user-images.githubusercontent.com/57091259/157045110-ea8c427c-feca-4aa0-8279-b411143c5c1d.png)

> If I split according to lane ID, is this the wrong operation?

**Comment by YiBenqiu** [comment]
So now I need to use samtools to merge the bam file obtained by splitting the individual according to the lane ID into a bam, right?

**Comment by d-cameron** [comment]
GRIDSS will work either way but it's best to merge so steps before GRIDSS such as marking duplicates will work correctly.
