### ISSUE TITLE
Error in gridss_somatic_filter

### ISSUE THREAD

**Issue by jungsoo080** [PapenfussLab/gridss#571]
Hello, I've just finished calling SV with tumor only samples and pondir directory and files were generated using gridss.GeneratePonBedpe.

Now the problem is the error shown as below.

gridss_somatic_filter --pondir pondir --input gridss_call_sv.vcf --output high_confidence_somatic.vcf.gz --fulloutput high_and_low_confidence_somatic.vcf.gz --scriptdir $(scriptdir) -t 1 -n 0

The following have been reloaded with a version change:
  1) GCCcore/7.3.0 => GCCcore/10.2.0                             4) bzip2/1.0.6-GCCcore-7.3.0 => bzip2/1.0.8-GCCcore-10.2.0     7) zlib/1.2.11-GCCcore-7.3.0 => zlib/1.2.11-GCCcore-10.2.0
  2) SAMtools/1.9-foss-2016b => SAMtools/1.13-GCCcore-10.2.0     5) cURL/7.60.0-GCCcore-7.3.0 => cURL/7.72.0-GCCcore-10.2.0
  3) XZ/5.2.4-GCCcore-7.3.0 => XZ/5.2.5-GCCcore-10.2.0           6) ncurses/6.1-GCCcore-7.3.0 => ncurses/6.2-GCCcore-10.2.0

Test passed 😀
Test passed 🎊
No reference genome supplied using --ref. Not performing variant equivalence checks.
2022-03-13 15:56:51 Reading gridss_call_sv.vcf
Tumour samples: tumor.bam
Matched normals: 
Warning messages:
1: In NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,  :
  subscript is an array, passing it thru as.vector() first
2: In NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,  :
  subscript is an array, passing it thru as.vector() first
3: In NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,  :
  subscript is an array, passing it thru as.vector() first
4: In NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,  :
  subscript is an array, passing it thru as.vector() first
2022-03-13 15:58:13 Parsing single breakends gridss_call_sv.vcf
2022-03-13 15:58:14 Calculating single breakend VAF gridss_call_sv.vcf
2022-03-13 15:58:14 Filtering single breakends gridss_call_sv.vcf
2022-03-13 15:58:14 Loading from cache  pondir/gridss_pon_single_breakend.bed.cached.parsed.rds
2022-03-13 15:58:15 Parsing breakpoints gridss_call_sv.vcf
2022-03-13 15:58:15 Calculating breakpoint VAF gridss_call_sv.vcf
2022-03-13 15:58:16 Filtering breakpoints gridss_call_sv.vcf
**Error in DataFrame(..., check.names = FALSE) : 
  different row counts implied by arguments
Calls: gridss_breakpoint_filter ... cached_read_file -> read_function -> GRanges -> DataFrame**
Execution halted

So I want to know what the problem is.... thank you!

**Comment by d-cameron** [comment]
Can you supply either the problematic VCF, or rerun the filtering script with debuggin enabled? Unfortunately, that error log is insufficiently detailed for me to tell you the root cause and why you're seeing that error.

Your other option is to use the Hartwig GRIPSS somatic filtering tool (https://github.com/hartwigmedical/hmftools/tree/master/gripss). It's based on `gridss_somatic_filter` and does pretty much the same thing (the Hartwig version has a few extra features).

**Comment by jungsoo080** [comment]
Thank you for the kind answer!
I think I solved the problem just right now!
I made PON of gridss.GeneratePonBedpe with the somatic SV called vcf, not the original sample's vcf and that was the problem I think...
I'd close this issue.

**Comment by sainadfensi** [comment]
Hi,
I'm bit confused. According to the posts, the PoN is made from somatic VCF rather than germline VCF?
