### ISSUE TITLE
Run complete with 19 warnings and 3 errors.

### ISSUE THREAD

**Issue by zongzone** [PapenfussLab/gridss#574]
I've run it to completion, but it reminds me of the following, is there something wrong? Or does it not affect my results?
![image](https://user-images.githubusercontent.com/101814626/161407712-6023b306-8ab8-4de9-a210-f88d67b559a8.png)

**Comment by d-cameron** [comment]
>is there something wrong? Or does it not affect my results?

You'll need to check the full log file (it's in the working directory) to see if the errors are important. They may be as unimportant as a cache directory not being writeable, or be more serious errors.

**Comment by zongzone** [comment]
![image](https://user-images.githubusercontent.com/101814626/161466393-d14cf1d3-c1e6-49f5-bd65-a16a79489846.png)
![image](https://user-images.githubusercontent.com/101814626/161466543-ef2b2375-564d-4fce-a05b-e75e9b2bf9a0.png)
 I found this information in the log, thanks for your answer
