### ISSUE TITLE
timecmd java -Xmx$otherjvmheap $jvm_args -cp $gridss_jar gridss.PrepareReference REFERENCE_SEQUENCE=$reference 1>&2 2>> $logfile

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [PapenfussLab/gridss#575]
hello, i run the gridss for sv calling ,but its error, wuold you help me to debug ? thank you 

gridss --reference /public/home/yjhuang/jjzhang/RNA_seq/raw_data/resequencing/referencehemp.fna --output txt.vcf.gz -a  test_assembluped.bam
Using working directory "."
Mon Apr  4 09:43:14 CST 2022: Full log file is: ./gridss.full.20220404_094314.login02.3472.log
Mon Apr  4 09:43:14 CST 2022: Found /usr/bin/time
Mon Apr  4 09:43:14 CST 2022: Using GRIDSS jar /public/home/yjhuang/anaconda3/envs/gridss2_benchmark_sim/share/gridss-2.11.1-1/grids
Mon Apr  4 09:43:14 CST 2022: Using reference genome "/public/home/yjhuang/jjzhang/RNA_seq/raw_data/resequencing/referencehemp.fna"
Mon Apr  4 09:43:14 CST 2022: Using output VCF txt.vcf.gz
Mon Apr  4 09:43:14 CST 2022: Using assembly bam  test_assembly.bam
Mon Apr  4 09:43:14 CST 2022: Using 8 worker threads.
Mon Apr  4 09:43:14 CST 2022: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Mon Apr  4 09:43:14 CST 2022: Using JVM maximum heap size of 30g for assembly and variant calling.
Mon Apr  4 09:43:14 CST 2022: Using input file SRR14708197_deduped.bam
Mon Apr  4 09:43:14 CST 2022: Found /public/home/yjhuang/anaconda3/envs/gridss2_benchmark_sim/bin/Rscript
Mon Apr  4 09:43:14 CST 2022: Found /public/home/yjhuang/anaconda3/envs/gridss2_benchmark_sim/bin/samtools
Mon Apr  4 09:43:14 CST 2022: Found /public/home/yjhuang/anaconda3/envs/gridss2_benchmark_sim/bin/java
Mon Apr  4 09:43:14 CST 2022: Found /public/home/yjhuang/anaconda3/envs/gridss2_benchmark_sim/bin/bwa
Mon Apr  4 09:43:14 CST 2022: samtools version: 1.11+htslib-1.11
Mon Apr  4 09:43:14 CST 2022: R version: R scripting front-end version 4.1.2 (2021-11-01)
Mon Apr  4 09:43:14 CST 2022: bwa Version: 0.7.17-r1188
Mon Apr  4 09:43:14 CST 2022: time version: GNU time 1.7
Mon Apr  4 09:43:14 CST 2022: bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Mon Apr  4 09:43:15 CST 2022: java version: openjdk version "11.0.1" 2018-10-16 LTS	OpenJDK Runtime Environment Zulu11.2+3 (buil mixed mode)	
Mon Apr  4 09:43:15 CST 2022: Max file handles: 4096
Mon Apr  4 09:43:15 CST 2022: Running GRIDSS steps: setupreference, preprocess, assemble, call,
Mon Apr  4 09:43:15 CST 2022: Running	PrepareReference	(once-off setup for reference genome)
"$timecmd java -Xmx$otherjvmheap $jvm_args -cp $gridss_jar gridss.PrepareReference REFERENCE_SEQUENCE=$reference 1>&2 2>> $logfile" 
*****
The underlying error message can be found in ./gridss.full.20220404_094314.login02.3472.log
*****

**Comment by Jiangjiangzhang6** [comment]
![image](https://user-images.githubusercontent.com/101324838/161520340-cdbdaa45-2353-48b8-a367-e87c1ec3ddfc.png)
 the reference , I have indexed by samtools many times 
![image](https://user-images.githubusercontent.com/101324838/161520485-2b7b5d31-f97e-43da-9caa-608a7109724b.png)
but the error also showd this

**Comment by Jiangjiangzhang6** [comment]
referencehemp.fna.tmp.gridsslock
this dirctionary each time error need to delete 
thanks for helping

**Comment by Jiangjiangzhang6** [comment]
hello, the error didnot solved? my friend

**Comment by Jiangjiangzhang6** [comment]
I wait for your replay

**Comment by d-cameron** [comment]
>referencehemp.fna.tmp.gridsslock

The leftover lock happens when the setupreference step fails.

The error you've posted is because the .fai index file can't be created. The actual root cause (not being able to create .fai index) error is further up in the logfile.

Usually the issue is that you don't have write permissions to the directory where your .fna file is so you can't create the .fai file. Other possibilities are that your .fna file is malformed.

**Comment by Jiangjiangzhang6** [comment]
yeah, every time create the index by samtools , everytime show it down, but the error show the same error, so my friend, If I want to run this software without the root authority, any other approaches would slove the mistake?
Waiting for your reply.

**Comment by d-cameron** [comment]
GRIDSS requires once-off write access to the reference genome directory.
Either copy the reference fasta to a location you do have write access to,
or change the permissions on the directory that it is in.
