### ISSUE TITLE
when there are multiple samples in group.vcf for "gridss_somatic_filter"

### ISSUE THREAD

**Issue by mjko1210** [PapenfussLab/gridss#576]
Hi,
I have group.vcf after gridss_call steps. There are 4 samples mentioned in VCF header.

```
> head(geno(raw_vcf)$VF)
                 VY01JHU528_1N VY01JHU528_1T VY01JHU528_2N
gridss0ff_29688o                 0                 5                 8
gridss0ff_29688h                 0                 5                 8
gridss1f_24781b                  0                 0                 0
gridss2f_50856b                  0                 0                 0
gridss2f_126333b                 0                 0                 0
gridss3ff_19683o                 0                 1                 6
                 VY01JHU528_2T
gridss0ff_29688o                15
gridss0ff_29688h                15
gridss1f_24781b                  0
gridss2f_50856b                  0
gridss2f_126333b                 0
gridss3ff_19683o                 7
```
However, when I use `--normalordinal 1 --tumourordinal 2`, it only takes first two samples. I wonder if I can modify this to `--normalordinal c(1,3) --tumourordinal c(2,4)` so that it performs somatic filter for two matched normal-tumor pairs: (1 and 2) and (3 and 4).

Or, does it require to separate vcf into two (one vcf for 1 and 2 only, the other vcf for 3 and 4 only) before run this script?

I am confused because previous assembly and call steps were performed jointly (all samples together).

Thanks!

**Comment by d-cameron** [comment]
> I am confused because previous assembly and call steps were performed jointly (all samples together).

Assembly and variant calling are performed jointly, but both steps include a per-sample breakdown.

> so that it performs somatic filter for two matched normal-tumor pairs: 

If they're different patients you'd run it twice. If it's multi-region sequencing from the same patient then that is supported. If it's multiple sequencing runs of the same samples then they should be merged into the same VCF column using `gridss --labels`.

> `I wonder if I can modify this to --normalordinal c(1,3) --tumourordinal c(2,4)`

I believe the `R/argparser` syntax is `--normalordinal 1 --normalordinal 3 --tumourordinal 2 --tumourordinal 4`

**Comment by mjko1210** [comment]
Thanks for quick reply! So first two (N-T) pairs are from the same patient and later two are from different patient.
So do you mean I can still run these 4 samples at once (altogether) with gridss `assembly` and `call`?
For example,

> gridss -s assemble -a assembly.bam 1.bam 2.bam 3.bam 4.bam
> gridss -s call -a assembly.bam 1.bam 2.bam 3.bam 4.bam -o group.vcf


And then run `gridss_somatic_filter` twice by separating vcf files into same patients? (For example, `vcf1` to contain 1 and 2 only, `vcf2` for 3 and 4 only).

If this is not what you suggested, I wonder if it's more about running gridss twice for each step.
> gridss -s assemble -a assembly1.bam 1.bam 2.bam
> gridss -s call -a assembly1.bam 1.bam 2.bam -o group1.vcf

> gridss -s assemble -a assembly2.bam 3.bam 4.bam
> gridss -s call -a assembly2.bam 3.bam 4.bam -o group2.vcf

and run `gridss_somatic_filter` for each group1.vcf and group2.vcf.

I would appreciate if you can help me with clarification here.

**Comment by d-cameron** [comment]
> So do you mean I can still run these 4 samples at once (altogether)

You can.

> And then run gridss_somatic_filter twice by separating vcf files into same patients?

Yes, but you'll still have 4 columns in your VCF. It's just that the 1/2 output VCF will be subset to the ones that are somatic in 2, and the 3/4 are the ones that are somatic in 4.

>If this is not what you suggested, I wonder if it's more about running gridss twice for each step.

If they're unrelated samples, then the usual workflow is to run them separately. In this case, that would be running GRIDSS on 1/2, and running again on 3/4. `--normalordinal` and `--tumourordinal` are typically only used for more complex experimental designs such as when you take multiple samples (e.g. primary + mets) from the same patient, or longitudinal mouse xenograft experiments.
