### ISSUE TITLE
Cell-free DNA low-frequency variants

### ISSUE THREAD

**Issue by stsergbg** [PapenfussLab/gridss#579]
Hi,

Do you have any particular advice on optimizing GRIDSS (or further filtering with GRIPSS) for low-frequency SV calling, such as analyzing cell-free DNA data for somatic (or one-sample) SV calling?

**Comment by d-cameron** [comment]
I haven't tried it myself so I can't recommend any particular optimisations but I expect you'll have two issues. Firstly, the QUAL score filtering will likely be too aggressive (weak signal from the low AF is further compounded by the short fragment length of cfDNA reducing the read pair signal) so you'll need to drop that threshold. Secondly, the lack of a matched normal will make it difficult to separate the low AF TPs from the noise.

If I were doing this analysis, I would do joint calling on multiple unrelated samples to help reduce this noise. A low AF SV found in multiple samples is likely to be systematic noise.

**Comment by d-cameron** [comment]
I'd still be using a PON, it's just that joint calling will pick up some of the low-level SV noise that wasn't strong enough in any individual sample to make it into the PON.

**Comment by d-cameron** [comment]
Detection of low AF samples is always a trade-off between sensitivity and specificity. Reducing `MINIMUM_TUMOR_QUAL` lets to make the choice to be more sensitive. I wouldn't remove it entirely as full GRIDSS output is very sensitive/spammy.

If you have related samples (e.g. you're trying to detect tumour relapse) then you should definitely do joint calling with the initially sequenced tumour as you can do very sensitive (i.e. single read) detection of SVs that are known to occur in the tumour.
