### ISSUE TITLE
virusbreakend output files

### ISSUE THREAD

**Issue by MjelleLab** [PapenfussLab/gridss#587]
Hi,
I wonder how I can combine the vcf and summary output from virusbreakend so that I can get information on the species and the chromosomal position of the insertion. I cannot find the species (virus) in the VCF file that contains the chromosome position.

**Comment by d-cameron** [comment]
> I cannot find the species (virus) in the VCF file that contains the chromosome position

The NCBI taxonomy ID of the virus is in the `INSTAXID` field.

The actual fasta sequence for the viral contig will be in:
{virusbreakend_db}/library/viral/library.fna
or 
{virusbreakend_db}/library/added/*.fna

Where it is located depends on whether the best viral sequence match was the RefSeq exemplar sequence, or one of the NCBI neighbour sequences.

For more information, see https://github.com/PapenfussLab/gridss/blob/master/VIRUSBreakend_Readme.md#reference-data-contents. Depending on your workflow, you may also be interested in the seqid2taxid.map or taxid10239.nbr reference files.
