### ISSUE TITLE
Two large genomes

### ISSUE THREAD

**Issue by Karimi-81** [PapenfussLab/gridss#598]
Hi there,
I wonder if it is possible to use gridss to find re-arrangements between two chromosome-level genome assemblies. I would appreciate it if you could guide me.

**Comment by d-cameron** [comment]
GRIDSS is designed to detect rearrangements from a sample sequenced with short reads against a single reference genome. Is it not designed for assembly-to-assembly rearrangement detection.

These sort of assembly-level comparison are best using one of the comparative genomics tools designed for this purpose.
