### ISSUE TITLE
Error in assembly step

### ISSUE THREAD

**Issue by senzhaocode** [PapenfussLab/gridss#604]
Hello gridss developer, 

Thank you for developing this tool. Now I am using it to do SV calling on WGS data (tumor - 100X and normal 50X pair). I experienced a few error reports during assemble step. For example, see attached figure.  
1). Traversal of kier length ending at [X, Y] contains an invalidate subnode.....
2). Sanity check failure: found path with no support.....

These errors were reported in earlier opened issues, and I thought that they were supposed to be fixed? Could you help me sort it out. Thanks again. 
<img width="1246" alt="Screenshot 2022-10-25 at 13 59 34" src="https://user-images.githubusercontent.com/26706345/197768897-d7beaddb-44a3-4ba6-9c49-412376b83f43.png">
<img width="1238" alt="Screenshot 2022-10-25 at 13 59 17" src="https://user-images.githubusercontent.com/26706345/197768902-a58d295b-4f88-4f36-9c36-ea1f074d6c62.png">

**Comment by d-cameron** [comment]
> These errors were reported in earlier opened issues, and I thought that they were supposed to be fixed? Could you help me sort it out. Thanks again.

These are unlikely to ever get fixed the issues don't reproduce on a subset of the data (thus making debugging extremely difficult) and the graph unload/reload work-around that is triggered fixes the immediate issue without loss.

If the reload actually triggers another fail thus a total failure of assembly (as opposed to these error messages but a successful assembly) then please send through the generated debugging file (in a subdirectory of the assembly.bam.gridss.working/ directory) as that contains the minimal subset of data for reproducing the error.
