### ISSUE TITLE
Gridss sv calling in non-illumina technologies

### ISSUE THREAD

**Issue by DomManou** [PapenfussLab/gridss#607]
Hello, 

I would like to run GRIDSS for SV calling on short-read sequencing data. However, my dataset is not produced through Illumina technologies (DNBseq-BGI). To "test the waters", I ran GRIDSS on a test sample. Although the software runs, the output .vcf file contains only "SVTYPE=BND". 

I am wondering whether the vcf output reflects an issue arising from the sequencing output. If so, have you found/could there be  a way to adjust the software for non-illumina sequencing output (e.g. through SAMtags etc)?  Any help is greatly appreciated :) 

Best regards,
Domniki

**Comment by d-cameron** [comment]
We have successfully used gridss on BGI data in the past.

All gridss calls are in breakend notation - this is expected behaviour.
See https://github.com/PapenfussLab/gridss#why-are-all-calls-bnd for
details.
