### ISSUE TITLE
Could not find or load main class au.edu.wehi.idsv.Idsv in 1.2.4 release

### ISSUE THREAD

**Issue by datakid** [PapenfussLab/gridss#61]
[root@vmpr-res-head-node gridss]# java -Xmx31g -jar /config/binaries/gridss/1.2.4/gridss.jar       
Error: Could not find or load main class au.edu.wehi.idsv.Idsv

[root@vmpr-res-head-node gridss]# /usr/bin/java -version                                                                                                                                 
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

Note: also didn't work with module java

[root@vmpr-res-head-node gridss]# java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

cheers
L.

**Comment by d-cameron** [comment]
Fixed in 291479311b0302d7695a689868a55e49508558e8
