### ISSUE TITLE
PONs from joint-calling or merge VCFs?

### ISSUE THREAD

**Issue by mnshgl0110** [PapenfussLab/gridss#619]
Hi,

I have multiple samples from couple of tissues. I want to call variants in sample of one tissue while considering the samples from other tissue as "normal" and vice-versa.

Could you please let me know what is the correct strategy to create the PONs? Specifically, should I first do joint-calling on all samples from a tissue and then create PON from the single (multi-sample) VCF file? Or, should I get individual VCF file for each sample from a tissue and then merge them to create PON as the code in README suggests?

Best
Manish

**Comment by d-cameron** [comment]
If you're comparing multiple related samples then there's no need for a PON. Perform joint calling on all samples then you can filter to sample-specific variants by looking at the support breakdown for each sample through the FORMAT VF field.

That is, the FORMAT VF field gives you a breakdown of the support for that variant by sample. If a variant is common to all samples then VF > 0 for all samples and a private sample will have VF=0 ^ except for the sample that it occurs in.


^ Be aware that crosss-contamination and subclonality can result in low but non-zero VF. Non-zero VF can also occur by chance for small variants (e.g. <1kbp deletion) when a reference read pair fragment just happens to be very large.
