### ISSUE TITLE
gridss assembly

### ISSUE THREAD

**Issue by vitty0513** [PapenfussLab/gridss#628]
Dear,
I met lots of WARNING when I run: gridss -s assemble --reference $ref --jobindex 0 --jobnodes 10 -a assembly.bam --threads 8 --jar /home/banliping/WORKSPACE/dwt/software/gridss-2.13.2-gridss-jar-with-dependencies.jar input1.bam input2.bam input3.bam ......
Like these:
WARNING 2023-06-01 16:51:22     PositionalAssembler     Forcing downsampling around LG15:13154045-13154054 since probabilistic downsampling failed.
WARNING 2023-06-01 16:51:26     PositionalAssembler     Forcing downsampling around LG15:13154045-13154054 since probabilistic downsampling failed.
WARNING 2023-06-01 16:51:28     PositionalAssembler     Forcing downsampling around LG15:13154045-13154054 since probabilistic downsampling failed.
WARNING 2023-06-01 16:51:29     PositionalAssembler     Forcing downsampling around LG15:13154045-13154054 since probabilistic downsampling failed.
WARNING 2023-06-01 16:51:31     PositionalAssembler     Forcing downsampling around LG15:13154045-13154054 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:16     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:24     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:29     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:30     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:31     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:31     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 16:59:34     PositionalAssembler     Forcing downsampling around LG4:11939830-11939862 since probabilistic downsampling failed.
WARNING 2023-06-01 17:00:38     PositionalAssembler     Forcing downsampling around LG30:660125-660174 since probabilistic downsampling failed.
WARNING 2023-06-01 17:01:07     PositionalAssembler     Forcing downsampling around LG30:660125-660174 since probabilistic downsampling failed.
WARNING 2023-06-01 17:01:20     PositionalAssembler     Forcing downsampling around LG30:660125-660174 since probabilistic downsampling failed.
WARNING 2023-06-01 17:01:26     PositionalAssembler     Forcing downsampling around LG30:660125-660174 since probabilistic downsampling failed.
WARNING 2023-06-01 17:22:51     PositionalAssembler     Forcing downsampling around LG30:1153281-1153282 since probabilistic downsampling failed.
WARNING 2023-06-01 17:24:25     PositionalAssembler     Forcing downsampling around LG9:17396164-17396283 since probabilistic downsampling failed.
INFO    2023-06-01 21:52:18     AssemblyEvidenceSource  Completed assembly on chunk 7 (LG4:2414868-LG4:12414867) in 36055s (10.02 h)
INFO    2023-06-01 21:52:18     SAMFileUtil     Sorting ./assembly.bam.gridss.working/gridss.tmp.assembly.bam.assembly.chunk7.bam
INFO    2023-06-01 22:54:34     AssemblyEvidenceSource  Completed assembly on chunk 17 (LG9:8151586-LG10:227327) in 39792s (11.05 h)
INFO    2023-06-01 22:54:34     SAMFileUtil     Sorting ./assembly.bam.gridss.working/gridss.tmp.assembly.bam.assembly.chunk17.bam
INFO    2023-06-01 23:37:42     AssemblyEvidenceSource  Completed assembly on chunk 27 (LG15:4611247-LG15:14611246) in 42380s (11.77 h)
INFO    2023-06-01 23:37:42     SAMFileUtil     Sorting ./assembly.bam.gridss.working/gridss.tmp.assembly.bam.assembly.chunk27.bam
WARNING 2023-06-02 00:45:26     PositionalAssembler     Forcing downsampling around LG22:3023671-3023697 since probabilistic downsampling failed.
INFO    2023-06-02 00:58:18     AssemblyEvidenceSource  Completed assembly on chunk 37 (LG21:8159015-LG22:3430381) in 47216s (13.12 h)
INFO    2023-06-02 00:58:18     SAMFileUtil     Sorting ./assembly.bam.gridss.working/gridss.tmp.assembly.bam.assembly.chunk37.bam
INFO    2023-06-02 01:39:32     AssemblyEvidenceSource  Completed assembly on chunk 47 (LG29:2534334-LG30:4441378) in 49690s (13.80 h)
INFO    2023-06-02 01:39:32     SAMFileUtil     Sorting ./assembly.bam.gridss.working/gridss.tmp.assembly.bam.assembly.chunk47.bam
INFO    2023-06-02 01:40:00     AssemblyEvidenceSource  Breakend assembly complete.
INFO    2023-06-02 01:40:00     AssemblyEvidenceSource  Breakend assembly complete (node 7, 10 total)
INFO    2023-06-02 01:40:00     AssemblyEvidenceSource  Not merging assembly files since not all chunks were assembled.
[Fri Jun 02 01:40:00 CST 2023] gridss.AssembleBreakends done. Elapsed time: 828.75 minutes.
Runtime.totalMemory()=28055699456
Fri Jun  2 01:40:05 CST 2023: Assembly processing for job index 7 complete.
Fri Jun  2 01:40:06 CST 2023: To perform the gather/reduce after all jobs are complete, run assembly without specifying --jobnodes.

What does "Forcing downsampling" mean? Is this warning important? And will it affect my results?

**Comment by d-cameron** [comment]
> What does "Forcing downsampling" mean?

It means the assembly graph got too complicated in these regions so GRIDSS
starting ignoring some of the reads.

> Is this warning important?

Each one of those messages indicates that 5% of the remaining putative
SV-supporting reads was ignored and the local assembly was rerun. You get
that message more than once for the same interval because that interval had
5% repeatedly removed until the assembly succeeded.

> And will it affect my results?

Unlikely to have any material impact. It's only in the (narrow) intervals
specified and only for the assembly step - all reads are still counted when
doing the actual variant calling step (it's just that some of the reads
won't be counted as also assembly-supporting reads).

The vast majority of regions that encounter this warning are regions where
the read mapping is suspicious anyway.
