### ISSUE TITLE
External aligner always uses all cores

### ISSUE THREAD

**Issue by mpinese** [PapenfussLab/gridss#63]
On be00baa84178962e368d625f6df55c7169393df4, the external aligner is always called with all cores during the realignment step, regardless of the THREADS= command line setting.

Looking into the code I think the line responsible is https://github.com/PapenfussLab/gridss/blob/e6ca8cfdeb7a4a46b69e61612e0cd3048715723c/src/main/java/au/edu/wehi/idsv/SplitReadRealigner.java#L36 where workerThreads is always set to Runtime.getRuntime().availableProcessors().

**Comment by d-cameron** [comment]
Thanks for the report. The WORKER_THREADS parameter was missing from SoftClipsToSplitReads thus resulting in the missing setWorkerThreads() call.

**Comment by d-cameron** [comment]
Fixed in https://github.com/PapenfussLab/gridss/releases/tag/v1.3.2
