### ISSUE TITLE
Docker gridss image cannot find reference genome

### ISSUE THREAD

**Issue by mxiong2** [PapenfussLab/gridss#634]
The reference genome path is specify correctly, but I consistently get an error to set the reference location. Any thoughts?

Thu Jul  6 14:46:02 UTC 2023: Missing reference genome /media/sf_ncbi/GRCh38.d1.vd1.fa. Specify reference location using the --reference command line argument

"exit $EX_USAGE" command completed with exit code 64.

*****

The underlying error message can be found in /media/sf_ncbi/gridss_out/gridss_tmp/gridss.full.20230706_144602.df195842c4e0.371.log

*****

**Comment by d-cameron** [comment]
Have you mounted the reference genome  directory in the docker image?
Docker paths are relative to the image itself, not the host paths and the
docker image only has access to the paths on the host file system that are
explicitly mounted.

**Comment by mxiong2** [comment]
Thanks d-cameron, 

Do all path need to be mounted into the docker image? i.e the temp directory , output directory?

**Comment by d-cameron** [comment]
https://github.com/PapenfussLab/gridss/blob/master/docker/run_cohort_from_csv.sh#L117 is a good example of the recommended docker mounting points.

**Comment by d-cameron** [comment]
Temp directory does not (since /tmp exist in the image and you don't need anything out of it when you're done) but the input and output directories (including the working directory) should be mounted.
