### ISSUE TITLE
T2T reference

### ISSUE THREAD

**Issue by BethHudson-Lund** [PapenfussLab/gridss#637]
Hi!

I have recently aligned WGS of human tumour to the T2T-CHM13v2.0 reference genome and am hoping to call somatic SVs. 
Is GRIDSS2 compatible with the T2T reference?

Thanks for your help :)

**Comment by d-cameron** [comment]
GRIDSS2 is not tied to any specific reference genome so should work with that T2T reference without issue.

GRIDSS2 requires some additional files which are generated from the reference (e.g. a bwa index) so make sure the first time you run GRIDSS against a new reference you only run one instance of GRIDSS. Having multiple processing creating a bwa index at the same time will result in a corrupted index.
