### ISSUE TITLE
Blacklist errror

### ISSUE THREAD

**Issue by uretaj** [PapenfussLab/gridss#642]
Hi,

I'm using hs37d5 as my reference and ENCFF001TDO.bed that I downloaded from here (https://github.com/PapenfussLab/gridss/tree/master/example) but I'm getting this error
`IntervalBed	Error loading record 268 of ENCFF001TDO.bed: 'M' not found in reference genome.
Exception in thread "main" java.lang.IllegalArgumentException: Error loading record 268 of ENCFF001TDO.bed: 'M' not found in reference genome.`

**Comment by d-cameron** [comment]
That will be a chromosome naming convention difference between your
reference and the blacklist - specifically that error is the mitochondrial
chromosome name. Make sure the .bed and .fa reference you use have matching
chromosome names.
