### ISSUE TITLE
Assemble  step error

### ISSUE THREAD

**Issue by poddarharsh15** [PapenfussLab/gridss#648]
Hello, 
I am trying to run GRIDSS on BAM files, however during the process it gives me some errors that I couldn't figure out could you please suggest me some advice?
Thanks. 

[gridss.full.20231115_110358.flgambardella01.256857.log](https://github.com/PapenfussLab/gridss/files/13363191/gridss.full.20231115_110358.flgambardella01.256857.log)

```
- [ ] [ ] gridss -r /home/tigem/h.poddar/input/reference_genome/GRCh38.primary_assembly.genome.fa -j /home/tigem/h.poddar/anaconda3/envs/GRIDSS/share/gridss-2.13.2-2/gridss.jar -t 8 -s assemble -a ~/input/GRIDSS/assembly.bam -w ~/input/GRIDSS  --jvmheap 15g --otherjvmheap 15g --skipsoftcliprealignment /home/tigem/h.poddar/input/lumpy/sample_sorted.bam
- [ ] [ ] Using working directory "/home/tigem/h.poddar/input/GRIDSS
```

**Comment by d-cameron** [comment]
>it gives me some errors that I couldn't figure out could you please suggest me some advice?

There's no `ERROR` messages in that log. That output is what you'd expect. What isn't expected is the GRIDSS run starting with

`INFO	2023-11-15 11:03:59	AssemblyEvidenceSource	Starting assembly on chunk 14 `

That log looks very much like you'd previously run GRIDSS, the job was killed (probably ran out of your time allocation on your HPC cluster), and GRIDSS was restarting where it left off.

Give your GRIDSS job more time before killing it. It's running, but the job is getting killed before it can finish.

**Comment by d-cameron** [comment]
It could also have been killed by running out of memory you set `--jvmheap 15g --otherjvmheap 15g` but the default recommended memory is 31Gb. If you don't have 32Gb of memory on the machine you're running it on then change `-t 8` to `-t 4` so you're only running 4 threads at once instead of 8. This will approximately halve your memory usage so it should fit within the 15gb you've given it.

**Comment by d-cameron** [comment]
Also be aware that `--skipsoftcliprealignment` is an experimental setting has has not been extensively test.

**Comment by poddarharsh15** [comment]
Thank you for answering, I tried to rub the pipeline again with 4 threads but still it's get killed after couple of minutes. 
![Screenshot from 2023-11-20 13-34-18](https://github.com/PapenfussLab/gridss/assets/45700858/3ed52f8c-a4e6-49a1-aabb-91c39fd632a9)
[gridss.full.20231120_132758.flgambardella01.26468.log](https://github.com/PapenfussLab/gridss/files/13414636/gridss.full.20231120_132758.flgambardella01.26468.log)
Could you please check these results?

**Comment by d-cameron** [comment]
Exit code 137 indicated killed due to out of memory. You'll need to reduce
thread count further or use a machine with more memory.

**Comment by poddarharsh15** [comment]
Hello again, I reduced the thread count to 2 and then 1 but still gives the same error with 137 exit code I assume I need to run the GRIDSS on cluster to provide more memory and time to run.
