### ISSUE TITLE
GRIDDS results benchmarking queries:

### ISSUE THREAD

**Issue by poddarharsh15** [PapenfussLab/gridss#649]
Hello, I'm attempting to benchmark GRIDSS output using Truvari with GIAB truth sets. However, I've observed that a significant portion of the structural variant (SV) detections are labeled as BND (breakend) rather than DEL (deletion), INS (insertion), or DUP (duplication). I'm seeking guidance on the possible methods to accurately identify and categorize these BND events into DEL, INS, or DUP. Your assistance is greatly appreciated. Thank you.

**Comment by d-cameron** [comment]
https://github.com/PapenfussLab/gridss?tab=readme-ov-file#why-are-all-calls-bnd

**Comment by poddarharsh15** [comment]
Hello,
Thank you for your previous response. I attempted to use simple-event-annotation.R but encountered errors. Despite this, I managed to generate the .vcf file with INS;DUP;DEL events. Could you please review the error details attached and provide any insights or suggestions for resolution?
![Screenshot from 2024-01-02 15-57-56](https://github.com/PapenfussLab/gridss/assets/45700858/dfeb7d0b-9339-402f-8092-53bada1329bf)
