### ISSUE TITLE
assembly error

### ISSUE THREAD

**Issue by alkodsi** [PapenfussLab/gridss#65]
I'm getting this error. I'm not interested in these chromosomes, is there a way to exclude them?

> ERROR   2017-03-02 11:43:33     PositionalAssembler     Error assembling chrUn_JTFH01001998v1_decoy. This 
> should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues
> java.lang.AssertionError
>         at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.advance(PathSimplificationItera
> tor.java:217)
>         at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.ensureBuffer(PathSimplification
> Iterator.java:171)
>         at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.hasNext(PathSimplificationItera
> tor.java:147)
>         at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.nextPosition(NonReferenceConti
> gAssembler.java:302)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeMisassembledPartialConti
> g(NonReferenceContigAssembler.java:287)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:227)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:176)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:68)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:108)
>

**Comment by d-cameron** [comment]
You could use BLACKLIST=excluded.bed to exclude the contigs that you are not interested in but it sounds very much like the error that I fixed earlier today:

https://github.com/PapenfussLab/gridss/releases/tag/v1.3.2
