### ISSUE TITLE
Unable to run GRIDSS jar

### ISSUE THREAD

**Issue by vialimju** [PapenfussLab/gridss#652]
Hi,

I ran virusbreakend that I installed under gridss (mamba environment)

virusbreakend
-r /mnt/storage/resources/references/hg38/hg38.fa 
-j ~/gridss-2.2.3-gridss-jar-with-dependencies.jar 
-o MNH053_CF_virusbreakend.vcf 
--db ~/virusbreakenddb_20210401 MNH053_CF/MNH053_CF.bam

but I got

Error: Could not find or load main class gridss.Echo
Caused by: java.lang.ClassNotFoundException: gridss.Echo
Wed Jan 10 17:54:19 GMT 2024: Unable to run GRIDSS jar. Java 1.8 or later is required.
Wed Jan 10 17:54:19 GMT 2024: java version: openjdk version "21.0.1-internal" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 21.0.1-internal-adhoc.conda.src, mixed mode, sharing)
Wed Jan 10 17:54:19 GMT 2024: Exit status 0 for exit $EX_CONFIG

and when I checked which java that I got, it says "/home/silvia/mambaforge/envs/gridss2/bin/java"

I thought when I installed gridss, all dependencies including openjdk were also installed. Am I missing something here?

Thanks!

**Comment by d-cameron** [comment]
>gridss-2.2.3-gridss-jar-with-dependencies.jar

That version of GRIDSS is so old that it doesn't have the `gridss.Echo` command required by virusbreakend. Try GRIDSS version 2.13.2.

**Comment by vialimju** [comment]
Thank you, that works now!

**Comment by HuangYihang1222** [comment]
I want to know how to install the latest version of gridss via conda? I can only install `gridss-2.8.0-0` using conda
