### ISSUE TITLE
Input BAM not recognized

### ISSUE THREAD

**Issue by espelpz** [PapenfussLab/gridss#653]
Hi,

I am trying to run gridss but I am getting the following error despite the bam file exists and the path is correct:

> (base) elpz@picasso:/mnt2/fscratch/users/b02_cimes_uma/elpz/lhodgkin_try3/014LH19/results/8_applybqsr/0/014LH19> gridss -r /mnt/home/users/b02_cimes_uma/elpz/genomas_ref/references/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta -o 014LH19_gridss_all_calls.vcf /mnt2/fscratch/users/b02_cimes_uma/elpz/lhodgkin_try3/014LH19/results/8_applybqsr/0/014LH19/0_014LH19.bam /mnt2/fscratch/users/b02_cimes_uma/elpz/lhodgkin_try3/014LH19/results/8_applybqsr/1/014LH19/1_014LH19.bam
> Using working directory "."
> Wed Feb 21 13:56:45 CET 2024: Full log file is: ./gridss.full.20240221_135645.picasso.12919.log
> Wed Feb 21 13:56:45 CET 2024: Found /usr/bin/time
> /usr/bin/time: unrecognized option '--verbose'
> BusyBox v1.32.1 (2021-04-13 11:15:36 UTC) multi-call binary.
> 
> Usage: time [-vpa] [-o FILE] PROG ARGS
> 
> Run PROG, display resource usage when it exits
> 
> 	-v	Verbose
> 	-p	POSIX output format
> 	-f FMT	Custom format
> 	-o FILE	Write result to FILE
> 	-a	Append (else overwrite)
> Wed Feb 21 13:56:45 CET 2024: Using GRIDSS jar /usr/local/share/gridss-2.13.2-2/gridss.jar
> Wed Feb 21 13:56:45 CET 2024: Using reference genome "/mnt/home/users/b02_cimes_uma/elpz/genomas_ref/references/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta"
> Wed Feb 21 13:56:45 CET 2024: Using output VCF 014LH19_gridss_all_calls.vcf
> Wed Feb 21 13:56:45 CET 2024: Using assembly bam 014LH19_gridss_all_calls.vcf.assembly.bam
> Wed Feb 21 13:56:45 CET 2024: Using 8 worker threads.
> Wed Feb 21 13:56:45 CET 2024: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
> Wed Feb 21 13:56:45 CET 2024: Using JVM maximum heap size of 30g for assembly and variant calling.
> **Wed Feb 21 13:56:46 CET 2024: Input file /mnt2/fscratch/users/b02_cimes_uma/elpz/lhodgkin_try3/014LH19/results/8_applybqsr/0/014LH19/0_014LH19.bam does not exist**
> "exit $EX_NOINPUT" command completed with exit code 66.
> *****
> The underlying error message can be found in ./gridss.full.20240221_135645.picasso.12919.log
> *****
> 
> real	0m2,804s
> user	0m3,728s
> sys	0m10,912s

How may I fix this?

Thank you in advance!

Cheers,

Espe

**Comment by d-cameron** [comment]
>Wed Feb 21 13:56:45 CET 2024: Found /usr/bin/time
> /usr/bin/time: unrecognized option '--verbose'

Not sure what your OS is but the root cause is that your version of `/usr/bin/time` does not support the `--verbose` command-line parameter. The workaround is to update/install a `time` version that supports `--verbose`. One such workaround is to use the conda time package https://anaconda.org/conda-forge/time
