### ISSUE TITLE
Indexed block-compressed FASTA file cannot be handled

### ISSUE THREAD

**Issue by keeblee** [PapenfussLab/gridss#659]
I have an issue regarding references.

I built docker image manually using git clone and all requirement software installed.

My command is below.
`docker run --rm -v /disk2/kb/GIAB/NA12878/final_parabricks:/data -v /disk2/references/hg38/GIAB:/reference sv:latest GRIDSS HiSeq_dup.bam hg38 /reference`
(Via ENTRYPOINT) `gridss --reference ${fa} --output ${name}_gridiss.vcf ${bam}`

Log file attached.

How can I fix it?

Tue May  7 08:23:04 UTC 2024: Full log file is: ./gridss.full.20240507_082304.ce336ba252dc.9.log
Tue May  7 08:23:05 UTC 2024: Found /usr/bin/time
Tue May  7 08:23:05 UTC 2024: Using GRIDSS jar /tmp/gridss/gridss-2.13.2-gridss-jar-with-dependencies.jar
Tue May  7 08:23:05 UTC 2024: Using reference genome "/reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz"
Tue May  7 08:23:06 UTC 2024: Using output VCF HiSeq_dup_gridiss.vcf
Tue May  7 08:23:06 UTC 2024: Using assembly bam HiSeq_dup_gridiss.vcf.assembly.bam
Tue May  7 08:23:06 UTC 2024: Using 8 worker threads.
Tue May  7 08:23:06 UTC 2024: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Tue May  7 08:23:06 UTC 2024: Using JVM maximum heap size of 30g for assembly and variant calling.
Tue May  7 08:23:07 UTC 2024: Using input file HiSeq_dup.bam
Tue May  7 08:23:07 UTC 2024: Found /usr/bin/Rscript
Tue May  7 08:23:07 UTC 2024: Found /usr/local/bin/samtools
Tue May  7 08:23:08 UTC 2024: Found /usr/bin/java
Tue May  7 08:23:08 UTC 2024: Found /usr/local/bin/bwa
Tue May  7 08:23:09 UTC 2024: samtools version: 1.20-5-g1592334+htslib-1.20-8-g7576aca1
Tue May  7 08:23:10 UTC 2024: R version: Rscript (R) version 4.4.0 (2024-04-24)
Tue May  7 08:23:10 UTC 2024: bwa Version: 0.7.18-r1243-dirty
Tue May  7 08:23:10 UTC 2024: time version: time (GNU Time) UNKNOWN
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David Keppel, David MacKenzie, and Assaf Gordon.
Tue May  7 08:23:10 UTC 2024: bash version: GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
Tue May  7 08:23:14 UTC 2024: java version: openjdk version "17.0.11" 2024-04-16        OpenJDK Runtime Environment (build 17.0.11+9-Ubuntu-1)  OpenJDK 64-Bit Server VM (build 17.0.11+9-Ubuntu-1, mixed mode, sharing)
Tue May  7 08:23:17 UTC 2024: Max file handles: 1048576
Tue May  7 08:23:17 UTC 2024: Running GRIDSS steps: setupreference, preprocess, assemble, call,
Tue May  7 08:23:17 UTC 2024: Start pre-processing      HiSeq_dup.bam
Tue May  7 08:23:17 UTC 2024: Running   CollectGridssMetrics    HiSeq_dup.bam   first 10000000 records
INFO    2024-05-07 08:23:20     Defaults        Found file for property samjdk.reference_fasta: /reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz 
INFO    2024-05-07 08:23:20     CollectGridssMetrics

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectGridssMetrics -REFERENCE_SEQUENCE /reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz -TMP_DIR ./HiSeq_dup.bam.gridss.working -ASSUME_SORTED true -I HiSeq_dup.bam -O ./HiSeq_dup.bam.gridss.working/tmp.HiSeq_dup.bam -THRESHOLD_COVERAGE 50000 -FILE_EXTENSION null -GRIDSS_PROGRAM null -GRIDSS_PROGRAM CollectIdsvMetrics -PROGRAM null -PROGRAM CollectInsertSizeMetrics -STOP_AFTER 10000000
**********

08:23:22.640 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/tmp/gridss/gridss-2.13.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue May 07 08:23:22 UTC 2024] CollectGridssMetrics GRIDSS_PROGRAM=[CollectIdsvMetrics] THRESHOLD_COVERAGE=50000 INPUT=HiSeq_dup.bam ASSUME_SORTED=true STOP_AFTER=10000000 OUTPUT=./HiSeq_dup.bam.gridss.working/tmp.HiSeq_dup.bam FILE_EXTENSION=null PROGRAM=[CollectInsertSizeMetrics] TMP_DIR=[./HiSeq_dup.bam.gridss.working] REFERENCE_SEQUENCE=/reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz    METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue May 07 08:23:22 UTC 2024] Executing as root@ce336ba252dc on Linux 5.4.0-177-generic amd64; OpenJDK 64-Bit Server VM 17.0.11+9-Ubuntu-1; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.13.2-gridss
INFO    2024-05-07 08:25:01     SinglePassSamProgram    Processed    10,000,000 records.  Elapsed time: 00:01:38s.  Time for last 10,000,000:   95s.  Last read position: chr1:46,771,997
INFO    2024-05-07 08:25:18     RExecutor       Executing R script via command: Rscript /data/./HiSeq_dup.bam.gridss.working/script8717745328748757078.R /data/./HiSeq_dup.bam.gridss.working/tmp.HiSeq_dup.bam.insert_size_metrics /data/./HiSeq_dup.bam.gridss.working/tmp.HiSeq_dup.bam.insert_size_histogram.pdf HiSeq_dup.bam
INFO    2024-05-07 08:25:19     ProcessExecutor null device 
INFO    2024-05-07 08:25:19     ProcessExecutor           1 
[Tue May 07 08:25:20 UTC 2024] gridss.analysis.CollectGridssMetrics done. Elapsed time: 1.96 minutes.
Runtime.totalMemory()=2151677952
Tue May  7 08:25:20 UTC 2024: Running   CollectGridssMetricsAndExtractSVReads|samtools  HiSeq_dup.bam
INFO    2024-05-07 08:25:21     Defaults        Found file for property samjdk.reference_fasta: /reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz 
INFO    2024-05-07 08:25:21     CollectGridssMetricsAndExtractSVReads

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectGridssMetricsAndExtractSVReads -REFERENCE_SEQUENCE /reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz -TMP_DIR ./HiSeq_dup.bam.gridss.working -ASSUME_SORTED true -I HiSeq_dup.bam -O ./HiSeq_dup.bam.gridss.working/HiSeq_dup.bam -THRESHOLD_COVERAGE 50000 -FILE_EXTENSION null -GRIDSS_PROGRAM null -GRIDSS_PROGRAM CollectCigarMetrics -GRIDSS_PROGRAM CollectMapqMetrics -GRIDSS_PROGRAM CollectTagMetrics -GRIDSS_PROGRAM CollectIdsvMetrics -GRIDSS_PROGRAM ReportThresholdCoverage -PROGRAM null -PROGRAM CollectInsertSizeMetrics -SV_OUTPUT /dev/stdout -COMPRESSION_LEVEL 0 -INSERT_SIZE_METRICS ./HiSeq_dup.bam.gridss.working/tmp.HiSeq_dup.bam.insert_size_metrics -READ_PAIR_CONCORDANT_PERCENT 0.995 -UNMAPPED_READS false -MIN_CLIP_LENGTH 5 -INCLUDE_DUPLICATES true
**********

08:25:22.048 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/tmp/gridss/gridss-2.13.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue May 07 08:25:23 UTC 2024] CollectGridssMetricsAndExtractSVReads MIN_CLIP_LENGTH=5 READ_PAIR_CONCORDANT_PERCENT=0.995 INSERT_SIZE_METRICS=./HiSeq_dup.bam.gridss.working/tmp.HiSeq_dup.bam.insert_size_metrics UNMAPPED_READS=false INCLUDE_DUPLICATES=true SV_OUTPUT=/dev/stdout GRIDSS_PROGRAM=[CollectCigarMetrics, CollectMapqMetrics, CollectTagMetrics, CollectIdsvMetrics, ReportThresholdCoverage] THRESHOLD_COVERAGE=50000 INPUT=HiSeq_dup.bam ASSUME_SORTED=true OUTPUT=./HiSeq_dup.bam.gridss.working/HiSeq_dup.bam FILE_EXTENSION=null PROGRAM=[CollectInsertSizeMetrics] TMP_DIR=[./HiSeq_dup.bam.gridss.working] COMPRESSION_LEVEL=0 REFERENCE_SEQUENCE=/reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz    MIN_INDEL_SIZE=1 CLIPPED=true INDELS=true SPLIT=true SINGLE_MAPPED_PAIRED=true DISCORDANT_READ_PAIRS=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue May 07 08:25:23 UTC 2024] Executing as root@ce336ba252dc on Linux 5.4.0-177-generic amd64; OpenJDK 64-Bit Server VM 17.0.11+9-Ubuntu-1; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.13.2-gridss
INFO    2024-05-07 08:25:25     SAMFileWriterFactory    Unknown file extension, assuming BAM format when writing file: file:///dev/stdout
[Tue May 07 08:25:27 UTC 2024] gridss.CollectGridssMetricsAndExtractSVReads done. Elapsed time: 0.10 minutes.
Runtime.totalMemory()=2151677952
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Exception when running gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:253)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:134)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:126)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:598)
        at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:78)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:196)
        at gridss.CollectGridssMetricsAndExtractSVReads.main(CollectGridssMetricsAndExtractSVReads.java:56)
Caused by: java.lang.RuntimeException: Exception when running gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram
        at picard.analysis.SinglePassSamProgram.raiseAsyncException(SinglePassSamProgram.java:282)
        at picard.analysis.SinglePassSamProgram.asyncAcceptRead(SinglePassSamProgram.java:273)
        at picard.analysis.SinglePassSamProgram.asyncAcceptReads(SinglePassSamProgram.java:263)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:216)
        ... 7 more
Caused by: htsjdk.samtools.SAMException: Indexed block-compressed FASTA file cannot be handled: /reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:84)
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:62)
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:71)
        at gridss.cmdline.ReferenceCommandLineProgram.getReference(ReferenceCommandLineProgram.java:57)
        at gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram.acceptRead(ByReadNameSinglePassSamProgram.java:162)
        at picard.analysis.SinglePassSamProgram$SinglePassSamProgramRunner.run(SinglePassSamProgram.java:320)
        at java.base/java.lang.Thread.run(Thread.java:840)
[W::hts_set_opt] Cannot change block size for this format
samtools sort: failed to read header from "/dev/stdin"

**Comment by d-cameron** [comment]
>How can I fix it?

Decompress `/reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz` and use  `/reference/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta` as the reference file.

**Comment by d-cameron** [comment]
There are no plans to support compressed references.
