### ISSUE TITLE
Suggestion - use BAM:SM tag to name the sample in VCF

### ISSUE THREAD

**Issue by drmjc** [PapenfussLab/gridss#71]
Hi,
Most variant callers that I've used name the sample in the VCF using the BAM SM tag. This would help the VCF fit in existing workflows a bit more seamlessly.
cheers

**Comment by d-cameron** [comment]
GRIDSS does not currently support multiple read groups per input file, but I've added it to the TODO list.

**Comment by d-cameron** [comment]
Would using the @RG SM value as the default sample name then falling back to file name if no read group header is present work for your use case?

**Comment by drmjc** [comment]
Yes, that would work really well.
