### ISSUE TITLE
NonReferenceContigAssembler warnings

### ISSUE THREAD

**Issue by melop** [PapenfussLab/gridss#76]
Hello, I am new to GRIDSS. I am trying to use it to identify misassemblies in a de novo assembly project. I see a lot of the following warnings, is this something to worry about? Thanks!

WARNING	2017-04-22 08:38:25	NonReferenceContigAssembler	Sanity check failure. Attempting to flush contig NORscf321:274078-279850 (+919) when graph only loaded to NORscf321:280726. Ignoring flush request.

**Comment by d-cameron** [comment]
Terribly sorry for the late response: no that's not something to worry about. I've been investigating it and although there is an issue with an edge case, that warning message is because the sanity checks identifies it and prevents the error from occurring.
