### ISSUE TITLE
Error about sam header

### ISSUE THREAD

**Issue by cboursnell** [PapenfussLab/gridss#90]
I get this error message:

```
INFO	2017-08-07 15:15:15	ExternalProcessFastqAligner	Invoking external aligner
INFO	2017-08-07 15:15:15	ExternalProcessFastqAligner	bwa mem -t 8 genome.fa normal.sort.bam.realign.0.fq
[Mon Aug 07 15:15:15 BST 2017] gridss.SoftClipsToSplitReads done. Elapsed time: 1.91 minutes.
Runtime.totalMemory()=6502219776
ERROR	2017-08-07 15:15:15	CallVariants	Fatal exception thrown by worker thread.
htsjdk.samtools.SAMFormatException: Error parsing SAM header. @SQ line missing LN tag. Line:
@SQ	SN:JTF; ; Line number 2489
```

I've checked the sam header at line 2489 and it looks fine: 
```
@SQ	SN:JTFH01001906.1	LN:2475
```
The bam files were created with `bwa mem` using default settings.

Full log: https://gist.github.com/cboursnell/7c8276dbc20eaacd360287a56eda0832

**Comment by d-cameron** [comment]
The error is occurring when attempting to identify additional split reads. This step involves invoking bwa and it is this header, not the header of the input file that GRIDSS is complaining about.

What does the sam header look like when running:
```
bwa mem -t 8 genome.fa ./normal.sort.bam.gridss.working/normal.sort.bam.realign.0.fq
```

**Comment by cboursnell** [comment]
Maybe this is why: 
```
chris@i3:gridss$ bwa mem -t 8 genome.fa ./normal.sort.bam.gridss.working/normal.sort.bam.realign.0.fq -o test.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 94638 sequences (5079940 bp)...
Segmentation fault (core dumped)
```
Seems like there's a problem with bwa-0.7.16. Tried with bwa-0.7.15 and it didn't seg fault. I'll pass this along to them.

**Comment by d-cameron** [comment]
Is there a message (anywhere in the log) that looks like the following:
```
Subprocess terminated with with exit status %1$d. Alignment failed for %2$s executing "%3$s".
```
That message is supposed to display when the aligner has a non-zero exit status.
