### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by chirrie** [PapenfussLab/gridss#98]
Command used:
java -Xmx31g -cp gridss-1.4.3-jar-with-dependencies.jar gridss.CallVariants REFERENCE_SEQUENCE=capra.fa INPUT=sample.sorted.bam ASSEMBLY=assembly.bam OUTPUT=sample-gridss.vcf

Error 1:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[Fri Nov 10 11:27:04 EAT 2017] gridss.CallVariants OUTPUT=sample.gridss.vcf ASSEMBLY=assembly.bam INPUT=[sample.sorted.bam] REFERENCE_SEQUENCE=c$
[Fri Nov 10 11:27:04 EAT 2017] Executing as vchebii@taurus on Linux 2.6.32-696.10.3.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_$
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

Another error I get is this

Fri Nov 10 14:42:00 EAT 2017] gridss.ExtractSVReads done. Elapsed time: 56.15 minutes.
Runtime.totalMemory()=1520959488
INFO    2017-11-10 14:42:00     SAMFileUtil     Sorting /home/vchebii/sample.sorted.bam.gridss.working/gridss.tmp.extracted.Ibe$
ERROR   2017-11-10 15:06:35     CallVariants    Fatal exception thrown by worker thread.
htsjdk.samtools.util.RuntimeIOException: java.io.IOException: No space left on device

What should I do?  I am running it on a cluster and I think their is enough space...
This ran for 2.5 hours before before raising the error..
How can I can configure the commands to run  in batch?

**Comment by d-cameron** [comment]
By default, GRIDSS uses the same code as Picard tools to store intermediate files when sorting SAM/BAM. The default location is `/tmp` so it is quite possible you have filled up the /tmp drive on the cluster node (I've had this happen to me with other tools as well).

The temporary file location can be overridden by specifying a `TMP_DIR` parameter to the GRIDSS command-line (this is the same approach used by the Picard tools SortSam utility). A location on the same mount point as the BAM files is likely to work. For this reason, the GRIDSS example script has `TMP_DIR=.` as the recommended location.
