### ISSUE TITLE
Error in library(devtools) : there is no package called ‘devtools’  

### ISSUE THREAD

**Issue by chirrie** [PapenfussLab/gridss#99]
I have a VCF file  outputted from gridss analysis. So how do I extract various variations events from it like duplications and deletions? The VCF file looks complicated to  figure out...

I have checked through the manual and their is an option to use StructuralVariantAnnotation, but on following installation  instructions I get an error library(devtools) not available... same to the example somatic.R script provided... 

Error in library(devtools) : there is no package called ‘devtools’

I am just stuck.. Is there an easy command line just  to input the vcf file and get the  variations events?

**Comment by d-cameron** [comment]
> Error in library(devtools) : there is no package called ‘devtools’

StructuralVariantAnnotation requires the devtools library to be installed. You can install this library by running `install.packages("devtools")` in R.


> I have a VCF file outputted from gridss analysis. So how do I extract various variations events from it like duplications and deletions? The VCF file looks complicated to figure out...

GRIDSS reports variants in the VCF breakend notation. It is indeed complicated but is the only way to report inter-chromosomal events in VCF. If you are only interested in simple events, the https://github.com/PapenfussLab/gridss/blob/master/example/simple-event-annotation.R can be used to convert the variant calls into a simple BED file.

>I am just stuck.. Is there an easy command line just to input the vcf file and get the variations events?

1. Save a local copy of simple-event-annotation.R

2. Install the prerequisite R packages (uncomment lines 1-4, run them, then comment them out again - this only needs to be done once, note that you'll first need devtools installed as per the StructuralVariantAnnotation package documentation)

3. Edit lines 17, 23 and 41 of simple-event-annotation.R to match your filenames

4. Run simple-event-annotation.R

This will output a simple BED file containing only well supported INS/INV/DEL/DUP events.

**Comment by chirrie** [comment]
I am getting this errors on running the simple-event-annotation.R.....  It is really an up hill to get this tool working....


 DONE (AnnotationDbi)
ERROR: dependencies ‘XML’, ‘RCurl’ are not available for package ‘biomaRt’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/biomaRt’
ERROR: dependencies ‘GenomicRanges’, ‘GenomeInfoDb’ are not available for package ‘SummarizedExperiment’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/SummarizedExperiment’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’ are not available for package ‘Rsamtools’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/Rsamtools’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘Rsamtools’ are not available for package ‘GenomicAlignments’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/GenomicAlignments’
ERROR: dependencies ‘GenomicRanges’, ‘XML’, ‘GenomeInfoDb’, ‘RCurl’, ‘Rsamtools’, ‘GenomicAlignments’ are not available for package ‘rtracklayer’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/rtracklayer’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘rtracklayer’, ‘Rsamtools’ are not available for package ‘BSgenome’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/BSgenome’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘RCurl’, ‘rtracklayer’, ‘biomaRt’ are not available for package ‘GenomicFeatures’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/GenomicFeatures’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘Rsamtools’, ‘BSgenome’, ‘rtracklayer’, ‘GenomicFeatures’ are not available for package ‘VariantAnnotation’
* removing ‘/home/vchebii/R/x86_64-pc-linux-gnu-library/3.3/VariantAnnotation’

The downloaded source packages are in
        ‘/tmp/RtmpChHo51/downloaded_packages’
installation path not writeable, unable to update packages: boot, cluster,
  foreign, lattice, MASS, Matrix, mgcv, rpart, survival
There were 12 warnings (use warnings() to see them)
Error: could not find function "install_github"
Execution halted

**Comment by d-cameron** [comment]
>It is really an up hill to get this tool working....

It shouldn't be, but it appears your environment lacks most of the dependencies that GRIDSS (technically, it's the R StructuralVariantAnnotation package) relies on.

In this particular case, you are missing required R libraries. It looks like your installation of R packages failed. Installation can fail for many reasons, and the log file indicates the issue was not with GRIDSS or StructuralVariantAnnotation, but an issue with updating VariantAnnotation BioConductor package (and/or upstream packages).

`installation path not writeable, unable to update packages: boot, cluster,`

It looks like you don't have permission to update your R environment. This is common for server installations as it prevents users corruption other users' R environments (e.g. by updating or uninstalling a package they are currently using). The best point of contact for this is your system administrator (who should have write permission), or the BioConductor support site (https://support.bioconductor.org/).
